MODULE M_DIFF_Z_CF12_BWD_SARAP_VAR
  DOUBLE PRECISION, DIMENSION(:), POINTER :: diff_z_bwd
  DOUBLE PRECISION, DIMENSION(:), POINTER :: dcf1_bwd
  DOUBLE PRECISION, DIMENSION(:), POINTER :: dcf2_bwd
END MODULE M_DIFF_Z_CF12_BWD_SARAP_VAR
