MODULE M_DIFF_Z_CF12_FWD_SARAP_VAR
  DOUBLE PRECISION, DIMENSION(:), POINTER :: diff_z_fwd
  DOUBLE PRECISION, DIMENSION(:), POINTER :: dcf1_fwd
  DOUBLE PRECISION, DIMENSION(:), POINTER :: dcf2_fwd
END MODULE M_DIFF_Z_CF12_FWD_SARAP_VAR
