      block data MED_SET_IT

      implicit none

      include "med_parameter.hf"

      common /MED/ MED_GET_CELL_GEOMETRY_TYPE
      integer MED_GET_CELL_GEOMETRY_TYPE(MED_N_CELL_FIXED_GEO)
      save /MED/
      data MED_GET_CELL_GEOMETRY_TYPE /
     &  MED_POINT1, MED_SEG2, MED_SEG3,
     &  MED_SEG4, MED_TRIA3, MED_QUAD4, MED_TRIA6,
     &  MED_TRIA7, MED_QUAD8, MED_QUAD9, MED_TETRA4,
     &  MED_PYRA5, MED_PENTA6, MED_HEXA8, MED_TETRA10,
     &  MED_OCTA12, MED_PYRA13, MED_PENTA15, MED_PENTA18, MED_HEXA20,
     &  MED_HEXA27, MED_POLYGON, MED_POLYGON2,MED_POLYHEDRON /

      END
