{% set name = "opentelemac" %}
{% set version = "main" %}
{% set build = 0 %}
{% set python = python or '3.10' %}  # Default to 3.10 if not specified
{% set numpy = numpy or '1.21' %}    # Default to 1.21 if not specified
{% set mpi = "openmpi" %}     # Default to "openmpi" if not specified


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/-/archive/{{ version }}/telemac-mascaret-{{ version }}.tar.gz
    folder: opentelemac
    sha256: 45468b850c8271c21f7d6ef7017945c297dfc3b670c3cde706d71124189d6396
    patches:
      - global.patch

build:
  {% set mpi_prefix = "mpi_" + mpi %}
  {% set py_prefix = "py_" + python %}
  {% set np_prefix = "np_" + numpy %}
  string: {{ mpi_prefix }}_{{ py_prefix }}_{{ np_prefix }}_{{ build }}
  number: {{ build }}
  script_env:
    - TELEMAC_VERSION={{ version }}
  skip_compile_pyc:
    - "*/examples/*"
    - "*/notebooks/*"

outputs: 
  - name: {{ name }}-examples
    build:
      script: "%RECIPE_DIR%/build-examples.bat" # [win]
      script: "$RECIPE_DIR/build-examples.sh"   # [not win]

  - name: {{ name }}-documentation
    build:
      script: "%RECIPE_DIR%/build-documentation.bat" # [win]
      script: "$RECIPE_DIR/build-documentation.sh"   # [not win]
  
  - name: {{ name }}
    requirements:
      host:
        # Windows
        - m2-sed                    # [win]
        - m2w64-metis               # [win]
        - m2w64-toolchain           # [win]
        - m2w64-dlfcn               # [win]
        - m2w64-msmpi               # [win]
        - mumps-otm                 # [win]
        - scalapack-otm             # [win]
        # Linux / MacOS
        - {{ compiler('fortran') }} # [not win]
        - {{ mpi }}                 # [not win]
        - {{ mpi }}-mpifort         # [not win]
        - {{ compiler('gcc') }}     # [not win]
        - {{ compiler('gxx') }}     # [not win]
        - binutils                  # [not win]
        - hdf5                      # [not win]
        - metis                     # [not win]
        - libmed                    # [not win]
        - mumps-mpi                 # [not win]
        - scalapack                 # [not win]
        - parmetis                  # [not win]
        - gotm-otm                  # [not win]
        # Vendors
        - med-otm
        - aed2-otm
        # Python
        - matplotlib
        - numpy {{ numpy }}*
        - python {{ python }}
        - scipy
      run:
        # Windows
        - m2-sed                    # [win]
        - m2w64-metis               # [win]
        - m2w64-toolchain           # [win]
        - m2w64-dlfcn               # [win]
        - m2w64-msmpi               # [win]
        - mumps-otm                 # [win]
        - scalapack-otm             # [win]
        # Linux / MacOS
        - {{ compiler('fortran') }} # [not win]
        - {{ mpi }}                 # [not win]
        - {{ mpi }}-mpifort         # [not win]
        - {{ compiler('gcc') }}     # [not win]
        - {{ compiler('gxx') }}     # [not win]
        - binutils                  # [not win]
        - hdf5                      # [not win]
        - metis                     # [not win]
        - libmed                    # [not win]
        - mumps-mpi                 # [not win]
        - scalapack                 # [not win]
        - parmetis                  # [not win]
        - gotm-otm                  # [not win]
        # Vendors
        - med-otm
        - aed2-otm
        # Python
        - matplotlib
        - mpi4py
        - numpy {{ numpy }}*
        - python {{ python }}
        - scipy
    # test:
    #   script: run_test.bat

about:
  home: http://www.opentelemac.org/
  license: GPLv3
  summary: openTelemac
  description: |
    The TELEMAC-MASCARET system is an integrated suite of solvers for use in the
    field of free-surface flow.
  doc_url: https://gitlab.pam-retd.fr/otm/telemac-mascaret/
  dev_url: https://github.com/nicogodet/telemac-mascaret-feedstock

extra:
  recipe-maintainers:
    - nicogodet
    - brey
    - tomsail
