/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             7566,
                                             2693,
                                             "Strand Editor",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  TecGUIFrameAdd(Dialog1Manager,
             3349,
             1307,
             4071,
             653,
                    "Solution Time");

  TecGUIFrameAdd(Dialog1Manager,
             3349,
             2019,
             4071,
             274,
                    "Parent Zone");

  TecGUIFrameAdd(Dialog1Manager,
             3363,
             122,
             4071,
             793,
                    "Data Specifications");

  TecGUIFrameAdd(Dialog1Manager,
             3349,
             974,
             4071,
             274,
                    "StrandID");

  ZoneList_MLST_D1 = TecGUIListAdd(Dialog1Manager,
                                 194,
                                 157,
                                 3043,
                                 1873,
                       1,
                       ZoneList_MLST_D1_CB);

  MultiZone_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                   3571,
                                   227,
                                   3835,
                                   122,
                               "&Multiple Zones Per Time Step",
                               MultiZone_TOG_D1_CB);

  Grouping_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                      3501,
                                      536,
                                      1639,
                                      297,
                                 "T&ime Step",
                                 "St&rand",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 Grouping_RADIO_D1_CB);

  GroupSize_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                     5711,
                                     536,
                                     1111,
                                     145,
                       GroupSize_TF_D1_CB);

  AssignStrandID_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                        3488,
                                        1085,
                                        2376,
                                        122,
                               "Assign &Strands",
                               AssignStrandID_TOG_D1_CB);

  StrandID_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                    6434,
                                    1056,
                                    819,
                                    145,
                       StrandID_TF_D1_CB);

  AssignSolutionTime_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                            3488,
                                            1406,
                                            2987,
                                            122,
                               "Assign Solution &Time",
                               AssignSolutionTime_TOG_D1_CB);

  TimeOption_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                        3488,
                                        1575,
                                        2112,
                                        297,
                                 "Single &Value",
                                 "Constant &Delta",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 TimeOption_RADIO_D1_CB);

  SolutionTime_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                        6323,
                                        1552,
                                        931,
                                        145,
                       SolutionTime_TF_D1_CB);

  SolutionTimeDelta_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                             6323,
                                             1768,
                                             931,
                                             145,
                       SolutionTimeDelta_TF_D1_CB);

  AssignParent_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                      3488,
                                      2130,
                                      2265,
                                      122,
                               "Assign &Parent",
                               AssignParent_TOG_D1_CB);

  ParentZone_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                      6323,
                                      2101,
                                      931,
                                      145,
                       ParentZone_TF_D1_CB);

  Apply_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                               4711,
                               2346,
                               1556,
                               145,
                    "&Apply           ",
                    Apply_BTN_D1_CB);

  LBL9_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             194,
                             46,
                    "Zones to edit:");

  StrandGroupSize_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                        5711,
                                        402,
                    "Group Size:");

  TimeDelta_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                  5669,
                                  1803,
                    "Delta:");

  StrandID_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                 5669,
                                 1091,
                    "Value:");

  ParentValue_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                    5669,
                                    2142,
                    "Value:");

  LBL19_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              3501,
                              402,
                    "Zones Grouped By:");

  SelectedStrandID_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                         1667,
                                         2264,
                    "StrandID");

  SelectedSolutionTime_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                             1667,
                                             2416,
                    "Solution Time");

  LBL22_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              194,
                              2416,
                    "Solution Time:");

  LBL23_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              194,
                              2264,
                    "StrandID:");

  LBL24_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                              194,
                              2112,
                    "Selected Zone Info:");

  TimeValue_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                                  5669,
                                  1593,
                    "Value:");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
