/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  ZoneList_MLST_D1;
extern LgIndex_t  MultiZone_TOG_D1;
extern LgIndex_t  Grouping_RADIO_D1;
extern LgIndex_t  GroupSize_TF_D1;
extern LgIndex_t  AssignStrandID_TOG_D1;
extern LgIndex_t  StrandID_TF_D1;
extern LgIndex_t  AssignSolutionTime_TOG_D1;
extern LgIndex_t  TimeOption_RADIO_D1;
extern LgIndex_t  SolutionTime_TF_D1;
extern LgIndex_t  SolutionTimeDelta_TF_D1;
extern LgIndex_t  AssignParent_TOG_D1;
extern LgIndex_t  ParentZone_TF_D1;
extern LgIndex_t  Apply_BTN_D1;
extern LgIndex_t  LBL9_LBL_D1;
extern LgIndex_t  StrandGroupSize_LBL_D1;
extern LgIndex_t  TimeDelta_LBL_D1;
extern LgIndex_t  StrandID_LBL_D1;
extern LgIndex_t  ParentValue_LBL_D1;
extern LgIndex_t  LBL19_LBL_D1;
extern LgIndex_t  SelectedStrandID_LBL_D1;
extern LgIndex_t  SelectedSolutionTime_LBL_D1;
extern LgIndex_t  LBL22_LBL_D1;
extern LgIndex_t  LBL23_LBL_D1;
extern LgIndex_t  LBL24_LBL_D1;
extern LgIndex_t  TimeValue_LBL_D1;
