# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_medlibrary')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_medlibrary')
    _medlibrary = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_medlibrary', [dirname(__file__)])
        except ImportError:
            import _medlibrary
            return _medlibrary
        try:
            _mod = imp.load_module('_medlibrary', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _medlibrary = swig_import_helper()
    del swig_import_helper
else:
    import _medlibrary
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator_medlibrary_module(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator_medlibrary_module, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator_medlibrary_module, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _medlibrary.delete_SwigPyIterator_medlibrary_module
    __del__ = lambda self: None

    def value(self):
        return _medlibrary.SwigPyIterator_medlibrary_module_value(self)

    def incr(self, n=1):
        return _medlibrary.SwigPyIterator_medlibrary_module_incr(self, n)

    def decr(self, n=1):
        return _medlibrary.SwigPyIterator_medlibrary_module_decr(self, n)

    def distance(self, x):
        return _medlibrary.SwigPyIterator_medlibrary_module_distance(self, x)

    def equal(self, x):
        return _medlibrary.SwigPyIterator_medlibrary_module_equal(self, x)

    def copy(self):
        return _medlibrary.SwigPyIterator_medlibrary_module_copy(self)

    def next(self):
        return _medlibrary.SwigPyIterator_medlibrary_module_next(self)

    def __next__(self):
        return _medlibrary.SwigPyIterator_medlibrary_module___next__(self)

    def previous(self):
        return _medlibrary.SwigPyIterator_medlibrary_module_previous(self)

    def advance(self, n):
        return _medlibrary.SwigPyIterator_medlibrary_module_advance(self, n)

    def __eq__(self, x):
        return _medlibrary.SwigPyIterator_medlibrary_module___eq__(self, x)

    def __ne__(self, x):
        return _medlibrary.SwigPyIterator_medlibrary_module___ne__(self, x)

    def __iadd__(self, n):
        return _medlibrary.SwigPyIterator_medlibrary_module___iadd__(self, n)

    def __isub__(self, n):
        return _medlibrary.SwigPyIterator_medlibrary_module___isub__(self, n)

    def __add__(self, n):
        return _medlibrary.SwigPyIterator_medlibrary_module___add__(self, n)

    def __sub__(self, *args):
        return _medlibrary.SwigPyIterator_medlibrary_module___sub__(self, *args)
    def __iter__(self): return self
    def __iter__(self):
        return self
SwigPyIterator_medlibrary_module_swigregister = _medlibrary.SwigPyIterator_medlibrary_module_swigregister
SwigPyIterator_medlibrary_module_swigregister(SwigPyIterator_medlibrary_module)

ABSOLUTE_H5IPUBLIC_H = _medlibrary.ABSOLUTE_H5IPUBLIC_H
ABSOLUTE_H5PUBLIC_H = _medlibrary.ABSOLUTE_H5PUBLIC_H
HAVE_CC_C99 = _medlibrary.HAVE_CC_C99
HAVE_CUSERID = _medlibrary.HAVE_CUSERID
HAVE_DLFCN_H = _medlibrary.HAVE_DLFCN_H
HAVE_FTIME = _medlibrary.HAVE_FTIME
HAVE_GETEUID = _medlibrary.HAVE_GETEUID
HAVE_GETPWUID = _medlibrary.HAVE_GETPWUID
HAVE_GETTIMEOFDAY = _medlibrary.HAVE_GETTIMEOFDAY
HAVE_H5IPUBLIC_H = _medlibrary.HAVE_H5IPUBLIC_H
HAVE_H5PUBLIC_H = _medlibrary.HAVE_H5PUBLIC_H
HAVE_INTTYPES_H = _medlibrary.HAVE_INTTYPES_H
HAVE_LIBHDF5 = _medlibrary.HAVE_LIBHDF5
HAVE_MALLOC_H = _medlibrary.HAVE_MALLOC_H
HAVE_MEMORY_H = _medlibrary.HAVE_MEMORY_H
HAVE_PWD_H = _medlibrary.HAVE_PWD_H
HAVE_PYTHON = _medlibrary.HAVE_PYTHON
HAVE_STDBOOL_H = _medlibrary.HAVE_STDBOOL_H
HAVE_STDINT_H = _medlibrary.HAVE_STDINT_H
HAVE_STDLIB_H = _medlibrary.HAVE_STDLIB_H
HAVE_STRINGS_H = _medlibrary.HAVE_STRINGS_H
HAVE_STRING_H = _medlibrary.HAVE_STRING_H
HAVE_SYS_STAT_H = _medlibrary.HAVE_SYS_STAT_H
HAVE_SYS_TIMEB_H = _medlibrary.HAVE_SYS_TIMEB_H
HAVE_SYS_TIME_H = _medlibrary.HAVE_SYS_TIME_H
HAVE_SYS_TYPES_H = _medlibrary.HAVE_SYS_TYPES_H
HAVE_UNISTD_H = _medlibrary.HAVE_UNISTD_H
HAVE__BOOL = _medlibrary.HAVE__BOOL
LT_OBJDIR = _medlibrary.LT_OBJDIR
MED_API_23 = _medlibrary.MED_API_23
MED_CHECK_23FORMAT = _medlibrary.MED_CHECK_23FORMAT
MED_HAVE_FORTRAN = _medlibrary.MED_HAVE_FORTRAN
MED_HAVE_PYTHON = _medlibrary.MED_HAVE_PYTHON
MESGERR = _medlibrary.MESGERR
PACKAGE = _medlibrary.PACKAGE
PACKAGE_BUGREPORT = _medlibrary.PACKAGE_BUGREPORT
PACKAGE_NAME = _medlibrary.PACKAGE_NAME
PACKAGE_STRING = _medlibrary.PACKAGE_STRING
PACKAGE_TARNAME = _medlibrary.PACKAGE_TARNAME
PACKAGE_URL = _medlibrary.PACKAGE_URL
PACKAGE_VERSION = _medlibrary.PACKAGE_VERSION
SIZEOF_FORTRAN_INTEGER = _medlibrary.SIZEOF_FORTRAN_INTEGER
SIZEOF_FORTRAN_INTEGERp8 = _medlibrary.SIZEOF_FORTRAN_INTEGERp8
SIZEOF_HID_T = _medlibrary.SIZEOF_HID_T
SIZEOF_INT = _medlibrary.SIZEOF_INT
SIZEOF_LONG = _medlibrary.SIZEOF_LONG
SIZEOF_LONG_LONG = _medlibrary.SIZEOF_LONG_LONG
STDC_HEADERS = _medlibrary.STDC_HEADERS
TIME_WITH_SYS_TIME = _medlibrary.TIME_WITH_SYS_TIME
VERSION = _medlibrary.VERSION
HDF_VERSION_MAJOR_REF = _medlibrary.HDF_VERSION_MAJOR_REF
HDF_VERSION_MINOR_REF = _medlibrary.HDF_VERSION_MINOR_REF
HDF_VERSION_RELEASE_REF = _medlibrary.HDF_VERSION_RELEASE_REF
HDF_VERSION_NUM_REF = _medlibrary.HDF_VERSION_NUM_REF
H5F_LIBVER_18 = _medlibrary.H5F_LIBVER_18
MED_MAJOR_NUM = _medlibrary.MED_MAJOR_NUM
MED_MINOR_NUM = _medlibrary.MED_MINOR_NUM
MED_RELEASE_NUM = _medlibrary.MED_RELEASE_NUM
MED_3_LATEST_MINOR = _medlibrary.MED_3_LATEST_MINOR
MED_4_LATEST_MINOR = _medlibrary.MED_4_LATEST_MINOR
MED_NUM_MAJEUR = _medlibrary.MED_NUM_MAJEUR
MED_NUM_MINEUR = _medlibrary.MED_NUM_MINEUR
MED_NUM_RELEASE = _medlibrary.MED_NUM_RELEASE
MED_VERSION_STR = _medlibrary.MED_VERSION_STR
MED_MAX_PARA = _medlibrary.MED_MAX_PARA
MED_COMMENT_SIZE = _medlibrary.MED_COMMENT_SIZE
MED_IDENT_SIZE = _medlibrary.MED_IDENT_SIZE
MED_NAME_SIZE = _medlibrary.MED_NAME_SIZE
MED_SNAME_SIZE = _medlibrary.MED_SNAME_SIZE
MED_LNAME_SIZE = _medlibrary.MED_LNAME_SIZE
MED_SNAME_BLANK = _medlibrary.MED_SNAME_BLANK
MED_NAME_BLANK = _medlibrary.MED_NAME_BLANK
MED_PATHNAME_SIZE = _medlibrary.MED_PATHNAME_SIZE
MED_MAX_CHFID_PATH = _medlibrary.MED_MAX_CHFID_PATH
MED_FULL_INTERLACE = _medlibrary.MED_FULL_INTERLACE
MED_NO_INTERLACE = _medlibrary.MED_NO_INTERLACE
MED_UNDEF_INTERLACE = _medlibrary.MED_UNDEF_INTERLACE
MED_UNDEF_STMODE = _medlibrary.MED_UNDEF_STMODE
MED_GLOBAL_STMODE = _medlibrary.MED_GLOBAL_STMODE
MED_COMPACT_STMODE = _medlibrary.MED_COMPACT_STMODE
MED_GLOBAL_PFLMODE = _medlibrary.MED_GLOBAL_PFLMODE
MED_COMPACT_PFLMODE = _medlibrary.MED_COMPACT_PFLMODE
MED_UNDEF_PFLMODE = _medlibrary.MED_UNDEF_PFLMODE
MED_ACC_RDONLY = _medlibrary.MED_ACC_RDONLY
MED_ACC_RDWR = _medlibrary.MED_ACC_RDWR
MED_ACC_RDEXT = _medlibrary.MED_ACC_RDEXT
MED_ACC_CREAT = _medlibrary.MED_ACC_CREAT
MED_ACC_UNDEF = _medlibrary.MED_ACC_UNDEF
MED_UNSTRUCTURED_MESH = _medlibrary.MED_UNSTRUCTURED_MESH
MED_STRUCTURED_MESH = _medlibrary.MED_STRUCTURED_MESH
MED_UNDEF_MESH_TYPE = _medlibrary.MED_UNDEF_MESH_TYPE
MED_CARTESIAN_GRID = _medlibrary.MED_CARTESIAN_GRID
MED_POLAR_GRID = _medlibrary.MED_POLAR_GRID
MED_CURVILINEAR_GRID = _medlibrary.MED_CURVILINEAR_GRID
MED_UNDEF_GRID_TYPE = _medlibrary.MED_UNDEF_GRID_TYPE
MED_CELL = _medlibrary.MED_CELL
MED_DESCENDING_FACE = _medlibrary.MED_DESCENDING_FACE
MED_DESCENDING_EDGE = _medlibrary.MED_DESCENDING_EDGE
MED_NODE = _medlibrary.MED_NODE
MED_NODE_ELEMENT = _medlibrary.MED_NODE_ELEMENT
MED_STRUCT_ELEMENT = _medlibrary.MED_STRUCT_ELEMENT
MED_ALL_ENTITY_TYPE = _medlibrary.MED_ALL_ENTITY_TYPE
MED_UNDEF_ENTITY_TYPE = _medlibrary.MED_UNDEF_ENTITY_TYPE
MED_N_ENTITY_TYPES = _medlibrary.MED_N_ENTITY_TYPES
MED_COORDINATE = _medlibrary.MED_COORDINATE
MED_CONNECTIVITY = _medlibrary.MED_CONNECTIVITY
MED_NAME = _medlibrary.MED_NAME
MED_NUMBER = _medlibrary.MED_NUMBER
MED_FAMILY_NUMBER = _medlibrary.MED_FAMILY_NUMBER
MED_COORDINATE_AXIS1 = _medlibrary.MED_COORDINATE_AXIS1
MED_COORDINATE_AXIS2 = _medlibrary.MED_COORDINATE_AXIS2
MED_COORDINATE_AXIS3 = _medlibrary.MED_COORDINATE_AXIS3
MED_INDEX_FACE = _medlibrary.MED_INDEX_FACE
MED_INDEX_NODE = _medlibrary.MED_INDEX_NODE
MED_GLOBAL_NUMBER = _medlibrary.MED_GLOBAL_NUMBER
MED_VARIABLE_ATTRIBUTE = _medlibrary.MED_VARIABLE_ATTRIBUTE
MED_COORDINATE_TRSF = _medlibrary.MED_COORDINATE_TRSF
MED_UNDEF_DATATYPE = _medlibrary.MED_UNDEF_DATATYPE
MED_INTERNAL_FLOAT32 = _medlibrary.MED_INTERNAL_FLOAT32
MED_INTERNAL_FLOAT64 = _medlibrary.MED_INTERNAL_FLOAT64
MED_INTERNAL_INT32 = _medlibrary.MED_INTERNAL_INT32
MED_INTERNAL_INT64 = _medlibrary.MED_INTERNAL_INT64
MED_INTERNAL_INT = _medlibrary.MED_INTERNAL_INT
MED_INTERNAL_NAME = _medlibrary.MED_INTERNAL_NAME
MED_INTERNAL_SNAME = _medlibrary.MED_INTERNAL_SNAME
MED_INTERNAL_LNAME = _medlibrary.MED_INTERNAL_LNAME
MED_INTERNAL_IDENT = _medlibrary.MED_INTERNAL_IDENT
MED_INTERNAL_CHAR = _medlibrary.MED_INTERNAL_CHAR
MED_INTERNAL_UNDEF = _medlibrary.MED_INTERNAL_UNDEF
MED_DOUBLE = _medlibrary.MED_DOUBLE
MED_FLOAT64 = _medlibrary.MED_FLOAT64
MED_FLOAT32 = _medlibrary.MED_FLOAT32
MED_INT32 = _medlibrary.MED_INT32
MED_INT64 = _medlibrary.MED_INT64
MED_INT = _medlibrary.MED_INT
MED_ATT_FLOAT64 = _medlibrary.MED_ATT_FLOAT64
MED_ATT_INT = _medlibrary.MED_ATT_INT
MED_ATT_NAME = _medlibrary.MED_ATT_NAME
MED_ATT_UNDEF = _medlibrary.MED_ATT_UNDEF
MED_MESH = _medlibrary.MED_MESH
MED_FIELD = _medlibrary.MED_FIELD
MED_LIBRARY = _medlibrary.MED_LIBRARY
MED_FILE = _medlibrary.MED_FILE
MED_MESH_SUPPORT = _medlibrary.MED_MESH_SUPPORT
MED_ELSTRUCT = _medlibrary.MED_ELSTRUCT
MED_FAMILY = _medlibrary.MED_FAMILY
MED_EQUIVALENCE = _medlibrary.MED_EQUIVALENCE
MED_GROUP = _medlibrary.MED_GROUP
MED_JOINT = _medlibrary.MED_JOINT
MED_LOCALIZATION = _medlibrary.MED_LOCALIZATION
MED_PROFILE = _medlibrary.MED_PROFILE
MED_FILTER = _medlibrary.MED_FILTER
MED_INTERPOLATION = _medlibrary.MED_INTERPOLATION
MED_NUMERICAL_DATA = _medlibrary.MED_NUMERICAL_DATA
MED_LINK = _medlibrary.MED_LINK
MED_CLASS_UNDEF = _medlibrary.MED_CLASS_UNDEF
MED_CLASS_ALL = _medlibrary.MED_CLASS_ALL
MED_POINT1 = _medlibrary.MED_POINT1
MED_SEG2 = _medlibrary.MED_SEG2
MED_SEG3 = _medlibrary.MED_SEG3
MED_SEG4 = _medlibrary.MED_SEG4
MED_TRIA3 = _medlibrary.MED_TRIA3
MED_QUAD4 = _medlibrary.MED_QUAD4
MED_TRIA6 = _medlibrary.MED_TRIA6
MED_TRIA7 = _medlibrary.MED_TRIA7
MED_QUAD8 = _medlibrary.MED_QUAD8
MED_QUAD9 = _medlibrary.MED_QUAD9
MED_TETRA4 = _medlibrary.MED_TETRA4
MED_PYRA5 = _medlibrary.MED_PYRA5
MED_PENTA6 = _medlibrary.MED_PENTA6
MED_HEXA8 = _medlibrary.MED_HEXA8
MED_TETRA10 = _medlibrary.MED_TETRA10
MED_OCTA12 = _medlibrary.MED_OCTA12
MED_PYRA13 = _medlibrary.MED_PYRA13
MED_PENTA15 = _medlibrary.MED_PENTA15
MED_PENTA18 = _medlibrary.MED_PENTA18
MED_HEXA20 = _medlibrary.MED_HEXA20
MED_HEXA27 = _medlibrary.MED_HEXA27
MED_POLYGON = _medlibrary.MED_POLYGON
MED_POLYGON2 = _medlibrary.MED_POLYGON2
MED_POLYHEDRON = _medlibrary.MED_POLYHEDRON
MED_STRUCT_GEO_INTERNAL = _medlibrary.MED_STRUCT_GEO_INTERNAL
MED_STRUCT_GEO_SUP_INTERNAL = _medlibrary.MED_STRUCT_GEO_SUP_INTERNAL
MED_NONE = _medlibrary.MED_NONE
MED_NO_GEOTYPE = _medlibrary.MED_NO_GEOTYPE
MED_UNDEF_GEOTYPE = _medlibrary.MED_UNDEF_GEOTYPE
MED_UNDEF_GEOMETRY_TYPE = _medlibrary.MED_UNDEF_GEOMETRY_TYPE
MED_ALL_GEOTYPE = _medlibrary.MED_ALL_GEOTYPE
MED_GEO_ALL = _medlibrary.MED_GEO_ALL
MED_N_CELL_GEO = _medlibrary.MED_N_CELL_GEO
MED_N_CELL_FIXED_GEO = _medlibrary.MED_N_CELL_FIXED_GEO
MED_N_CELL_GEO_FIXED_CON = _medlibrary.MED_N_CELL_GEO_FIXED_CON
MED_N_FACE_GEO = _medlibrary.MED_N_FACE_GEO
MED_N_FACE_FIXED_GEO = _medlibrary.MED_N_FACE_FIXED_GEO
MED_N_FACE_GEO_FIXED_CON = _medlibrary.MED_N_FACE_GEO_FIXED_CON
MED_N_EDGE_TYPES = _medlibrary.MED_N_EDGE_TYPES
MED_N_EDGE_FIXED_GEO = _medlibrary.MED_N_EDGE_FIXED_GEO
MED_N_EDGE_GEO_FIXED_CON = _medlibrary.MED_N_EDGE_GEO_FIXED_CON
MED_N_NODE_GEO = _medlibrary.MED_N_NODE_GEO
MED_N_NODE_FIXED_GEO = _medlibrary.MED_N_NODE_FIXED_GEO
MED_N_NODE_GEO_FIXED_CON = _medlibrary.MED_N_NODE_GEO_FIXED_CON
MED_NODAL = _medlibrary.MED_NODAL
MED_DESCENDING = _medlibrary.MED_DESCENDING
MED_UNDEF_CONNECTIVITY_MODE = _medlibrary.MED_UNDEF_CONNECTIVITY_MODE
MED_NO_CMODE = _medlibrary.MED_NO_CMODE
MED_CARTESIAN = _medlibrary.MED_CARTESIAN
MED_CYLINDRICAL = _medlibrary.MED_CYLINDRICAL
MED_SPHERICAL = _medlibrary.MED_SPHERICAL
MED_UNDEF_AXIS_TYPE = _medlibrary.MED_UNDEF_AXIS_TYPE
MED_FALSE = _medlibrary.MED_FALSE
MED_TRUE = _medlibrary.MED_TRUE
MED_GAUSS_ELNO = _medlibrary.MED_GAUSS_ELNO
MED_IPOINT_ELNO = _medlibrary.MED_IPOINT_ELNO
MED_NO_NAME = _medlibrary.MED_NO_NAME
MED_NO_MESHNAME = _medlibrary.MED_NO_MESHNAME
MED_NO_MESH = _medlibrary.MED_NO_MESH
MED_NO_MESH_SUPPORT = _medlibrary.MED_NO_MESH_SUPPORT
MED_NO_LOCALIZATION = _medlibrary.MED_NO_LOCALIZATION
MED_NO_INTERPOLATION = _medlibrary.MED_NO_INTERPOLATION
MED_NO_IPOINT_INTERNAL = _medlibrary.MED_NO_IPOINT_INTERNAL
MED_NO_PROFILE = _medlibrary.MED_NO_PROFILE
MED_NO_GROUP = _medlibrary.MED_NO_GROUP
MED_ALLENTITIES_PROFILE = _medlibrary.MED_ALLENTITIES_PROFILE
MED_NO_PROFILE_INTERNAL = _medlibrary.MED_NO_PROFILE_INTERNAL
MED_SAME_PROFILE_INTERNAL = _medlibrary.MED_SAME_PROFILE_INTERNAL
MED_ALL_CONSTITUENT = _medlibrary.MED_ALL_CONSTITUENT
MED_UNDEF_SIZE = _medlibrary.MED_UNDEF_SIZE
MED_NO_PROFILE_SIZE = _medlibrary.MED_NO_PROFILE_SIZE
MED_SORT_DTIT = _medlibrary.MED_SORT_DTIT
MED_SORT_ITDT = _medlibrary.MED_SORT_ITDT
MED_SORT_UNDEF = _medlibrary.MED_SORT_UNDEF
MED_NO_DT = _medlibrary.MED_NO_DT
MED_NO_IT = _medlibrary.MED_NO_IT
MED_UNDEF_DT = _medlibrary.MED_UNDEF_DT
MED_ATT_NOT_FILLED = _medlibrary.MED_ATT_NOT_FILLED
MED_MAX_FILTER_SPACES = _medlibrary.MED_MAX_FILTER_SPACES
class med_filter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_filter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_filter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nspaces"] = _medlibrary.med_filter_nspaces_set
    __swig_getmethods__["nspaces"] = _medlibrary.med_filter_nspaces_get
    if _newclass:
        nspaces = _swig_property(_medlibrary.med_filter_nspaces_get, _medlibrary.med_filter_nspaces_set)
    __swig_setmethods__["memspace"] = _medlibrary.med_filter_memspace_set
    __swig_getmethods__["memspace"] = _medlibrary.med_filter_memspace_get
    if _newclass:
        memspace = _swig_property(_medlibrary.med_filter_memspace_get, _medlibrary.med_filter_memspace_set)
    __swig_setmethods__["diskspace"] = _medlibrary.med_filter_diskspace_set
    __swig_getmethods__["diskspace"] = _medlibrary.med_filter_diskspace_get
    if _newclass:
        diskspace = _swig_property(_medlibrary.med_filter_diskspace_get, _medlibrary.med_filter_diskspace_set)
    __swig_setmethods__["nentity"] = _medlibrary.med_filter_nentity_set
    __swig_getmethods__["nentity"] = _medlibrary.med_filter_nentity_get
    if _newclass:
        nentity = _swig_property(_medlibrary.med_filter_nentity_get, _medlibrary.med_filter_nentity_set)
    __swig_setmethods__["nvaluesperentity"] = _medlibrary.med_filter_nvaluesperentity_set
    __swig_getmethods__["nvaluesperentity"] = _medlibrary.med_filter_nvaluesperentity_get
    if _newclass:
        nvaluesperentity = _swig_property(_medlibrary.med_filter_nvaluesperentity_get, _medlibrary.med_filter_nvaluesperentity_set)
    __swig_setmethods__["nconstituentpervalue"] = _medlibrary.med_filter_nconstituentpervalue_set
    __swig_getmethods__["nconstituentpervalue"] = _medlibrary.med_filter_nconstituentpervalue_get
    if _newclass:
        nconstituentpervalue = _swig_property(_medlibrary.med_filter_nconstituentpervalue_get, _medlibrary.med_filter_nconstituentpervalue_set)
    __swig_setmethods__["constituentselect"] = _medlibrary.med_filter_constituentselect_set
    __swig_getmethods__["constituentselect"] = _medlibrary.med_filter_constituentselect_get
    if _newclass:
        constituentselect = _swig_property(_medlibrary.med_filter_constituentselect_get, _medlibrary.med_filter_constituentselect_set)
    __swig_setmethods__["switchmode"] = _medlibrary.med_filter_switchmode_set
    __swig_getmethods__["switchmode"] = _medlibrary.med_filter_switchmode_get
    if _newclass:
        switchmode = _swig_property(_medlibrary.med_filter_switchmode_get, _medlibrary.med_filter_switchmode_set)
    __swig_setmethods__["filterarraysize"] = _medlibrary.med_filter_filterarraysize_set
    __swig_getmethods__["filterarraysize"] = _medlibrary.med_filter_filterarraysize_get
    if _newclass:
        filterarraysize = _swig_property(_medlibrary.med_filter_filterarraysize_get, _medlibrary.med_filter_filterarraysize_set)
    __swig_setmethods__["filterarray23v30"] = _medlibrary.med_filter_filterarray23v30_set
    __swig_getmethods__["filterarray23v30"] = _medlibrary.med_filter_filterarray23v30_get
    if _newclass:
        filterarray23v30 = _swig_property(_medlibrary.med_filter_filterarray23v30_get, _medlibrary.med_filter_filterarray23v30_set)
    __swig_setmethods__["profilearraysize"] = _medlibrary.med_filter_profilearraysize_set
    __swig_getmethods__["profilearraysize"] = _medlibrary.med_filter_profilearraysize_get
    if _newclass:
        profilearraysize = _swig_property(_medlibrary.med_filter_profilearraysize_get, _medlibrary.med_filter_profilearraysize_set)
    __swig_setmethods__["storagemode"] = _medlibrary.med_filter_storagemode_set
    __swig_getmethods__["storagemode"] = _medlibrary.med_filter_storagemode_get
    if _newclass:
        storagemode = _swig_property(_medlibrary.med_filter_storagemode_get, _medlibrary.med_filter_storagemode_set)
    __swig_setmethods__["profilename"] = _medlibrary.med_filter_profilename_set
    __swig_getmethods__["profilename"] = _medlibrary.med_filter_profilename_get
    if _newclass:
        profilename = _swig_property(_medlibrary.med_filter_profilename_get, _medlibrary.med_filter_profilename_set)

    def __init__(self):
        """__init__(self) -> med_filter"""
        this = _medlibrary.new_med_filter()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _medlibrary.delete_med_filter
    __del__ = lambda self: None
med_filter_swigregister = _medlibrary.med_filter_swigregister
med_filter_swigregister(med_filter)

MED_NO_FILTER_SIZE = _medlibrary.MED_NO_FILTER_SIZE
MED_NO_PROFILE_F = _medlibrary.MED_NO_PROFILE_F
class med_file_version(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_file_version, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_file_version, name)
    __repr__ = _swig_repr
    __swig_setmethods__["majeur"] = _medlibrary.med_file_version_majeur_set
    __swig_getmethods__["majeur"] = _medlibrary.med_file_version_majeur_get
    if _newclass:
        majeur = _swig_property(_medlibrary.med_file_version_majeur_get, _medlibrary.med_file_version_majeur_set)
    __swig_setmethods__["mineur"] = _medlibrary.med_file_version_mineur_set
    __swig_getmethods__["mineur"] = _medlibrary.med_file_version_mineur_get
    if _newclass:
        mineur = _swig_property(_medlibrary.med_file_version_mineur_get, _medlibrary.med_file_version_mineur_set)
    __swig_setmethods__["release"] = _medlibrary.med_file_version_release_set
    __swig_getmethods__["release"] = _medlibrary.med_file_version_release_get
    if _newclass:
        release = _swig_property(_medlibrary.med_file_version_release_get, _medlibrary.med_file_version_release_set)

    def __init__(self):
        """__init__(self) -> med_file_version"""
        this = _medlibrary.new_med_file_version()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _medlibrary.delete_med_file_version
    __del__ = lambda self: None
med_file_version_swigregister = _medlibrary.med_file_version_swigregister
med_file_version_swigregister(med_file_version)

class med_memfile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_memfile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_memfile, name)
    __repr__ = _swig_repr
    __swig_setmethods__["app_image_ptr"] = _medlibrary.med_memfile_app_image_ptr_set
    __swig_getmethods__["app_image_ptr"] = _medlibrary.med_memfile_app_image_ptr_get
    if _newclass:
        app_image_ptr = _swig_property(_medlibrary.med_memfile_app_image_ptr_get, _medlibrary.med_memfile_app_image_ptr_set)
    __swig_setmethods__["app_image_size"] = _medlibrary.med_memfile_app_image_size_set
    __swig_getmethods__["app_image_size"] = _medlibrary.med_memfile_app_image_size_get
    if _newclass:
        app_image_size = _swig_property(_medlibrary.med_memfile_app_image_size_get, _medlibrary.med_memfile_app_image_size_set)
    __swig_setmethods__["ref_count"] = _medlibrary.med_memfile_ref_count_set
    __swig_getmethods__["ref_count"] = _medlibrary.med_memfile_ref_count_get
    if _newclass:
        ref_count = _swig_property(_medlibrary.med_memfile_ref_count_get, _medlibrary.med_memfile_ref_count_set)
    __swig_setmethods__["fapl_image_ptr"] = _medlibrary.med_memfile_fapl_image_ptr_set
    __swig_getmethods__["fapl_image_ptr"] = _medlibrary.med_memfile_fapl_image_ptr_get
    if _newclass:
        fapl_image_ptr = _swig_property(_medlibrary.med_memfile_fapl_image_ptr_get, _medlibrary.med_memfile_fapl_image_ptr_set)
    __swig_setmethods__["fapl_image_size"] = _medlibrary.med_memfile_fapl_image_size_set
    __swig_getmethods__["fapl_image_size"] = _medlibrary.med_memfile_fapl_image_size_get
    if _newclass:
        fapl_image_size = _swig_property(_medlibrary.med_memfile_fapl_image_size_get, _medlibrary.med_memfile_fapl_image_size_set)
    __swig_setmethods__["fapl_ref_count"] = _medlibrary.med_memfile_fapl_ref_count_set
    __swig_getmethods__["fapl_ref_count"] = _medlibrary.med_memfile_fapl_ref_count_get
    if _newclass:
        fapl_ref_count = _swig_property(_medlibrary.med_memfile_fapl_ref_count_get, _medlibrary.med_memfile_fapl_ref_count_set)
    __swig_setmethods__["vfd_image_ptr"] = _medlibrary.med_memfile_vfd_image_ptr_set
    __swig_getmethods__["vfd_image_ptr"] = _medlibrary.med_memfile_vfd_image_ptr_get
    if _newclass:
        vfd_image_ptr = _swig_property(_medlibrary.med_memfile_vfd_image_ptr_get, _medlibrary.med_memfile_vfd_image_ptr_set)
    __swig_setmethods__["vfd_image_size"] = _medlibrary.med_memfile_vfd_image_size_set
    __swig_getmethods__["vfd_image_size"] = _medlibrary.med_memfile_vfd_image_size_get
    if _newclass:
        vfd_image_size = _swig_property(_medlibrary.med_memfile_vfd_image_size_get, _medlibrary.med_memfile_vfd_image_size_set)
    __swig_setmethods__["vfd_ref_count"] = _medlibrary.med_memfile_vfd_ref_count_set
    __swig_getmethods__["vfd_ref_count"] = _medlibrary.med_memfile_vfd_ref_count_get
    if _newclass:
        vfd_ref_count = _swig_property(_medlibrary.med_memfile_vfd_ref_count_get, _medlibrary.med_memfile_vfd_ref_count_set)
    __swig_setmethods__["flags"] = _medlibrary.med_memfile_flags_set
    __swig_getmethods__["flags"] = _medlibrary.med_memfile_flags_get
    if _newclass:
        flags = _swig_property(_medlibrary.med_memfile_flags_get, _medlibrary.med_memfile_flags_set)

    def __init__(self):
        """__init__(self) -> med_memfile"""
        this = _medlibrary.new_med_memfile()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _medlibrary.delete_med_memfile
    __del__ = lambda self: None
med_memfile_swigregister = _medlibrary.med_memfile_swigregister
med_memfile_swigregister(med_memfile)

MED_PARTICLE_NAME = _medlibrary.MED_PARTICLE_NAME
MED_BALL_NAME = _medlibrary.MED_BALL_NAME
MED_BEAM_NAME = _medlibrary.MED_BEAM_NAME
MED_PARTICLE_LABEL = _medlibrary.MED_PARTICLE_LABEL
MED_BALL_DIAMETER = _medlibrary.MED_BALL_DIAMETER
MED_BEAM_THICKNESS = _medlibrary.MED_BEAM_THICKNESS
import med.medenum
class MEDBOOL(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDBOOL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDBOOL, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDBOOL_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDBOOL___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDBOOL___bool__(self)

    def __len__(self):
        return _medlibrary.MEDBOOL___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDBOOL___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDBOOL___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDBOOL___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDBOOL___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDBOOL___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDBOOL___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDBOOL_pop(self)

    def append(self, x):
        return _medlibrary.MEDBOOL_append(self, x)

    def empty(self):
        return _medlibrary.MEDBOOL_empty(self)

    def size(self):
        return _medlibrary.MEDBOOL_size(self)

    def swap(self, v):
        return _medlibrary.MEDBOOL_swap(self, v)

    def begin(self):
        return _medlibrary.MEDBOOL_begin(self)

    def end(self):
        return _medlibrary.MEDBOOL_end(self)

    def rbegin(self):
        return _medlibrary.MEDBOOL_rbegin(self)

    def rend(self):
        return _medlibrary.MEDBOOL_rend(self)

    def clear(self):
        return _medlibrary.MEDBOOL_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDBOOL_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDBOOL_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDBOOL_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDBOOL(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDBOOL_push_back(self, x)

    def front(self):
        return _medlibrary.MEDBOOL_front(self)

    def back(self):
        return _medlibrary.MEDBOOL_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDBOOL_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDBOOL_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDBOOL_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDBOOL_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDBOOL_capacity(self)
    __swig_destroy__ = _medlibrary.delete_MEDBOOL
    __del__ = lambda self: None
MEDBOOL_swigregister = _medlibrary.MEDBOOL_swigregister
MEDBOOL_swigregister(MEDBOOL)
cvar = _medlibrary.cvar
MED_GET_ENTITY_TYPENAME = cvar.MED_GET_ENTITY_TYPENAME
MED_GET_CELL_GEOMETRY_TYPENAME = cvar.MED_GET_CELL_GEOMETRY_TYPENAME
MED_GET_FACE_GEOMETRY_TYPENAME = cvar.MED_GET_FACE_GEOMETRY_TYPENAME


MEDBOOL.__str__= lambda self: str([x for x in self])
MEDBOOL.__repr__= lambda self: "MEDBOOL("+str([x for x in self])+")"

class MEDFLOAT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDFLOAT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDFLOAT, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDFLOAT_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDFLOAT___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDFLOAT___bool__(self)

    def __len__(self):
        return _medlibrary.MEDFLOAT___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDFLOAT___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDFLOAT___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDFLOAT___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDFLOAT___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDFLOAT___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDFLOAT___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDFLOAT_pop(self)

    def append(self, x):
        return _medlibrary.MEDFLOAT_append(self, x)

    def empty(self):
        return _medlibrary.MEDFLOAT_empty(self)

    def size(self):
        return _medlibrary.MEDFLOAT_size(self)

    def swap(self, v):
        return _medlibrary.MEDFLOAT_swap(self, v)

    def begin(self):
        return _medlibrary.MEDFLOAT_begin(self)

    def end(self):
        return _medlibrary.MEDFLOAT_end(self)

    def rbegin(self):
        return _medlibrary.MEDFLOAT_rbegin(self)

    def rend(self):
        return _medlibrary.MEDFLOAT_rend(self)

    def clear(self):
        return _medlibrary.MEDFLOAT_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDFLOAT_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDFLOAT_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDFLOAT_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDFLOAT(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDFLOAT_push_back(self, x)

    def front(self):
        return _medlibrary.MEDFLOAT_front(self)

    def back(self):
        return _medlibrary.MEDFLOAT_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDFLOAT_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDFLOAT_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDFLOAT_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDFLOAT_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDFLOAT_capacity(self)

    def __iadd__(self, value):
        return _medlibrary.MEDFLOAT___iadd__(self, value)

    def __add__(self, value):
        return _medlibrary.MEDFLOAT___add__(self, value)

    def __isub__(self, value):
        return _medlibrary.MEDFLOAT___isub__(self, value)

    def __sub__(self, value):
        return _medlibrary.MEDFLOAT___sub__(self, value)

    def __imul__(self, value):
        return _medlibrary.MEDFLOAT___imul__(self, value)

    def __mul__(self, value):
        return _medlibrary.MEDFLOAT___mul__(self, value)

    def __itruediv__(self, *args):
        return _medlibrary.MEDFLOAT___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __truediv__(self, *args):
        return _medlibrary.MEDFLOAT___truediv__(self, *args)
    __div__ = __truediv__



    def __le__(self, value):
        return _medlibrary.MEDFLOAT___le__(self, value)

    def __lt__(self, value):
        return _medlibrary.MEDFLOAT___lt__(self, value)

    def __gt__(self, value):
        return _medlibrary.MEDFLOAT___gt__(self, value)

    def __ge__(self, value):
        return _medlibrary.MEDFLOAT___ge__(self, value)

    def __eq__(self, value):
        return _medlibrary.MEDFLOAT___eq__(self, value)

    def __ne__(self, value):
        return _medlibrary.MEDFLOAT___ne__(self, value)
    __swig_destroy__ = _medlibrary.delete_MEDFLOAT
    __del__ = lambda self: None
MEDFLOAT_swigregister = _medlibrary.MEDFLOAT_swigregister
MEDFLOAT_swigregister(MEDFLOAT)


MEDFLOAT.__str__= lambda self: str([x for x in self])
MEDFLOAT.__repr__= lambda self:"MEDFLOAT" +"("+str([x for x in self])+")"


MEDFLOAT64=MEDFLOAT
MEDDOUBLE=MEDFLOAT

class MEDFLOAT32(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDFLOAT32, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDFLOAT32, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDFLOAT32_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDFLOAT32___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDFLOAT32___bool__(self)

    def __len__(self):
        return _medlibrary.MEDFLOAT32___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDFLOAT32___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDFLOAT32___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDFLOAT32___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDFLOAT32___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDFLOAT32___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDFLOAT32___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDFLOAT32_pop(self)

    def append(self, x):
        return _medlibrary.MEDFLOAT32_append(self, x)

    def empty(self):
        return _medlibrary.MEDFLOAT32_empty(self)

    def size(self):
        return _medlibrary.MEDFLOAT32_size(self)

    def swap(self, v):
        return _medlibrary.MEDFLOAT32_swap(self, v)

    def begin(self):
        return _medlibrary.MEDFLOAT32_begin(self)

    def end(self):
        return _medlibrary.MEDFLOAT32_end(self)

    def rbegin(self):
        return _medlibrary.MEDFLOAT32_rbegin(self)

    def rend(self):
        return _medlibrary.MEDFLOAT32_rend(self)

    def clear(self):
        return _medlibrary.MEDFLOAT32_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDFLOAT32_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDFLOAT32_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDFLOAT32_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDFLOAT32(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDFLOAT32_push_back(self, x)

    def front(self):
        return _medlibrary.MEDFLOAT32_front(self)

    def back(self):
        return _medlibrary.MEDFLOAT32_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDFLOAT32_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDFLOAT32_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDFLOAT32_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDFLOAT32_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDFLOAT32_capacity(self)

    def __iadd__(self, value):
        return _medlibrary.MEDFLOAT32___iadd__(self, value)

    def __add__(self, value):
        return _medlibrary.MEDFLOAT32___add__(self, value)

    def __isub__(self, value):
        return _medlibrary.MEDFLOAT32___isub__(self, value)

    def __sub__(self, value):
        return _medlibrary.MEDFLOAT32___sub__(self, value)

    def __imul__(self, value):
        return _medlibrary.MEDFLOAT32___imul__(self, value)

    def __mul__(self, value):
        return _medlibrary.MEDFLOAT32___mul__(self, value)

    def __itruediv__(self, *args):
        return _medlibrary.MEDFLOAT32___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __truediv__(self, *args):
        return _medlibrary.MEDFLOAT32___truediv__(self, *args)
    __div__ = __truediv__



    def __le__(self, value):
        return _medlibrary.MEDFLOAT32___le__(self, value)

    def __lt__(self, value):
        return _medlibrary.MEDFLOAT32___lt__(self, value)

    def __gt__(self, value):
        return _medlibrary.MEDFLOAT32___gt__(self, value)

    def __ge__(self, value):
        return _medlibrary.MEDFLOAT32___ge__(self, value)

    def __eq__(self, value):
        return _medlibrary.MEDFLOAT32___eq__(self, value)

    def __ne__(self, value):
        return _medlibrary.MEDFLOAT32___ne__(self, value)
    __swig_destroy__ = _medlibrary.delete_MEDFLOAT32
    __del__ = lambda self: None
MEDFLOAT32_swigregister = _medlibrary.MEDFLOAT32_swigregister
MEDFLOAT32_swigregister(MEDFLOAT32)


MEDFLOAT32.__str__= lambda self: str([x for x in self])
MEDFLOAT32.__repr__= lambda self:"MEDFLOAT32" +"("+str([x for x in self])+")"

class MEDINT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDINT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDINT, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDINT_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDINT___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDINT___bool__(self)

    def __len__(self):
        return _medlibrary.MEDINT___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDINT___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDINT___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDINT___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDINT___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDINT___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDINT___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDINT_pop(self)

    def append(self, x):
        return _medlibrary.MEDINT_append(self, x)

    def empty(self):
        return _medlibrary.MEDINT_empty(self)

    def size(self):
        return _medlibrary.MEDINT_size(self)

    def swap(self, v):
        return _medlibrary.MEDINT_swap(self, v)

    def begin(self):
        return _medlibrary.MEDINT_begin(self)

    def end(self):
        return _medlibrary.MEDINT_end(self)

    def rbegin(self):
        return _medlibrary.MEDINT_rbegin(self)

    def rend(self):
        return _medlibrary.MEDINT_rend(self)

    def clear(self):
        return _medlibrary.MEDINT_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDINT_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDINT_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDINT_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDINT(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDINT_push_back(self, x)

    def front(self):
        return _medlibrary.MEDINT_front(self)

    def back(self):
        return _medlibrary.MEDINT_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDINT_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDINT_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDINT_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDINT_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDINT_capacity(self)

    def __iadd__(self, value):
        return _medlibrary.MEDINT___iadd__(self, value)

    def __add__(self, value):
        return _medlibrary.MEDINT___add__(self, value)

    def __isub__(self, value):
        return _medlibrary.MEDINT___isub__(self, value)

    def __sub__(self, value):
        return _medlibrary.MEDINT___sub__(self, value)

    def __imul__(self, value):
        return _medlibrary.MEDINT___imul__(self, value)

    def __mul__(self, value):
        return _medlibrary.MEDINT___mul__(self, value)

    def __itruediv__(self, *args):
        return _medlibrary.MEDINT___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __truediv__(self, *args):
        return _medlibrary.MEDINT___truediv__(self, *args)
    __div__ = __truediv__



    def __le__(self, value):
        return _medlibrary.MEDINT___le__(self, value)

    def __lt__(self, value):
        return _medlibrary.MEDINT___lt__(self, value)

    def __gt__(self, value):
        return _medlibrary.MEDINT___gt__(self, value)

    def __ge__(self, value):
        return _medlibrary.MEDINT___ge__(self, value)

    def __eq__(self, value):
        return _medlibrary.MEDINT___eq__(self, value)

    def __ne__(self, value):
        return _medlibrary.MEDINT___ne__(self, value)
    __swig_destroy__ = _medlibrary.delete_MEDINT
    __del__ = lambda self: None
MEDINT_swigregister = _medlibrary.MEDINT_swigregister
MEDINT_swigregister(MEDINT)


MEDINT.__str__= lambda self: str([x for x in self])
MEDINT.__repr__= lambda self:"MEDINT" +"("+str([x for x in self])+")"


MEDINT32=MEDINT

class MEDINT64(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDINT64, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDINT64, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDINT64_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDINT64___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDINT64___bool__(self)

    def __len__(self):
        return _medlibrary.MEDINT64___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDINT64___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDINT64___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDINT64___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDINT64___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDINT64___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDINT64___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDINT64_pop(self)

    def append(self, x):
        return _medlibrary.MEDINT64_append(self, x)

    def empty(self):
        return _medlibrary.MEDINT64_empty(self)

    def size(self):
        return _medlibrary.MEDINT64_size(self)

    def swap(self, v):
        return _medlibrary.MEDINT64_swap(self, v)

    def begin(self):
        return _medlibrary.MEDINT64_begin(self)

    def end(self):
        return _medlibrary.MEDINT64_end(self)

    def rbegin(self):
        return _medlibrary.MEDINT64_rbegin(self)

    def rend(self):
        return _medlibrary.MEDINT64_rend(self)

    def clear(self):
        return _medlibrary.MEDINT64_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDINT64_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDINT64_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDINT64_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDINT64(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDINT64_push_back(self, x)

    def front(self):
        return _medlibrary.MEDINT64_front(self)

    def back(self):
        return _medlibrary.MEDINT64_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDINT64_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDINT64_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDINT64_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDINT64_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDINT64_capacity(self)

    def __iadd__(self, value):
        return _medlibrary.MEDINT64___iadd__(self, value)

    def __add__(self, value):
        return _medlibrary.MEDINT64___add__(self, value)

    def __isub__(self, value):
        return _medlibrary.MEDINT64___isub__(self, value)

    def __sub__(self, value):
        return _medlibrary.MEDINT64___sub__(self, value)

    def __imul__(self, value):
        return _medlibrary.MEDINT64___imul__(self, value)

    def __mul__(self, value):
        return _medlibrary.MEDINT64___mul__(self, value)

    def __itruediv__(self, *args):
        return _medlibrary.MEDINT64___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __truediv__(self, *args):
        return _medlibrary.MEDINT64___truediv__(self, *args)
    __div__ = __truediv__



    def __le__(self, value):
        return _medlibrary.MEDINT64___le__(self, value)

    def __lt__(self, value):
        return _medlibrary.MEDINT64___lt__(self, value)

    def __gt__(self, value):
        return _medlibrary.MEDINT64___gt__(self, value)

    def __ge__(self, value):
        return _medlibrary.MEDINT64___ge__(self, value)

    def __eq__(self, value):
        return _medlibrary.MEDINT64___eq__(self, value)

    def __ne__(self, value):
        return _medlibrary.MEDINT64___ne__(self, value)
    __swig_destroy__ = _medlibrary.delete_MEDINT64
    __del__ = lambda self: None
MEDINT64_swigregister = _medlibrary.MEDINT64_swigregister
MEDINT64_swigregister(MEDINT64)


MEDINT64.__str__= lambda self: str([x for x in self])
MEDINT64.__repr__= lambda self:"MEDINT64" +"("+str([x for x in self])+")"

class MEDCHAR(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDCHAR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDCHAR, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _medlibrary.MEDCHAR_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _medlibrary.MEDCHAR___nonzero__(self)

    def __bool__(self):
        return _medlibrary.MEDCHAR___bool__(self)

    def __len__(self):
        return _medlibrary.MEDCHAR___len__(self)

    def __getslice__(self, i, j):
        return _medlibrary.MEDCHAR___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _medlibrary.MEDCHAR___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _medlibrary.MEDCHAR___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _medlibrary.MEDCHAR___delitem__(self, *args)

    def __getitem__(self, *args):
        return _medlibrary.MEDCHAR___getitem__(self, *args)

    def __setitem__(self, *args):
        return _medlibrary.MEDCHAR___setitem__(self, *args)

    def pop(self):
        return _medlibrary.MEDCHAR_pop(self)

    def append(self, x):
        return _medlibrary.MEDCHAR_append(self, x)

    def empty(self):
        return _medlibrary.MEDCHAR_empty(self)

    def size(self):
        return _medlibrary.MEDCHAR_size(self)

    def swap(self, v):
        return _medlibrary.MEDCHAR_swap(self, v)

    def begin(self):
        return _medlibrary.MEDCHAR_begin(self)

    def end(self):
        return _medlibrary.MEDCHAR_end(self)

    def rbegin(self):
        return _medlibrary.MEDCHAR_rbegin(self)

    def rend(self):
        return _medlibrary.MEDCHAR_rend(self)

    def clear(self):
        return _medlibrary.MEDCHAR_clear(self)

    def get_allocator(self):
        return _medlibrary.MEDCHAR_get_allocator(self)

    def pop_back(self):
        return _medlibrary.MEDCHAR_pop_back(self)

    def erase(self, *args):
        return _medlibrary.MEDCHAR_erase(self, *args)

    def __init__(self, *args):
        this = _medlibrary.new_MEDCHAR(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _medlibrary.MEDCHAR_push_back(self, x)

    def front(self):
        return _medlibrary.MEDCHAR_front(self)

    def back(self):
        return _medlibrary.MEDCHAR_back(self)

    def assign(self, n, x):
        return _medlibrary.MEDCHAR_assign(self, n, x)

    def resize(self, *args):
        return _medlibrary.MEDCHAR_resize(self, *args)

    def insert(self, *args):
        return _medlibrary.MEDCHAR_insert(self, *args)

    def reserve(self, n):
        return _medlibrary.MEDCHAR_reserve(self, n)

    def capacity(self):
        return _medlibrary.MEDCHAR_capacity(self)

    def __iadd__(self, value):
        return _medlibrary.MEDCHAR___iadd__(self, value)

    def __add__(self, value):
        return _medlibrary.MEDCHAR___add__(self, value)

    def __isub__(self, value):
        return _medlibrary.MEDCHAR___isub__(self, value)

    def __sub__(self, value):
        return _medlibrary.MEDCHAR___sub__(self, value)

    def __imul__(self, value):
        return _medlibrary.MEDCHAR___imul__(self, value)

    def __mul__(self, value):
        return _medlibrary.MEDCHAR___mul__(self, value)

    def __itruediv__(self, *args):
        return _medlibrary.MEDCHAR___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __truediv__(self, *args):
        return _medlibrary.MEDCHAR___truediv__(self, *args)
    __div__ = __truediv__



    def __le__(self, value):
        return _medlibrary.MEDCHAR___le__(self, value)

    def __lt__(self, value):
        return _medlibrary.MEDCHAR___lt__(self, value)

    def __gt__(self, value):
        return _medlibrary.MEDCHAR___gt__(self, value)

    def __ge__(self, value):
        return _medlibrary.MEDCHAR___ge__(self, value)

    def __eq__(self, value):
        return _medlibrary.MEDCHAR___eq__(self, value)

    def __ne__(self, value):
        return _medlibrary.MEDCHAR___ne__(self, value)
    __swig_destroy__ = _medlibrary.delete_MEDCHAR
    __del__ = lambda self: None
MEDCHAR_swigregister = _medlibrary.MEDCHAR_swigregister
MEDCHAR_swigregister(MEDCHAR)


MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"


MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"


MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"


def MEDlibraryNumVersion():
    """MEDlibraryNumVersion() -> med_err"""
    return _medlibrary.MEDlibraryNumVersion()

def MEDlibraryStrVersion():
    """MEDlibraryStrVersion() -> med_err"""
    return _medlibrary.MEDlibraryStrVersion()

def MEDlibraryHdfNumVersion():
    """MEDlibraryHdfNumVersion() -> med_err"""
    return _medlibrary.MEDlibraryHdfNumVersion()

def MEDlibraryHdfStrVersion():
    """MEDlibraryHdfStrVersion() -> med_err"""
    return _medlibrary.MEDlibraryHdfStrVersion()

def MEDlibraryClose():
    """MEDlibraryClose() -> med_err"""
    return _medlibrary.MEDlibraryClose()
# This file is compatible with both classic and new-style classes.


