/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Tab1_2Manager = BADDIALOGID;
LgIndex_t Extract2D_BTN_T1_2 = BADDIALOGID;
LgIndex_t LBL2_LBL_T1_2 = BADDIALOGID;
LgIndex_t X1_TF_T1_2 = BADDIALOGID;
LgIndex_t Y1_TF_T1_2 = BADDIALOGID;
LgIndex_t Z1_TF_T1_2 = BADDIALOGID;
LgIndex_t X2_TF_T1_2 = BADDIALOGID;
LgIndex_t Y2_TF_T1_2 = BADDIALOGID;
LgIndex_t Z2_TF_T1_2 = BADDIALOGID;
LgIndex_t LBL9_LBL_T1_2 = BADDIALOGID;
LgIndex_t LZ2_LBL_T1_2 = BADDIALOGID;
LgIndex_t LBLY2_LBL_T1_2 = BADDIALOGID;
LgIndex_t LBLX2_LBL_T1_2 = BADDIALOGID;
LgIndex_t LZ1_LBL_T1_2 = BADDIALOGID;
LgIndex_t LBLX1_LBL_T1_2 = BADDIALOGID;
LgIndex_t LBY1_LBL_T1_2 = BADDIALOGID;
LgIndex_t LBL16_LBL_T1_2 = BADDIALOGID;
LgIndex_t NBPT_TF_T1_2 = BADDIALOGID;
LgIndex_t ResIsTrans_TOG_T1_2 = BADDIALOGID;
LgIndex_t Tab2_2Manager = BADDIALOGID;
LgIndex_t Extract1D_BTN_T2_2 = BADDIALOGID;
LgIndex_t LBL2_LBL_T2_2 = BADDIALOGID;
LgIndex_t LBLX_LBL_T2_2 = BADDIALOGID;
LgIndex_t LBLY_LBL_T2_2 = BADDIALOGID;
LgIndex_t LZ_LBL_T2_2 = BADDIALOGID;
LgIndex_t X_TF_T2_2 = BADDIALOGID;
LgIndex_t Y_TF_T2_2 = BADDIALOGID;
LgIndex_t Z_TF_T2_2 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t TAB1_TB_D1 = BADDIALOGID;
