!                   ************************
                    SUBROUTINE DEALL_ARTEMIS
!                   ************************
!
!
!***********************************************************************
! ARTEMIS
!***********************************************************************
!
!brief    Memory deallocation of structures, aliases, blocks...
!
!history  Y. AUDOUIN (LNHE)
!+        24/04/1997
!+        V8P0
!+        Creation of the file
!
!history  N.DURAND (HRW)
!+        August 2018
!+        V7P3
!+   added a clause for the de-allocation of BDALE
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF
      USE DECLARATIONS_TELEMAC
      USE DECLARATIONS_ARTEMIS
!
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
!
!-----------------------------------------------------------------------
!
!
!=======================================================================
!
!     ALLOCATES THE MESH STRUCTURE
!
      CALL DEALMESH(MESH)
!
!
! BUILDS THE BLOCK THAT CONNECTS A VARIABLE NAME
! TO ITS ARRAY
!
      CALL BIEF_DEALLOBJ(VARSOR)
!
! BUILDS THE BLOCK THAT CONNECTS A VARIABLE NAME
! TO ITS ARRAY
!
      CALL BIEF_DEALLOBJ(VARNIM)
!
!
!-----------------------------------------------------------------------
!
!                     ******************
!                     *   REAL ARRAYS  *
!                     ******************
!
!-----------------------------------------------------------------------
!
!
! POTENTIAL
!
      CALL BIEF_DEALLOBJ(PHIR)
      CALL BIEF_DEALLOBJ(PHII)
!
! WATER DEPTH AT REST
!
      CALL BIEF_DEALLOBJ(H)
!
! WAVE NUMBER
      CALL BIEF_DEALLOBJ(K)
!
! PHASE AND GROUP VELOCITIES
      CALL BIEF_DEALLOBJ(C)
      CALL BIEF_DEALLOBJ(CG)
!
! WAVE HEIGHT AND PHASE
      CALL BIEF_DEALLOBJ(HHO)
      CALL BIEF_DEALLOBJ(PHAS)
!
! VELOCITIES
      CALL BIEF_DEALLOBJ(U0)
      CALL BIEF_DEALLOBJ(V0)
!
! AVERAGES OF THE SINES AND COSINES OF THE WAVE DIRECTION
      CALL BIEF_DEALLOBJ(MCOS)
      CALL BIEF_DEALLOBJ(MSIN)
! WAVE INCIDENCE
      CALL BIEF_DEALLOBJ(INCI)
!
! FREE SURFACE AND BOTTOM ELEVATION
      CALL BIEF_DEALLOBJ(S)
      CALL BIEF_DEALLOBJ(ZF)
!
! FRICTION COEFFICIENT (VARIABLE IN SPACE)
      CALL BIEF_DEALLOBJ(FW)
!
! WAVE HEIGHT (RANDOM SEAS)
! ARRAY STORING DISCRETISED PERIODS FOR MULTIDIRECTIONAL RANDOM
! WAVES
!
      IF(ALEMON .OR. ALEMUL) THEN
        CALL BIEF_DEALLOBJ(HALE)
        CALL BIEF_DEALLOBJ(PALE)
      ENDIF
!
! REFLEXION COEFFICIENTS, ANGLE OF WAVE ATTACK (FROM X AXIS)
! AND DEPHASING CAUSED BY THE WALLS
!
      CALL BIEF_DEALLOBJ(RP)
      CALL BIEF_DEALLOBJ(TETAP)
      CALL BIEF_DEALLOBJ(ALFAP)
!     STORAGE OF TETAP FOR AUTOMATIC REFLEXION ANGLE CALCULATION
      CALL BIEF_DEALLOBJ(TETAPM)
!     STORAGE OF TETAP AND ALFAP VALUES
!     FOR LECLIM (SECOND DIMENSION=2 FOR THE EQUIVALENT OF UBOR)
      CALL BIEF_DEALLOBJ(TETAPS)
      CALL BIEF_DEALLOBJ(ALFAPS)
!     STORAGE OF HB VALUES
      CALL BIEF_DEALLOBJ(HBS)

! WAVE HEIGHT AND ANGLE OF WAVE ATTACK FOR OPEN BOUNDARIES
! (ANGLE FROM X AXIS)
      CALL BIEF_DEALLOBJ(HB)
      CALL BIEF_DEALLOBJ(TETAB)
! INCIDENT POTENIAL ALONG THE BOUNDARY
! REAL AND IMAGINARY PART
      CALL BIEF_DEALLOBJ(PRB   )
      CALL BIEF_DEALLOBJ(PIB   )
! GRADIENT OF INCIDENT POTENIAL ALONG THE BOUNDARY
! REAL AND IMAGINARY PART, X AND Y PART
      CALL BIEF_DEALLOBJ(DDXPRB)
      CALL BIEF_DEALLOBJ(DDYPRB)
      CALL BIEF_DEALLOBJ(DDXPIB)
      CALL BIEF_DEALLOBJ(DDYPIB)

!
! ARRAY OF POTENTIAL, IMPOSED ALONG THE BOUNDARY (DIRICHLET)
      CALL BIEF_DEALLOBJ(PHIRB)
      CALL BIEF_DEALLOBJ(PHIIB)
! BLOCK OF THESE VALUES :
      CALL BIEF_DEALLOBJ(PHIB)
!
! COEFFICIENTS FOR BOUNDARY CONDITIONS
!
      CALL BIEF_DEALLOBJ(APHI1B)
      CALL BIEF_DEALLOBJ(BPHI1B)
      CALL BIEF_DEALLOBJ(CPHI1B)
      CALL BIEF_DEALLOBJ(DPHI1B)
      CALL BIEF_DEALLOBJ(CGRX1B)
      CALL BIEF_DEALLOBJ(CGRY1B)
      CALL BIEF_DEALLOBJ(DGRX1B)
      CALL BIEF_DEALLOBJ(DGRY1B)
      CALL BIEF_DEALLOBJ(APHI2B)
      CALL BIEF_DEALLOBJ(BPHI2B)
      CALL BIEF_DEALLOBJ(CPHI2B)
      CALL BIEF_DEALLOBJ(DPHI2B)
      CALL BIEF_DEALLOBJ(APHI3B)
      CALL BIEF_DEALLOBJ(BPHI3B)
      CALL BIEF_DEALLOBJ(CPHI3B)
      CALL BIEF_DEALLOBJ(DPHI3B)
      CALL BIEF_DEALLOBJ(APHI4B)
      CALL BIEF_DEALLOBJ(BPHI4B)
      CALL BIEF_DEALLOBJ(CPHI4B)
      CALL BIEF_DEALLOBJ(DPHI4B)
!
! BIDON TABLE FOR LECLIM (SECOND DIMENSION=2 FOR THE EQUIVALENT OF UBOR)
!
      CALL BIEF_DEALLOBJ(TB1)

! WORKING ARRAY (SIZE NELEM)  (PROBLEM)
      CALL BIEF_DEALLOBJ(W1)
!
! WORKING ARRAY (SIZE NPOIN)
!
      CALL BIEF_DEALLOBJ(TB)
!
!     ALIASES FOR THE FIRST 4 WORKING ARRAYS IN THE BLOCK TB
!
!
! WORKING ARRAY (SIZE NPTFR)
!
!     TBBD STORES TBD1,TBD2,...
!
      CALL BIEF_DEALLOBJ(TBBD)
!
! MATRICES
!
      CALL BIEF_DEALLOBJ(AM1)
      CALL BIEF_DEALLOBJ(AM2)
      CALL BIEF_DEALLOBJ(AM3)
      CALL BIEF_DEALLOBJ(BM1)
      CALL BIEF_DEALLOBJ(BM2)
! BOUNDARY MATRIX
      CALL BIEF_DEALLOBJ(MBOR)
!
! SECOND MEMBERS
!
      CALL BIEF_DEALLOBJ(CV1)
      CALL BIEF_DEALLOBJ(CV2)
!
! ARRAYS FOR THE DISSIPATION :
!
      CALL BIEF_DEALLOBJ(MU    )
      CALL BIEF_DEALLOBJ(MU2   )
      CALL BIEF_DEALLOBJ(QB    )
      CALL BIEF_DEALLOBJ(HMU   )
      CALL BIEF_DEALLOBJ(HMUANC)
      CALL BIEF_DEALLOBJ(UEB   )
!
!
! ARRAYS FOR THE WAVE-CURRENT INTERACTION :
!
! --> CURRENT VELOCITY : X and Y DIRECTIONS
      CALL BIEF_DEALLOBJ(UC)
      CALL BIEF_DEALLOBJ(VC)
! --> RELATIVE ANGULAR FREQUENCY
      CALL BIEF_DEALLOBJ(WR)
! --> STORAGE OF WAVE VECTOR COMPONENTS
      CALL BIEF_DEALLOBJ(KANCX)
      CALL BIEF_DEALLOBJ(KANCY)
!
!
! ARRAYS FOR RADIATION STRESSES
!
      CALL BIEF_DEALLOBJ(SXX   )
      CALL BIEF_DEALLOBJ(SXY   )
      CALL BIEF_DEALLOBJ(SYY   )
      CALL BIEF_DEALLOBJ(FX    )
      CALL BIEF_DEALLOBJ(FY    )
!
! ARRAYS FOR MEAN PERIODS AND PULSATIONS
!
      CALL BIEF_DEALLOBJ(T01   )
      CALL BIEF_DEALLOBJ(T02   )
      CALL BIEF_DEALLOBJ(TM    )
      CALL BIEF_DEALLOBJ(OMEGAM)
!
!
! MASKS FOR BOUNDARY NODES
!
      CALL BIEF_DEALLOBJ(MASK1)
      CALL BIEF_DEALLOBJ(MASK2)
      CALL BIEF_DEALLOBJ(MASK3)
      CALL BIEF_DEALLOBJ(MASK4)
      CALL BIEF_DEALLOBJ(MASK5)

!
!_V5P6 : CORRECTION FOR LINUX
      CALL BIEF_DEALLOBJ(MASKEL)
      CALL BIEF_DEALLOBJ(SBID  )
!_V5P6 : END OF CORRECTION FOR LINUX
!
! BLOCK OF MATRICES IN BERKHO
!
      CALL BIEF_DEALLOBJ(MAT)
!
!  BLOCK OF  UNKNOWNS IN BERKHO
!
      CALL BIEF_DEALLOBJ(UNK)
!
!  BLOCK OF SECOND MEMBERS IN BERKHO
!
      CALL BIEF_DEALLOBJ(RHS)
!
! ARRAY STORING DISCRETISED DIRECTIONS FOR MULTIDIRECTIONAL
! RANDOM WAVES
!
      IF(ALEMUL) THEN
        CALL BIEF_DEALLOBJ(DALE)
        IF (CHAINTWC.EQ.1) THEN
          CALL BIEF_DEALLOBJ(PDALE)
        ENDIF
!
        IF(CHAINTWC.GE.1.AND.ART_FILES(WACSPE)%NAME(1:1).NE.' ') THEN
          CALL BIEF_DEALLSPEC(S_TOM,NSPEC)
        ENDIF
!
        IF (CHAINTWC.EQ.2) THEN
          CALL BIEF_DEALLOBJ(BDALE)
        ENDIF
      ENDIF
!
! ARRAYS AT THE USER'S DISPOSAL
!
      CALL BIEF_DEALLOBJ(PRIVE)
!
!_______________________________________________________________________
!
!                         * INTEGER ARRAYS *
!_______________________________________________________________________
!
!
      CALL BIEF_DEALLOBJ(LIUBOR)
      CALL BIEF_DEALLOBJ(LIVBOR)
      CALL BIEF_DEALLOBJ(LIHBOR)
! BOUNDARY_COLOUR TABLE USED IN PARALLEL
      CALL BIEF_DEALLOBJ(BOUNDARY_COLOUR)
! BIDON TABLE FOR LECLIM
      CALL BIEF_DEALLOBJ(ITB1)
!

      CALL BIEF_DEALLOBJ(NUMLIQ)
!
      CALL BIEF_DEALLOBJ(IT1   )
      CALL BIEF_DEALLOBJ(IT2   )
      CALL BIEF_DEALLOBJ(IT3   )
!
      CALL BIEF_DEALLOBJ(LIDIR )
!
!***********************************************************************
!
! WRITES OUT :
!
      IF(LISTIN) THEN
        WRITE(LU,23)
      ENDIF
23    FORMAT(1X,///,21X,'*************************************',/,
     &21X,              '*    END OF MEMORY ORGANIZATION:    *',/,
     &21X,              '*************************************',/)
!
!-----------------------------------------------------------------------
!
      RETURN
      END
