/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModeless(ParentDialog,
                                             4726,
                                             840,
                                             "FileDelwaq",
                                             Dialog1Init_CB,
                                             Dialog1CloseButton_CB,
                                             Dialog1HelpButton_CB);
  LBL1_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             305,
                             101,
                    "Name of the associated Delwaq Data File");

  FileName_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                    241,
                                    310,
                                    3565,
                                    144,
                       FileName_TF_D1_CB);

  Browse_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                3998,
                                310,
                                382,
                                144,
                    "...",
                    Browse_BTN_D1_CB);

  OKButton_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                  241,
                                  551,
                                  1133,
                                  144,
                    "Load File",
                    OKButton_BTN_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
