deco_cbar = {
    'orientation': "vertical",
    'fraction': 0.15,
    'pad': 0.05,
    'shrink': 1.0,
    'aspect': 20.0,
    'anchor': (0.0, 0.5),
    'panchor': (1.0, 0.5),
    'extend': "neither",
    'extendfrac': None,
    'extendrect': False,
    'spacing': 'uniform',
    'ticks': None,
    'format': None,
    'drawedges': False,
    }
