!                   **************************
                    SUBROUTINE DEALL_TELEMAC3D
!                   **************************
!
!
!***********************************************************************
! TELEMAC3D   V7P2                                   02/08/2017
!***********************************************************************
!
!brief    Memory allocation of structures, aliases, blocks...
!
!history  J-M HERVOUET (LNHE)
!+        02/04/2009
!+
!+   T3D_FILES(T3DGEO)%LU REPLACES NGEO
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF
      USE DECLARATIONS_TELEMAC
      USE TPXO, ONLY : DEALLOC_TPXO
      USE TEL4DEL, ONLY : DEALLOC_TEL4DEL
      USE METEO_TELEMAC, ONLY : DEALLOC_METEO
      USE GOTM_COUPLING, ONLY : DEALLOC_GOTM
      USE OILSPILL
      USE DECLARATIONS_TELEMAC3D
      USE DECLARATIONS_TELEMAC2D, ONLY : DEJA_BT,FIRSTTIDE_BT,
     &     LASTTIDE_BT,SHIFTTIDE_BT,
     &     AHM2,PHM2,AHS2,PHS2,AHN2,PHN2,AHM4,PHM4,
     &     AUM2,PUM2,AUS2,PUS2,AUN2,PUN2,AUM4,PUM4,
     &     AVM2,PVM2,AVS2,PVS2,AVN2,PVN2,AVM4,PVM4,
     &     FHXM2,FHYM2,FHXS2,FHYS2,FHXN2,FHYN2,FHXM4,FHYM4,
     &     FUXM2,FUYM2,FUXS2,FUYS2,FUXN2,FUYN2,FUXM4,FUYM4,
     &     FVXM2,FVYM2,FVXS2,FVYS2,FVXN2,FVYN2,FVXM4,FVYM4,
     &     DEJA_BTM,FIRSTTIDE_BTM,LASTTIDE_BTM,SHIFTTIDE_BTM,
     &     INDW_BTM,INDW2_BTM,INDW3_BTM,NAMEWAVE_BTM,
     &     AH_BTM,PH_BTM,AU_BTM,PU_BTM,AV_BTM,PV_BTM,
     &     LON_BTM,LAT_BTM,UPV_BTM,FF_BTM,OMEGA_BTM,PHCALHW_BTM
      USE DECLARATIONS_GAIA, ONLY : NUM_ISUSP_ICLA,FLUDP,FLUDPT,FLUER
      USE DECLARATIONS_WAQTEL, ONLY : WAQPROCESS
#if defined HAVE_AED2
      USE T3D_AED2, ONLY : CLEAN_AED2_MODELS
#endif
!
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
      INTEGER :: I
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!

!
!-----------------------------------------------------------------------
!

      CALL BIEF_DEALLOBJ(VARSOR )
      CALL BIEF_DEALLOBJ(VARCL )
      CALL BIEF_DEALLOBJ(VARSO3)
      CALL BIEF_DEALLOBJ(BL_FC )
      CALL BIEF_DEALLOBJ(BL_FN )
      CALL BIEF_DEALLOBJ(BL_S0F)
      CALL BIEF_DEALLOBJ(BL_FSC)
      CALL BIEF_DEALLOBJ(BL_BOL)
      CALL BIEF_DEALLOBJ(BL_BORL)
      CALL BIEF_DEALLOBJ(FN3D  )
      CALL BIEF_DEALLOBJ(FC3D  )
      CALL BIEF_DEALLOBJ(PRIVE  )
      CALL BIEF_DEALLOBJ(PRIVE2D)
      CALL BIEF_DEALLOBJ(VISCNU)

!
!     Deallocate the mesh structure
      CALL DEALMESH(MESH2D)
      CALL DEALMESH(MESH3D)
      NULLIFY(IKLE2)
      NULLIFY(IKLE3)
      NULLIFY(X)
      NULLIFY(Y)
      NULLIFY(Z)
      NULLIFY(NELEM2)
      NULLIFY(NELEM3)
      NULLIFY(NELMAX2)
      NULLIFY(NELMAX3)
      NULLIFY(NPTFR2)
      NULLIFY(NPTFR3)
      NULLIFY(NPTFRX2)
      NULLIFY(NPTFRX3)
      NULLIFY(TYPELM2)
      NULLIFY(TYPELM3)
      NULLIFY(NPOIN2)
      NULLIFY(NPOIN3)
      NULLIFY(NPMAX2)
      NULLIFY(NPMAX3)
      NULLIFY(MXPTVS2)
      NULLIFY(MXPTVS3)
      NULLIFY(LV)


      CALL BIEF_DEALLOBJ(ZPROP )
      CALL BIEF_DEALLOBJ(ZT    )
      CALL BIEF_DEALLOBJ(ZN    )

      CALL BIEF_DEALLOBJ(GRADZF)
      CALL BIEF_DEALLOBJ(GRADZS)
      CALL BIEF_DEALLOBJ(GRADZN)
      CALL BIEF_DEALLOBJ(DSSUDT)

      CALL BIEF_DEALLOBJ(ZSTAR )
      CALL BIEF_DEALLOBJ(ZPLANE)
      CALL BIEF_DEALLOBJ(ZCHAR )
      CALL BIEF_DEALLOBJ(TRANSF_PLANE)

      CALL BIEF_DEALLOBJ(LIHBOR)
      CALL BIEF_DEALLOBJ(NUMLIQ)
      CALL BIEF_DEALLOBJ(NUMLIQ_ELM)
      CALL BIEF_DEALLOBJ(BOUNDARY_COLOUR)
      CALL BIEF_DEALLOBJ(LIMPRO)

      CALL BIEF_DEALLOBJ(NLIQBED)
      CALL BIEF_DEALLOBJ(BEDFLU)

      CALL BIEF_DEALLOBJ(MASK  )
      CALL BIEF_DEALLOBJ(MASK_3D)
      CALL BIEF_DEALLOBJ(MASKTR)
      CALL BIEF_DEALLOBJ(MASKEL)
      CALL BIEF_DEALLOBJ(MASKPT)
      CALL BIEF_DEALLOBJ(MASKBR)

      CALL BIEF_DEALLOBJ(UN)
      CALL BIEF_DEALLOBJ(VN)
      CALL BIEF_DEALLOBJ(UC)
      CALL BIEF_DEALLOBJ(VC)
      CALL BIEF_DEALLOBJ(UD)
      CALL BIEF_DEALLOBJ(VD)
      CALL BIEF_DEALLOBJ(U)
      CALL BIEF_DEALLOBJ(V)
      CALL BIEF_DEALLOBJ(S0U)
      CALL BIEF_DEALLOBJ(S0V)
      CALL BIEF_DEALLOBJ(S1U)
      CALL BIEF_DEALLOBJ(S1V)
      CALL BIEF_DEALLOBJ(SMU)
      CALL BIEF_DEALLOBJ(SMV)
      CALL BIEF_DEALLOBJ(UBORF   )
      CALL BIEF_DEALLOBJ(VBORF   )
      CALL BIEF_DEALLOBJ(UBORL   )
      CALL BIEF_DEALLOBJ(VBORL   )
      CALL BIEF_DEALLOBJ(UBORS   )
      CALL BIEF_DEALLOBJ(VBORS   )
      CALL BIEF_DEALLOBJ(AUBORF  )
      CALL BIEF_DEALLOBJ(AVBORF  )
      CALL BIEF_DEALLOBJ(AUBORL  )
      CALL BIEF_DEALLOBJ(UETCAL  )
      CALL BIEF_DEALLOBJ(AVBORL  )
      CALL BIEF_DEALLOBJ(AUBORS  )
      CALL BIEF_DEALLOBJ(AVBORS  )
      CALL BIEF_DEALLOBJ(BUBORF  )
      CALL BIEF_DEALLOBJ(BUBORL  )
      CALL BIEF_DEALLOBJ(BUBORS  )
      CALL BIEF_DEALLOBJ(BVBORF  )
      CALL BIEF_DEALLOBJ(BVBORL  )
      CALL BIEF_DEALLOBJ(BVBORS  )
      CALL BIEF_DEALLOBJ(UBORSAVE)
      CALL BIEF_DEALLOBJ(VBORSAVE)
      CALL BIEF_DEALLOBJ(WBORSAVE)

      CALL BIEF_DEALLOBJ(HBTIDE )
      CALL BIEF_DEALLOBJ(UBTIDE )
      CALL BIEF_DEALLOBJ(VBTIDE )
      CALL BIEF_DEALLOBJ(NUMTIDE)

      CALL BIEF_DEALLOBJ(UETCAR  )
      CALL BIEF_DEALLOBJ(IPBOT )

      CALL BIEF_DEALLOBJ(LIUBOF)
      CALL BIEF_DEALLOBJ(LIUBOL)
      CALL BIEF_DEALLOBJ(LIUBOS)
      CALL BIEF_DEALLOBJ(LIVBOF)
      CALL BIEF_DEALLOBJ(LIVBOL)
      CALL BIEF_DEALLOBJ(LIVBOS)

      IF(THOMFR) THEN
        CALL BIEF_DEALLOBJ(LIHBOR_USER)
        CALL BIEF_DEALLOBJ(LIUBOL_USER)
        CALL BIEF_DEALLOBJ(LIVBOL_USER)
      ENDIF

      CALL BIEF_DEALLOBJ(WN)
      CALL BIEF_DEALLOBJ(WC)
      CALL BIEF_DEALLOBJ(WD)
      CALL BIEF_DEALLOBJ(WCONV )
      CALL BIEF_DEALLOBJ(W)
      CALL BIEF_DEALLOBJ(S0W)
      CALL BIEF_DEALLOBJ(S1W)
      CALL BIEF_DEALLOBJ(WBORF   )
      CALL BIEF_DEALLOBJ(WBORL   )
      CALL BIEF_DEALLOBJ(WBORS   )
      CALL BIEF_DEALLOBJ(AWBORF  )
      CALL BIEF_DEALLOBJ(AWBORL  )
      CALL BIEF_DEALLOBJ(AWBORS  )
      CALL BIEF_DEALLOBJ(BWBORF  )
      CALL BIEF_DEALLOBJ(BWBORL  )
      CALL BIEF_DEALLOBJ(BWBORS  )
      CALL BIEF_DEALLOBJ(LIWBOF)
      CALL BIEF_DEALLOBJ(LIWBOL)
      CALL BIEF_DEALLOBJ(LIWBOS)
      CALL BIEF_DEALLOBJ(WS    )
      CALL BIEF_DEALLOBJ(WEL   )

      CALL BIEF_DEALLOBJ(DP    )
      CALL BIEF_DEALLOBJ(DPN   )
      CALL BIEF_DEALLOBJ(PH    )
      CALL BIEF_DEALLOBJ(PBORF )
      CALL BIEF_DEALLOBJ(PBORL )
      CALL BIEF_DEALLOBJ(PBORS )
      CALL BIEF_DEALLOBJ(LIPBOF)
      CALL BIEF_DEALLOBJ(LIPBOL)
      CALL BIEF_DEALLOBJ(LIPBOS)
!     block
      CALL BIEF_DEALLOBJ(TRN   )
      CALL BIEF_DEALLOBJ(TAC   )
      CALL BIEF_DEALLOBJ(TA    )
      CALL BIEF_DEALLOBJ(S0TA  )
      CALL BIEF_DEALLOBJ(S1TA  )
      CALL BIEF_DEALLOBJ(TABORF)
      CALL BIEF_DEALLOBJ(TABORL)
      CALL BIEF_DEALLOBJ(TABORS)
      CALL BIEF_DEALLOBJ(ATABOF)
      CALL BIEF_DEALLOBJ(ATABOL)
      CALL BIEF_DEALLOBJ(ATABOS)
      CALL BIEF_DEALLOBJ(BTABOF)
      CALL BIEF_DEALLOBJ(BTABOL)
      CALL BIEF_DEALLOBJ(BTABOS)
      CALL BIEF_DEALLOBJ(LITABF)
      CALL BIEF_DEALLOBJ(LITABL)
      CALL BIEF_DEALLOBJ(LITABS)
      CALL BIEF_DEALLOBJ(TRBORSAVE)
      CALL BIEF_DEALLOBJ(TA_SCE )

      CALL BIEF_DEALLOBJ(AKN   )
      CALL BIEF_DEALLOBJ(AKC   )
      CALL BIEF_DEALLOBJ(AK    )
      CALL BIEF_DEALLOBJ(S0AK  )
      CALL BIEF_DEALLOBJ(S1AK  )
      CALL BIEF_DEALLOBJ(EPN   )
      CALL BIEF_DEALLOBJ(EPC   )
      CALL BIEF_DEALLOBJ(EP    )
      CALL BIEF_DEALLOBJ(S0EP  )
      CALL BIEF_DEALLOBJ(S1EP  )
      CALL BIEF_DEALLOBJ(KBORF )
      CALL BIEF_DEALLOBJ(KBORL )
      CALL BIEF_DEALLOBJ(KBORSAVE)
      CALL BIEF_DEALLOBJ(KBORS )
      CALL BIEF_DEALLOBJ(EBORF )
      CALL BIEF_DEALLOBJ(EBORL )
      CALL BIEF_DEALLOBJ(EBORSAVE)
      CALL BIEF_DEALLOBJ(EBORS )
      CALL BIEF_DEALLOBJ(AKBORF)
      CALL BIEF_DEALLOBJ(AKBORL)
      CALL BIEF_DEALLOBJ(AKBORS)
      CALL BIEF_DEALLOBJ(AEBORF)
      CALL BIEF_DEALLOBJ(AEBORL)
      CALL BIEF_DEALLOBJ(AEBORS)
      CALL BIEF_DEALLOBJ(BKBORF)
      CALL BIEF_DEALLOBJ(BKBORL)
      CALL BIEF_DEALLOBJ(BKBORS)
      CALL BIEF_DEALLOBJ(BEBORF)
      CALL BIEF_DEALLOBJ(BEBORL)
      CALL BIEF_DEALLOBJ(BEBORS)
      CALL BIEF_DEALLOBJ(LIKBOF)
      CALL BIEF_DEALLOBJ(LIKBOL)
      CALL BIEF_DEALLOBJ(LIKBOS)
      CALL BIEF_DEALLOBJ(LIEBOF)
      CALL BIEF_DEALLOBJ(LIEBOL)
      CALL BIEF_DEALLOBJ(LIEBOS)
!     SPALART
      CALL BIEF_DEALLOBJ(NUN   )
      CALL BIEF_DEALLOBJ(NUC   )
      CALL BIEF_DEALLOBJ(NU    )
      CALL BIEF_DEALLOBJ(S0NU  )
      CALL BIEF_DEALLOBJ(S1NU  )
      CALL BIEF_DEALLOBJ(NUBORF)
      CALL BIEF_DEALLOBJ(NUBORL)
      CALL BIEF_DEALLOBJ(NUBORS)
      CALL BIEF_DEALLOBJ(NUBORSAVE)
      CALL BIEF_DEALLOBJ(ANUBORF)
      CALL BIEF_DEALLOBJ(ANUBORL)
      CALL BIEF_DEALLOBJ(ANUBORS)
      CALL BIEF_DEALLOBJ(BNUBORF)
      CALL BIEF_DEALLOBJ(BNUBORL)
      CALL BIEF_DEALLOBJ(BNUBORS)
      CALL BIEF_DEALLOBJ(LINUBOF)
      CALL BIEF_DEALLOBJ(LINUBOL)
      CALL BIEF_DEALLOBJ(LINUBOS)
      CALL BIEF_DEALLOBJ(WDIST)
      CALL BIEF_DEALLOBJ(STRAIN)
      CALL BIEF_DEALLOBJ(ROTAN)
!
      CALL BIEF_DEALLOBJ(U2D   )
      CALL BIEF_DEALLOBJ(UN2D   )
      CALL BIEF_DEALLOBJ(FU    )
      CALL BIEF_DEALLOBJ(V2D   )
      CALL BIEF_DEALLOBJ(VN2D   )
      CALL BIEF_DEALLOBJ(FV    )
      CALL BIEF_DEALLOBJ(UBOR2D)
      CALL BIEF_DEALLOBJ(VBOR2D)
      CALL BIEF_DEALLOBJ(FLBOR   )
      CALL BIEF_DEALLOBJ(FLBLIM  )
      CALL BIEF_DEALLOBJ(UCONV )
      CALL BIEF_DEALLOBJ(VCONV )
      CALL BIEF_DEALLOBJ(UCONVC)
      CALL BIEF_DEALLOBJ(VCONVC)
      CALL BIEF_DEALLOBJ(WSCONV)
      CALL BIEF_DEALLOBJ(DM1)

      CALL BIEF_DEALLOBJ(H)
      CALL BIEF_DEALLOBJ(HN)
      CALL BIEF_DEALLOBJ(HPROP )
      CALL BIEF_DEALLOBJ(NUWAVE)
      CALL BIEF_DEALLOBJ(HBOR)
      CALL BIEF_DEALLOBJ(DH)
      CALL BIEF_DEALLOBJ(SMH   )

      CALL BIEF_DEALLOBJ(PLUIE  )
      IF(NCSIZE.LE.1.AND.RAIN) THEN
        ALLOCATE(PARAPLUIE%R(1))
      ENDIF
      CALL BIEF_DEALLOBJ(PARAPLUIE)
      CALL BIEF_DEALLOBJ(MAXZ )
      CALL BIEF_DEALLOBJ(TMAXZ)

      CALL BIEF_DEALLOBJ(FXH   )
      CALL BIEF_DEALLOBJ(FYH   )

      CALL BIEF_DEALLOBJ(DIRMOY )
      CALL BIEF_DEALLOBJ(HM0    )
      CALL BIEF_DEALLOBJ(TPR5   )
      CALL BIEF_DEALLOBJ(ORBVEL )

      CALL BIEF_DEALLOBJ(VOLU   )
      CALL BIEF_DEALLOBJ(VOLUN  )
      CALL BIEF_DEALLOBJ(VOLU3D )
      IF(NCSIZE.GT.1) THEN
        CALL BIEF_DEALLOBJ(VOLUPAR)
        CALL BIEF_DEALLOBJ(VOLUNPAR)
        CALL BIEF_DEALLOBJ(VOLU3DPAR)
      ELSE
        NULLIFY(VOLUPAR%R)
        ALLOCATE(VOLUPAR%R(1))
        CALL BIEF_DEALLOBJ(VOLUPAR)
        NULLIFY(VOLUNPAR%R)
        ALLOCATE(VOLUNPAR%R(1))
        CALL BIEF_DEALLOBJ(VOLUNPAR)
        NULLIFY(VOLU3DPAR%R)
        ALLOCATE(VOLU3DPAR%R(1))
        CALL BIEF_DEALLOBJ(VOLU3DPAR)
      ENDIF
      CALL BIEF_DEALLOBJ(VOLUT  )
      CALL BIEF_DEALLOBJ(VOLU2D)
      CALL BIEF_DEALLOBJ(V2DPAR)
      CALL BIEF_DEALLOBJ(UNSV2D)
      CALL BIEF_DEALLOBJ(UNSV3D)
      CALL BIEF_DEALLOBJ(FLUINT )
      CALL BIEF_DEALLOBJ(FLUEXT )
      IF(NCSIZE.GT.1) THEN
        CALL BIEF_DEALLOBJ(FLUEXTPAR)
      ELSE
        NULLIFY(FLUEXTPAR%R)
        ALLOCATE(FLUEXTPAR%R(1))
        CALL BIEF_DEALLOBJ(FLUEXTPAR)
      ENDIF
      CALL BIEF_DEALLOBJ(FLINT2)

      CALL BIEF_DEALLOBJ(VISCVI)
      CALL BIEF_DEALLOBJ(VISCTA)
      CALL BIEF_DEALLOBJ(ROTAT   )
      CALL BIEF_DEALLOBJ(DELTAR  )
      CALL BIEF_DEALLOBJ(RHO)
      CALL BIEF_DEALLOBJ(RHOPOT)
      CALL BIEF_DEALLOBJ(RI      )
      CALL BIEF_DEALLOBJ(RUGOF )
      CALL BIEF_DEALLOBJ(RUGOL   )
      CALL BIEF_DEALLOBJ(CF    )
      CALL BIEF_DEALLOBJ(WINDSPD)
      CALL BIEF_DEALLOBJ(RHO4AED2)
      CALL BIEF_DEALLOBJ(TEMP4AED2)
      CALL BIEF_DEALLOBJ(SALI4AED2)
      CALL BIEF_DEALLOBJ(THICK4AED2)
      CALL BIEF_DEALLOBJ(BENTH4AED2)

      CALL DEALLOC_METEO()

      CALL BIEF_DEALLOBJ(MASINI )
      CALL BIEF_DEALLOBJ(MASSE  )
      CALL BIEF_DEALLOBJ(MASSEN )
      CALL BIEF_DEALLOBJ(FLUCUM )
      CALL BIEF_DEALLOBJ(FLUX   )
      CALL BIEF_DEALLOBJ(FLUXB  )
      CALL BIEF_DEALLOBJ(ZF    )
      CALL BIEF_DEALLOBJ(ZFE   )
      CALL BIEF_DEALLOBJ(DHHN  )

      CALL BIEF_DEALLOBJ(XFLOT )
      CALL BIEF_DEALLOBJ(YFLOT )
      CALL BIEF_DEALLOBJ(ZFLOT )
      CALL BIEF_DEALLOBJ(SHPFLO)
      CALL BIEF_DEALLOBJ(SHZFLO)
      CALL BIEF_DEALLOBJ(TAGFLO)
      CALL BIEF_DEALLOBJ(CLSFLO)
      CALL BIEF_DEALLOBJ(ELTFLO)
      CALL BIEF_DEALLOBJ(ETAFLO)

      CALL BIEF_DEALLOBJ(U_SCE  )
      CALL BIEF_DEALLOBJ(V_SCE  )
      CALL BIEF_DEALLOBJ(W_SCE  )
      CALL BIEF_DEALLOBJ(AK_SCE )
      CALL BIEF_DEALLOBJ(EP_SCE )
      CALL BIEF_DEALLOBJ(NU_SCE )
!     block
      CALL BIEF_DEALLOBJ(ITRAV3)

      CALL BIEF_DEALLOBJ(MSUPG)
      CALL BIEF_DEALLOBJ(MMURD)
      CALL BIEF_DEALLOBJ(MURD_TF)
      CALL BIEF_DEALLOBJ(MDIFF)
      CALL BIEF_DEALLOBJ(MTRA1)
      CALL BIEF_DEALLOBJ(MTRA2)
      CALL BIEF_DEALLOBJ(MAT2D )
      CALL BIEF_DEALLOBJ(MBOR2D)
      CALL BIEF_DEALLOBJ(MATR2H)

      CALL BIEF_DEALLOBJ(TRAV3 )
      CALL BIEF_DEALLOBJ(TB2   )
      CALL BIEF_DEALLOBJ(SEM3D )
      CALL BIEF_DEALLOBJ(SOURCES)
      CALL BIEF_DEALLOBJ(TRAV2 )
      CALL BIEF_DEALLOBJ(SEM2D )

      CALL BIEF_DEALLOBJ(TE1)
      CALL BIEF_DEALLOBJ(TE2)
      CALL BIEF_DEALLOBJ(TE3)
      CALL BIEF_DEALLOBJ(ZFLATS)
      CALL BIEF_DEALLOBJ(ZCONV  )
      CALL BIEF_DEALLOBJ(GRAZCO )
      CALL BIEF_DEALLOBJ(FLODEL )
      CALL BIEF_DEALLOBJ(FLOPAR )
      CALL BIEF_DEALLOBJ(FLULIM )
      CALL BIEF_DEALLOBJ(SVIDE  )
      CALL BIEF_DEALLOBJ(WCHU   )
      IF(S3D_SEDI) THEN
        CALL BIEF_DEALLOBJ(TRAV1  )
        DEALLOCATE(S3D_CONC)
        DEALLOCATE(S3D_EPAI)
        DEALLOCATE(S3D_TOCE)
        DO I=1,S3D_NCOUCH
          ALLOCATE(S3D_LAYTOCE%ADR(I)%P%R(1))
          ALLOCATE(S3D_LAYTHI%ADR(I)%P%R(1))
        ENDDO
        CALL BIEF_DEALLOBJ(S3D_LAYTOCE)
        CALL BIEF_DEALLOBJ(S3D_LAYTHI)
        CALL BIEF_DEALLOBJ(S3D_FLUDP)
        CALL BIEF_DEALLOBJ(S3D_FLUDPT)
        CALL BIEF_DEALLOBJ(S3D_ZF_S)
        CALL BIEF_DEALLOBJ(S3D_ESOMT)
      ENDIF
      CALL BIEF_DEALLOBJ(S3D_WCHU)
      CALL BIEF_DEALLOBJ(S3D_DMOY)
      CALL BIEF_DEALLOBJ(S3D_CREF)
      CALL BIEF_DEALLOBJ(ZREF)
      CALL BIEF_DEALLOBJ(S3D_HDEP)
      CALL BIEF_DEALLOBJ(S3D_FLUER)
      CALL BIEF_DEALLOBJ(S3D_PDEPO)
      CALL BIEF_DEALLOBJ(ZR)
      CALL BIEF_DEALLOBJ(NPF)

      CALL BIEF_DEALLOBJ(S3D_IVIDE)
      CALL BIEF_DEALLOBJ(S3D_TEMP)

      CALL BIEF_DEALLOBJ(S3D_EPAICO)
      CALL BIEF_DEALLOBJ(S3D_EPAINCO)
      CALL BIEF_DEALLOBJ(S3D_PVSCO)
      CALL BIEF_DEALLOBJ(S3D_PVSNCO)
      CALL BIEF_DEALLOBJ(S3D_FLUERC)
      CALL BIEF_DEALLOBJ(S3D_FLUERNC)
      CALL BIEF_DEALLOBJ(S3D_FLUDPTC)
      CALL BIEF_DEALLOBJ(S3D_FLUDPTNC)
      CALL BIEF_DEALLOBJ(S3D_FLUDPC)
      CALL BIEF_DEALLOBJ(S3D_FLUDPNC)
      CALL BIEF_DEALLOBJ(S3D_WCS)

      CALL BIEF_DEALLOBJ(ALTBUS)
      CALL BIEF_DEALLOBJ(CSBUS )
      CALL BIEF_DEALLOBJ(CEBUS )
      CALL BIEF_DEALLOBJ(ANGBUS)
      CALL BIEF_DEALLOBJ(LBUS  )
      CALL BIEF_DEALLOBJ(DBUS  )
      CALL BIEF_DEALLOBJ(LRGBUS)
      CALL BIEF_DEALLOBJ(HAUBUS)
      CALL BIEF_DEALLOBJ(SECBUS)
      CALL BIEF_DEALLOBJ(CLPBUS)
      CALL BIEF_DEALLOBJ(CV    )
      CALL BIEF_DEALLOBJ(C56   )
      CALL BIEF_DEALLOBJ(CV5   )
      CALL BIEF_DEALLOBJ(C5    )
      CALL BIEF_DEALLOBJ(CTRASH)
      CALL BIEF_DEALLOBJ(FRICBUS)
      CALL BIEF_DEALLOBJ(LONGBUS)
      CALL BIEF_DEALLOBJ(CIRC  )
      CALL BIEF_DEALLOBJ(DELBUS)
      CALL BIEF_DEALLOBJ(AABUS )
      CALL BIEF_DEALLOBJ(TBUS  )
!
      CALL BIEF_DEALLOBJ(WIP    )
      CALL BIEF_DEALLOBJ(WIPDX  )
      CALL BIEF_DEALLOBJ(WIPDY  )
      CALL BIEF_DEALLOBJ(USTOKES)
      CALL BIEF_DEALLOBJ(VSTOKES)
      CALL BIEF_DEALLOBJ(WSTOKES)
      CALL BIEF_DEALLOBJ(WST1   )
      CALL BIEF_DEALLOBJ(WST2   )
      CALL BIEF_DEALLOBJ(US2D   )
      CALL BIEF_DEALLOBJ(VS2D   )
      CALL BIEF_DEALLOBJ(DUS2D  )
      CALL BIEF_DEALLOBJ(DVS2D  )
      CALL BIEF_DEALLOBJ(DUS2DX )
      CALL BIEF_DEALLOBJ(DVS2DY )
      CALL BIEF_DEALLOBJ(USTX   )
      CALL BIEF_DEALLOBJ(VSTY   )
      CALL BIEF_DEALLOBJ(FDX    )
      CALL BIEF_DEALLOBJ(FDY    )
      CALL BIEF_DEALLOBJ(FBX    )
      CALL BIEF_DEALLOBJ(FBY    )
      CALL BIEF_DEALLOBJ(CFWC   )
      CALL BIEF_DEALLOBJ(FDK    )
      CALL BIEF_DEALLOBJ(FWX    )
      CALL BIEF_DEALLOBJ(FWY    )
      CALL BIEF_DEALLOBJ(HBORCLI)
      CALL BIEF_DEALLOBJ(UBORCLI)
      CALL BIEF_DEALLOBJ(VBORCLI)
!
!     Deallocate some global variables allocated
!     at some point in the code
!
        IF(ALLOCATED(CALCFLU)) DEALLOCATE(CALCFLU)
        IF(ALLOCATED(CALCRAIN)) DEALLOCATE(CALCRAIN)
!
      IF(ALLOCATED(PARTICULES)) THEN
        DO I=1,NFLOT_MAX
!!          DEALLOCATE(PARTICULES(I)%COMPO) !????
!!          DEALLOCATE(PARTICULES(I)%HAP)   !????
        ENDDO
        DEALLOCATE(PARTICULES)
      ENDIF
!
!     TEL4DEL
!
      CALL DEALLOC_TEL4DEL()
!
!     TPXO
!
      CALL DEALLOC_TPXO()
!
!     JMJ IN BORD_TIDE
!
      IF(DEJA_BT) THEN
        IF(ALLOCATED(FIRSTTIDE_BT)) DEALLOCATE(FIRSTTIDE_BT)
        IF(ALLOCATED(LASTTIDE_BT))  DEALLOCATE(LASTTIDE_BT)
        IF(ALLOCATED(SHIFTTIDE_BT)) DEALLOCATE(SHIFTTIDE_BT)
        IF(ALLOCATED(AHM2)) DEALLOCATE(AHM2)
        IF(ALLOCATED(PHM2)) DEALLOCATE(PHM2)
        IF(ALLOCATED(AHS2)) DEALLOCATE(AHS2)
        IF(ALLOCATED(PHS2)) DEALLOCATE(PHS2)
        IF(ALLOCATED(AHN2)) DEALLOCATE(AHN2)
        IF(ALLOCATED(PHN2)) DEALLOCATE(PHN2)
        IF(ALLOCATED(AHM4)) DEALLOCATE(AHM4)
        IF(ALLOCATED(PHM4)) DEALLOCATE(PHM4)
        IF(ALLOCATED(AUM2)) DEALLOCATE(AUM2)
        IF(ALLOCATED(PUM2)) DEALLOCATE(PUM2)
        IF(ALLOCATED(AUS2)) DEALLOCATE(AUS2)
        IF(ALLOCATED(PUS2)) DEALLOCATE(PUS2)
        IF(ALLOCATED(AUN2)) DEALLOCATE(AUN2)
        IF(ALLOCATED(PUN2)) DEALLOCATE(PUN2)
        IF(ALLOCATED(AUM4)) DEALLOCATE(AUM4)
        IF(ALLOCATED(PUM4)) DEALLOCATE(PUM4)
        IF(ALLOCATED(AVM2)) DEALLOCATE(AVM2)
        IF(ALLOCATED(PVM2)) DEALLOCATE(PVM2)
        IF(ALLOCATED(AVS2)) DEALLOCATE(AVS2)
        IF(ALLOCATED(PVS2)) DEALLOCATE(PVS2)
        IF(ALLOCATED(AVN2)) DEALLOCATE(AVN2)
        IF(ALLOCATED(PVN2)) DEALLOCATE(PVN2)
        IF(ALLOCATED(AVM4)) DEALLOCATE(AVM4)
        IF(ALLOCATED(PVM4)) DEALLOCATE(PVM4)
        IF(ALLOCATED(FHXM2)) DEALLOCATE(FHXM2)
        IF(ALLOCATED(FHYM2)) DEALLOCATE(FHYM2)
        IF(ALLOCATED(FHXS2)) DEALLOCATE(FHXS2)
        IF(ALLOCATED(FHYS2)) DEALLOCATE(FHYS2)
        IF(ALLOCATED(FHXN2)) DEALLOCATE(FHXN2)
        IF(ALLOCATED(FHYN2)) DEALLOCATE(FHYN2)
        IF(ALLOCATED(FHXM4)) DEALLOCATE(FHXM4)
        IF(ALLOCATED(FHYM4)) DEALLOCATE(FHYM4)
        IF(ALLOCATED(FUXM2)) DEALLOCATE(FUXM2)
        IF(ALLOCATED(FUYM2)) DEALLOCATE(FUYM2)
        IF(ALLOCATED(FUXS2)) DEALLOCATE(FUXS2)
        IF(ALLOCATED(FUYS2)) DEALLOCATE(FUYS2)
        IF(ALLOCATED(FUXN2)) DEALLOCATE(FUXN2)
        IF(ALLOCATED(FUYN2)) DEALLOCATE(FUYN2)
        IF(ALLOCATED(FUXM4)) DEALLOCATE(FUXM4)
        IF(ALLOCATED(FUYM4)) DEALLOCATE(FUYM4)
        IF(ALLOCATED(FVXM2)) DEALLOCATE(FVXM2)
        IF(ALLOCATED(FVYM2)) DEALLOCATE(FVYM2)
        IF(ALLOCATED(FVXS2)) DEALLOCATE(FVXS2)
        IF(ALLOCATED(FVYS2)) DEALLOCATE(FVYS2)
        IF(ALLOCATED(FVXN2)) DEALLOCATE(FVXN2)
        IF(ALLOCATED(FVYN2)) DEALLOCATE(FVYN2)
        IF(ALLOCATED(FVXM4)) DEALLOCATE(FVXM4)
        IF(ALLOCATED(FVYM4)) DEALLOCATE(FVYM4)
        DEJA_BT = .FALSE.
      ENDIF
!
!     MISC (E.G. FES, NEA, PREVIMER) IN BORD_TIDE_MISC
!
      IF(DEJA_BTM) THEN
        IF(ALLOCATED(FIRSTTIDE_BTM)) DEALLOCATE(FIRSTTIDE_BTM)
        IF(ALLOCATED(LASTTIDE_BTM))  DEALLOCATE(LASTTIDE_BTM)
        IF(ALLOCATED(SHIFTTIDE_BTM)) DEALLOCATE(SHIFTTIDE_BTM)
        IF(ALLOCATED(INDW_BTM)) DEALLOCATE(INDW_BTM)
        IF(ALLOCATED(INDW2_BTM)) DEALLOCATE(INDW2_BTM)
        IF(ALLOCATED(INDW3_BTM)) DEALLOCATE(INDW3_BTM)
        IF(ALLOCATED(NAMEWAVE_BTM)) DEALLOCATE(NAMEWAVE_BTM)
        IF(ALLOCATED(AH_BTM)) DEALLOCATE(AH_BTM)
        IF(ALLOCATED(PH_BTM)) DEALLOCATE(PH_BTM)
        IF(ALLOCATED(AU_BTM)) DEALLOCATE(AU_BTM)
        IF(ALLOCATED(PU_BTM)) DEALLOCATE(PU_BTM)
        IF(ALLOCATED(AV_BTM)) DEALLOCATE(AV_BTM)
        IF(ALLOCATED(PV_BTM)) DEALLOCATE(PV_BTM)
        IF(ALLOCATED(LON_BTM)) DEALLOCATE(LON_BTM)
        IF(ALLOCATED(LAT_BTM)) DEALLOCATE(LAT_BTM)
        IF(ALLOCATED(UPV_BTM)) DEALLOCATE(UPV_BTM)
        IF(ALLOCATED(FF_BTM))  DEALLOCATE(FF_BTM)
        IF(ALLOCATED(OMEGA_BTM)) DEALLOCATE(OMEGA_BTM)
        IF(ALLOCATED(PHCALHW_BTM)) DEALLOCATE(PHCALHW_BTM)
        DEJA_BTM = .FALSE.
      ENDIF
!
!     GOTM
!
      IF(ITURBV.EQ.6) THEN
        CALL DEALLOC_GOTM()
      ENDIF
!
!     Breach
!
!
!     Deallocating arrays allocated in lecdon_TELEMAC3D
!
      DEALLOCATE(FRTYPE)
      DEALLOCATE(DEBIMP)
      DEALLOCATE(COTIMP)
      DEALLOCATE(VITIMP)
      DEALLOCATE(FLUX_BOUNDARIES)
      DEALLOCATE(TRACER)
      DEALLOCATE(PTS_CURVES)
      DEALLOCATE(STA_DIS_CURVES)
      DEALLOCATE(PROFVEL)
      DEALLOCATE(VERPROVEL)
      DEALLOCATE(VERPROTRA)
      DEALLOCATE(DIRFLU)
      DEALLOCATE(OKQ3)
      DEALLOCATE(OKSL3)
      DEALLOCATE(OKTR3)
      DEALLOCATE(OKVIT3)
      DEALLOCATE(BND_TIDE)
      DEALLOCATE(ISCE)
      DEALLOCATE(KSCE)
      DEALLOCATE(XSCE)
      DEALLOCATE(YSCE)
      DEALLOCATE(ZSCE)
      DEALLOCATE(QSCE)
      DEALLOCATE(QSCE2)
      DEALLOCATE(TASCE)
      DEALLOCATE(USCE)
      DEALLOCATE(VSCE)
      DEALLOCATE(WSCE)
      DEALLOCATE(OKDEBSCE)
      DEALLOCATE(OKTRSCE)
      DEALLOCATE(SCHCTA)
      DEALLOCATE(TRAIN)
      DEALLOCATE(TRAC0)
      DEALLOCATE(T0AC)
      DEALLOCATE(BETAC)
      DEALLOCATE(DNUTAH)
      DEALLOCATE(DNUTAV)
      DEALLOCATE(S_ADV)
      DEALLOCATE(NOM_ADV)
      DEALLOCATE(SLVDTA)
      DEALLOCATE(NAMETRAC)
      DEALLOCATE(BEDFLO)
      DEALLOCATE(BEDQAREA)
      DEALLOCATE(OPTADV_TR)

      IF(DEJA_MURD3D_POS) THEN
        DEALLOCATE(INDIC_MURD3D_POS)
      ENDIF

      IF(ALLOCATED(QZ)) DEALLOCATE(QZ)
      ! Resetting initial values of variables
      DEJA_MURD3D_POS = .FALSE.
      DEJALU_TRISOU = .FALSE.

      ! Temporary
      IF(.NOT.INCLUS(COUPLING,'GAIA  ')) THEN
        CALL BIEF_DEALLOBJ(FLUDP)
        CALL BIEF_DEALLOBJ(FLUDPT)
        CALL BIEF_DEALLOBJ(FLUER)
        DEALLOCATE(NUM_ISUSP_ICLA)
      ENDIF

      IF( 13*INT(WAQPROCESS/13).EQ.WAQPROCESS ) THEN
        IF( INCLUS(COUPLING,'WAQTEL')) THEN
#if defined HAVE_AED2
          CALL CLEAN_AED2_MODELS()
#endif
        ENDIF
      ENDIF
      
      IF(INCLUS(COUPLING,'TOMAWAC2').OR.
     &    INCLUS(COUPLING,'TOMAWACT3D2')) THEN
        CALL BIEF_DEALLOBJ(TEL2TOM)
        CALL BIEF_DEALLOBJ(TOM2TEL)
      ENDIF      
!
!=======================================================================
!
! WRITES OUT TO LISTING :
!
      IF(LISTIN) THEN
        WRITE(LU,23)
      ENDIF
23    FORMAT(1X,///,21X,'*************************************',/,
     &21X,              '*    END OF MEMORY ORGANIZATION:    *',/,
     &21X,              '*************************************',/)
!
!-----------------------------------------------------------------------
!
      RETURN
!
!
      END SUBROUTINE DEALL_TELEMAC3D
