#/usr/bin/env python
# -*- coding: latin-1 -*-
TelemacdicoEn = {
'VARIABLES_FOR_GRAPHIC_PRINTOUTS' : {
    'U':"velocity along x axis (m/s)",
    'V':"velocity along y axis (m/s)",
    'C':"wave celerity (m/s)",
    'H':"water depth (m)",
    'S':"free surface elevation (m)",
    'B':"bottom elevation (m)",
    'F':"Froude number",
    'Q':"scalar flowrate of fluid (m2/s)",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"tracer* etc.",
    'T1':"tracer1 etc.",
    'T2':"tracer2 etc.",
    'T3':"tracer3 etc.",
    'T4':"tracer4 etc.",
    'T5':"tracer5 etc.",
    'T6':"tracer6 etc.",
    'T7':"tracer7 etc.",
    'T8':"tracer8 etc.",
    'T9':"tracer9 etc.",
    'T10':"tracer10 etc.",
    'T11':"tracer11 etc.",
    'T12':"tracer12 etc.",
    'T13':"tracer13 etc.",
    'T14':"tracer14 etc.",
    'T15':"tracer15 etc.",
    'T16':"tracer16 etc.",
    'T17':"tracer17 etc.",
    'T18':"tracer18 etc.",
    'T19':"tracer19 etc.",
    'T**':"tracer** etc.",
    'T*':"All the tracers 1 to 9.",
    'T1*':"All the tracers 10 to 19.",
    'K':"turbulent kinetic energy in k-epsilon model (J/kg)",
    'E':"dissipation of turbulent energy (W/kg)",
    'D':"turbulent viscosity (m2/s)",
    'I':"flowrate along x axis (m2/s)",
    'J':"flowrate along y axis (m2/s)",
    'M':"scalar velocity (m/s)",
    'X':"wind along x axis (m/s)",
    'Y':"wind along y axis (m/s)",
    'P':"air pressure (Pa)",
    'W':"friction coefficient",
    'A':"drift along x (m)",
    'G':"drift along y (m)",
    'L':"Courant number",
    'N':"supplementary variable N",
    'O':"supplementary variable O",
    'R':"supplementary variable R",
    'Z':"supplementary variable Z",
    'MAXZ':"maximum elevation (m)",
    'TMXZ':"time of maximum elevation (s)",
    'MAXV':"maximum velocity (m/s)",
    'TMXV':"time of maximum velocity (s)",
    'US':"friction velocity (m/s)",
    'G1':"gradient 1, etc.",
    'TAU_S':"TAU_S",
    '1/R':"1/R (1/m)",
    'OMEGA':"OMEGA",
    'WDIST':"distance to the closest wall (m)",
    'ZRL':"reference level for Nestor (m)",
  },
'VARIABLES_TO_BE_PRINTED' : {
    'U':"velocity along x axis (m/s)",
    'V':"velocity along y axis (m/s)",
    'C':"wave celerity (m/s)",
    'H':"water depth (m)",
    'S':"free surface elevation (m)",
    'B':"bottom elevation (m)",
    'F':"Froude number",
    'Q':"scalar flowrate of fluid (m2/s)",
    'Tn':"tracer 1, etc.",
    'K':"turbulent kinetic energy in k-epsilon model (J/kg)",
    'E':"dissipation of turbulent energy (W/kg)",
    'D':"turbulent viscosity (m2/s)",
    'I':"flowrate along x axis (m2/s)",
    'J':"flowrate along y axis (m2/s)",
    'M':"scalar velocity (m/s)",
    'X':"wind along x axis (m/s)",
    'Y':"wind along y axis (m/s)",
    'P':"air pressure (Pa)",
    'W':"friction coefficient",
    'A':"drift along x (m)",
    'G':"drift along y (m)",
    'L':"Courant number",
    'N':"supplementary variable N",
    'O':"supplementary variable O",
    'R':"supplementary variable R",
    'Z':"supplementary variable Z",
    'MAXZ':"maximum elevation (m)",
    'TMXZ':"time of maximum elevation (s)",
    'MAXV':"maximum velocity (m/s)",
    'TMXV':"time of maximum velocity (s)",
    'US':"friction velocity (m/s)",
    'G1':"gradient 1, etc.",
    'TAU_S':"TAU_S",
    '1/R':"1/R (1/m)",
    'OMEGA':"OMEGA",
    'WDIST':"distance to the closest wall (m)",
    'ZRL':"reference level for Nestor (m)",
  },
'STAGE_DISCHARGE_CURVES' : {
    0:"no",
    1:"Z(Q)",
    2:"Q(Z)",
  },
'VELOCITY_PROFILES' : {
    1:"constant normal profile",
    2:"u and v given in the conlim file",
    3:"normal velocity given in ubor in the conlim file",
    4:"velocity proportional to square root of depth",
    5:"velocity proportional to square root of depth, variant",
  },
'OPTION_FOR_LIQUID_BOUNDARIES' : {
    1:"classical",
    2:"Thompson method based on characteristics",
  },
'LAW_OF_BOTTOM_FRICTION' : {
    0:"NO FRICTION",
    1:"HAALAND",
    2:"CHEZY",
    3:"STRICKLER",
    4:"MANNING",
    5:"NIKURADSE",
  },
'DEPTH_IN_FRICTION_TERMS' : {
    1:"nodal",
    2:"average",
  },
'LAW_OF_FRICTION_ON_LATERAL_BOUNDARIES' : {
    0:"NO FRICTION",
    1:"HAALAND",
    2:"CHEZY",
    3:"STRICKLER",
    4:"MANNING",
    5:"NIKURADSE",
    6:"LOG LAW",
    7:"COLEBROOK-WHITE",
  },
'OPTION_FOR_WIND' : {
    1:"constant in time and space",
    2:"variable in time given by formated file",
    3:"variable in time and space given by formated file",
  },
'RAINFALL_RUNOFF_MODEL' : {
    0:"No infiltration",
    1:"CN runoff model",
    2:"Horton model",
    3:"Green Ampt model",
  },
'COST_FUNCTION' : {
    1:"Computed with h,u,v",
    2:"Computed with c,u,v",
  },
'IDENTIFICATION_METHOD' : {
    0:"list of tests",
    1:"gradient simple",
    2:"conjugate gradient",
    3:"Lagrange interpolation",
  },
'TYPE_OF_SOURCES' : {
    1:"Normal",
    2:"Dirac",
  },
'TREATMENT_OF_THE_LINEAR_SYSTEM' : {
    1:"Coupled",
    2:"Wave equation",
  },
'FINITE_VOLUME_SCHEME' : {
    0:"Roe scheme",
    1:"kinetic",
    3:"Zokagoa scheme",
    4:"Tchamen scheme",
    5:"HLLC scheme",
    6:"WAF scheme",
  },
'OPTION_FOR_TSUNAMI_GENERATION' : {
    0:"No Tsunami",
    1:"Tsunami generated on the basis of the Okada model 1992",
  },
'SPATIAL_PROJECTION_TYPE' : {
    1:"CARTESIAN, NOT GEOREFERENCED",
    2:"MERCATOR",
    3:"LATITUDE LONGITUDE",
  },
'SOLVER' : {
    1:"conjugate gradient",
    2:"conjugate residual",
    3:"conjugate gradient on a normal equation",
    4:"minimum error",
    6:"cgstab",
    7:"gmres",
    8:"direct",
  },
'PRECONDITIONING' : {
    2:"diagonal",
    0:"no preconditioning",
    3:"block-diagonal (4-9 matrices)",
    5:"absolute value of diagonal",
    7:"Crout",
    11:"Gauss-Seidel",
    13:"Supplied by the user",
    14:"diagonal and Crout",
  },
'FINITE_ELEMENT_ASSEMBLY' : {
    1:"Normal",
    2:"Integer I8",
    3:"Compensated",
  },
'DISCRETIZATIONS_IN_SPACE' : {
    11:"linear",
    12:"quasi-bubble",
    13:"quadratic",
  },
'INITIAL_GUESS_FOR_H' : {
    0:"zero",
    1:"previous",
    2:"extrapolation",
  },
'INITIAL_GUESS_FOR_U' : {
    0:"zero",
    1:"previous",
    2:"extrapolation",
  },
'TYPE_OF_ADVECTION' : {
    1:"CHARACTERISTICS",
    2:"SUPG",
    3:"CONSERVATIVE N-SCHEME LP",
    4:"CONSERVATIVE N-SCHEME",
    5:"CONSERVATIVE PSI-SCHEME",
    13:"EDGE-BASED N-SCHEME LP",
    14:"EDGE-BASED N-SCHEME",
    15:"ERIA SCHEME",
  },
'OPTION_FOR_CHARACTERISTICS' : {
    1:"strong",
    2:"weak",
  },
'SCHEME_FOR_ADVECTION_OF_VELOCITIES' : {
    0:"NO ADVECTION",
    1:"CHARACTERISTICS",
    2:"EXPLICIT + SUPG",
    3:"EXPLICIT LEO POSTMA",
    4:"EXPLICIT + MURD SCHEME N",
    5:"EXPLICIT + MURD SCHEME PSI",
    13:"N-SCHEME FOR TIDAL FLATS",
    14:"N-SCHEME FOR TIDAL FLATS",
    15:"ERIA SCHEME",
  },
'TREATMENT_OF_FLUXES_AT_THE_BOUNDARIES' : {
    1:"Priority to prescribed values",
    2:"Priority to fluxes",
  },
'OPTION_FOR_THE_DIFFUSION_OF_VELOCITIES' : {
    1:"div( nu grad(U) )",
    2:"1/h div ( h nu grad(U)",
  },
'FINITE_VOLUME_SCHEME_FOR_VELOCITY_DIFFUSION' : {
    1:"explicit P1 finite element",
    2:"two points flux",
    3:"reconstructed two points flux",
  },
'FINITE_VOLUME_SCHEME_FOR_TRACER_DIFFUSION' : {
    1:"explicit P1 finite element",
    2:"two points flux",
    3:"reconstructed two points flux",
  },
'OPTION_FOR_THE_RTPF_SCHEME_RECONSTRUCTIONS' : {
    1:"reconstructions with subcell gradients",
    2:"reconstructions with cell gradients",
  },
'OPTION_FOR_DIRICHLET_CONDITION_IN_FV_DIFFUSION' : {
    1:"weak imposition",
    2:"strong imposition",
  },
'MATRIX_STORAGE' : {
    1:"classical EBE",
    3:"Edge-based storage",
  },
'TURBULENCE_MODEL' : {
    1:"CONSTANT VISCOSITY",
    2:"ELDER",
    3:"K-EPSILON MODEL",
    4:"SMAGORINSKI",
    5:"MIXING LENGTH",
    6:"SPALART-ALLMARAS",
  },
'SOLVER_FOR_K_EPSILON_MODEL' : {
    1:"conjugate gradient",
    2:"conjugate residual",
    3:"conjugate gradient on normal equation",
    4:"minimum error",
    5:"squared conjugate gradient",
    6:"conjugate gradient squared stabilised (cgstab)",
    7:"gmres (see option for the solver for k-epsilon model)",
    8:"direct",
  },
'PRECONDITIONING_FOR_K_EPSILON_MODEL' : {
    2:"diagonal",
    0:"no preconditioning",
    7:"Crout",
    14:"diagonal and Crout",
  },
'TURBULENCE_REGIME_FOR_SOLID_BOUNDARIES' : {
    1:"smooth",
    2:"rough",
  },
'SCHEME_FOR_ADVECTION_OF_K_EPSILON' : {
    0:"NO ADVECTION",
    1:"CHARACTERISTICS",
    2:"EXPLICIT + SUPG",
    3:"EXPLICIT LEO POSTMA",
    4:"EXPLICIT + MURD SCHEME N",
    5:"EXPLICIT + MURD SCHEME PSI",
    13:"LEO POSTMA FOR TIDAL FLATS",
    14:"N-SCHEME FOR TIDAL FLATS",
    15:"ERIA SCHEME FOR TIDAL FLATS",
  },
'OPTION_FOR_THE_TREATMENT_OF_TIDAL_FLATS' : {
    1:"EQUATIONS SOLVED EVERYWHERE WITH CORRECTION ON TIDAL FLATS",
    2:"DRY ELEMENTS FROZEN",
    3:"LIKE 1 BUT WITH POROSITY (DEFINA METHOD)",
  },
'TREATMENT_OF_NEGATIVE_DEPTHS' : {
    0:"NO TREATMENT",
    1:"SMOOTHING",
    2:"FLUX CONTROL",
    3:"FLUX CONTROL (ERIA)",
  },
'SOLVER_FOR_DIFFUSION_OF_TRACERS' : {
    1:"conjugate gradient",
    2:"conjugate residual",
    3:"conjugate gradient on a normal equation",
    4:"minimum error",
    5:"squared conjugate gradient",
    6:"cgstab",
    7:"gmres (see solver option for tracers diffusion)",
    8:"direct",
  },
'PRECONDITIONING_FOR_DIFFUSION_OF_TRACERS' : {
    0:"no preconditioning",
    2:"diagonal",
    7:"Crout",
    14:"diagonal and Crout",
  },
'OPTION_FOR_THE_DIFFUSION_OF_TRACERS' : {
    1:"div( nu grad(T) )",
    2:"1/h div ( h nu grad(T)",
  },
'SCHEME_FOR_ADVECTION_OF_TRACERS' : {
    0:"NO ADVECTION",
    1:"CHARACTERISTICS",
    2:"EXPLICIT + SUPG",
    3:"EXPLICIT LEO POSTMA",
    4:"EXPLICIT + MURD SCHEME N",
    5:"EXPLICIT + MURD SCHEME PSI",
    13:"LEO POSTMA FOR TIDAL FLATS",
    14:"N-SCHEME FOR TIDAL FLATS",
    15:"ERIA SCHEME FOR TIDAL FLATS",
  },
'ALGAE_TYPE' : {
    1:"SPHERE",
    2:"IRIDAEA FLACCIDA (CLOSE TO ULVA)",
    3:"PELVETIOPSIS LIMITATA",
    4:"GIGARTINA LEPTORHYNCHOS",
  },
'ALGAE_RELEASE_TYPE' : {
    1:"TIMED",
    2:"DISLODGEMENT",
  },
'STOCHASTIC_DIFFUSION_MODEL' : {
    0:"No model",
    1:"brownian movement",
  },
'TYPE_OF_WEIRS' : {
    1:"HORIZONTAL WITH SAME NUMBER OF NODES UPSTREAM/DOWNSTREAM",
    2:"GENERAL",
  },
'GEOGRAPHIC_SYSTEM' : {
    -1:"NO DEFAULT VALUE",
    0:"DEFINED BY USER",
    1:"WGS84 LONGITUDE/LATITUDE IN REAL DEGREES",
    2:"WGS84 NORTHERN UTM",
    3:"WGS84 SOUTHERN UTM",
    4:"LAMBERT",
    5:"MERCATOR FOR TELEMAC",
  },
'OPTION_FOR_TIDAL_BOUNDARY_CONDITIONS' : {
    0:"No tide",
    1:"Real tide (recommended methodology)",
    2:"Astronomical tide",
    3:"Mean spring tide",
    4:"Mean tide",
    5:"Mean neap tide",
    6:"Astronomical neap tide",
    7:"Real tide (methodology before 2010)",
  },
'TIDAL_DATA_BASE' : {
    -1:"NO DEFAULT VALUE",
    1:"JMJ",
    2:"TPXO",
    3:"MISCELLANEOUS (LEGOS-NEA, FES20XX, PREVIMER...)",
  },
'LANGUAGE' : {
    1:"FRANCAIS",
    2:"ANGLAIS",
  },
}
TelemacdicoFr = {
'VARIABLES_FOR_GRAPHIC_PRINTOUTS' : {
    'U':"vitesse suivant l axe des x (m/s)",
    'V':"vitesse suivant l axe des y (m/s)",
    'C':"celerite des ondes (m/s)",
    'H':"hauteur d eau (m)",
    'S':"cote de surface libre (m)",
    'B':"cote du fond (m)",
    'F':"nombre de Froude",
    'Q':"debit scalaire du fluide (m2/s)",
    'Ti':"traceur i etc.",
    'T*':"Tous les traceurs de 1 a 9.",
    'T1*':"Tous les traceurs 10 a 19.",
    'K':"energie turbulente du modele k-epsilon (J/kg)",
    'E':"dissipation de l energie turbulente (W/kg)",
    'D':"viscosite turbulente (m2/s)",
    'I':"debit suivant l axe des x (m2/s)",
    'J':"debit suivant l axe des y (m2/s)",
    'M':"vitesse scalaire (m/s)",
    'X':"vent suivant l axe des x (m/s)",
    'Y':"vent suivant l axe des y (m/s)",
    'P':"pression atmospherique (Pa)",
    'W':"coefficient de frottement sur le fond",
    'A':"derive en x (m)",
    'G':"derive en y (m)",
    'L':"nombre de Courant",
    'N':"variable supplementaire N",
    'O':"variable supplementaire O",
    'R':"variable supplementaire R",
    'Z':"variable supplementaire Z",
    'MAXZ':"cote maximum (m)",
    'TMXZ':"temps de la cote maximum (s)",
    'MAXV':"vitesse maximum (m/s)",
    'TMXV':"temps de la vitesse maximum (s)",
    'US':"vitesse de frottement (m/s)",
    'G1':"gradient 1, etc.",
    'TAU_S':"TAU_S",
    '1/R':"1/R (1/m)",
    'OMEGA':"OMEGA",
    'WDIST':"distance au mur le plus proche (m)",
    'ZRL':"niveau de reference pour Nestor (m)",
  },
'VARIABLES_TO_BE_PRINTED' : {
    'U':"vitesse suivant l axe des x (m/s)",
    'V':"vitesse suivant l axe des y (m/s)",
    'C':"celerite des ondes (m/s)",
    'H':"hauteur d eau (m)",
    'S':"cote de surface libre (m)",
    'B':"cote du fond (m)",
    'F':"nombre de Froude",
    'Q':"debit scalaire du fluide (m2/s)",
    'Tn':"traceur 1, etc.",
    'K':"energie turbulente du modele k-epsilon (J/kg)",
    'E':"dissipation de l energie turbulente (W/kg)",
    'D':"viscosite turbulente (m2/s)",
    'I':"debit suivant l axe des x (m2/s)",
    'J':"debit suivant l axe des y (m2/s)",
    'M':"vitesse scalaire (m/s)",
    'X':"vent suivant l axe des x (m/s)",
    'Y':"vent suivant l axe des y (m/s)",
    'P':"pression atmospherique (Pa)",
    'W':"coefficient de frottement sur le fond",
    'A':"derive en x (m)",
    'G':"derive en y (m)",
    'L':"nombre de Courant",
    'N':"variable supplementaire N",
    'O':"variable supplementaire O",
    'R':"variable supplementaire R",
    'Z':"variable supplementaire Z",
    'MAXZ':"cote maximum (m)",
    'TMXZ':"temps de la cote maximum (s)",
    'MAXV':"vitesse maximum (m/s)",
    'TMXV':"temps de la vitesse maximum (s)",
    'US':"vitesse de frottement (m/s)",
    'G1':"gradient 1, etc.",
    'TAU_S':"TAU_S",
    '1/R':"1/R (1/m)",
    'OMEGA':"OMEGA",
    'WDIST':"distance au mur le plus proche (m)",
    'ZRL':"niveau de reference pour Nestor (m)",
  },
'STAGE_DISCHARGE_CURVES' : {
    0:"non",
    1:"Z(Q)",
    2:"Q(Z)",
  },
'VELOCITY_PROFILES' : {
    1:"Profil normal constant",
    2:"u et v dans le fichier conlim",
    3:"Vitesse normale donnee dans ubor dans le fichier conlim",
    4:"vitesse en racine carree de h",
    5:"vitesse en racine carree de h, variante",
  },
'OPTION_FOR_LIQUID_BOUNDARIES' : {
    1:"classique",
    2:"methode de Thompson avec calcul de caracteristiques",
  },
'LAW_OF_BOTTOM_FRICTION' : {
    0:"PAS DE FROTTEMENT",
    1:"HAALAND",
    2:"CHEZY",
    3:"STRICKLER",
    4:"MANNING",
    5:"NIKURADSE",
  },
'DEPTH_IN_FRICTION_TERMS' : {
    1:"nodale",
    2:"moyenne",
  },
'LAW_OF_FRICTION_ON_LATERAL_BOUNDARIES' : {
    0:"PAS DE FROTTEMENT",
    1:"HAALAND",
    2:"CHEZY",
    3:"STRICKLER",
    4:"MANNING",
    5:"NIKURADSE",
    6:"LOG LAW",
    7:"COLEBROOK-WHITE",
  },
'OPTION_FOR_WIND' : {
    1:"constant en temps et en espace",
    2:"variable en temps donne par fichier formate",
    3:"variable en temps et en espace donne par fichier formate",
  },
'RAINFALL_RUNOFF_MODEL' : {
    0:"Pas d infiltration",
    1:"Modele CN",
    2:"Modele Horton",
    3:"Modele de Green et Ampt",
  },
'COST_FUNCTION' : {
    1:"Calculee sur h,u,v",
    2:"Calculee avec c,u,v",
  },
'IDENTIFICATION_METHOD' : {
    0:"plan d experience",
    1:"gradient simple",
    2:"gradient conjugue",
    3:"interpolation de Lagrange",
  },
'TYPE_OF_SOURCES' : {
    1:"Normal",
    2:"Dirac",
  },
'TREATMENT_OF_THE_LINEAR_SYSTEM' : {
    1:"Traitement couple",
    2:"Equation d onde",
  },
'FINITE_VOLUME_SCHEME' : {
    0:"schema de Roe",
    1:"schema cinetique",
    3:"schema Zokagoa",
    4:"schema Tchamen",
    5:"schema HLLC",
    6:"schema WAF",
  },
'OPTION_FOR_TSUNAMI_GENERATION' : {
    0:"Pas de Tsunami",
    1:"Generation d un Tsunami sur la base du modele de Okada 1992",
  },
'SPATIAL_PROJECTION_TYPE' : {
    1:"CARTESIEN, NON GEOREFERENCE",
    2:"MERCATOR",
    3:"LATITUDE LONGITUDE",
  },
'SOLVER' : {
    1:"gradient conjugue",
    2:"residu conjugue",
    3:"equation normale",
    4:"erreur minimale",
    6:"cgstab",
    7:"gmres",
    8:"direct",
  },
'PRECONDITIONING' : {
    2:"diagonal",
    0:"aucun",
    3:"bloc-diagonal (4 ou 9 matrices)",
    5:"valeur absolue diagonale",
    7:"Crout",
    11:"Gauss-Seidel",
    13:"Fourni par l utilisateur",
    14:"diagonal et Crout",
  },
'FINITE_ELEMENT_ASSEMBLY' : {
    1:"Normal",
    2:"Entier I8",
    3:"Compense",
  },
'DISCRETIZATIONS_IN_SPACE' : {
    11:"lineaire",
    12:"quasi-bulle",
    13:"quadratique",
  },
'INITIAL_GUESS_FOR_H' : {
    0:"zero",
    1:"precedent",
    2:"extrapolation",
  },
'INITIAL_GUESS_FOR_U' : {
    0:"zero",
    1:"precedent",
    2:"extrapolation",
  },
'TYPE_OF_ADVECTION' : {
    1:"CARACTERISTIQUES",
    2:"SUPG",
    3:"SCHEMA N CONSERVATIF LP",
    4:"SCHEMA N CONSERVATIF",
    5:"SCHEMA PSI CONSERVATIF",
    13:"SCHEMA N PAR SEGMENTS LP",
    14:"SCHEMA N PAR SEGMENTS",
    15:"SCHEMA ERIA",
  },
'OPTION_FOR_CHARACTERISTICS' : {
    1:"fortes",
    2:"faibles",
  },
'SCHEME_FOR_ADVECTION_OF_VELOCITIES' : {
    0:"PAS DE CONVECTION",
    1:"CARACTERISTIQUES",
    2:"EXPLICITE + SUPG",
    3:"EXPLICITE LEO POSTMA",
    4:"EXPLICITE + MURD SCHEMA N",
    5:"EXPLICITE + MURD SCHEMA PSI",
    13:"SCHEMA N POUR BANCS DECOUVRANTS",
    14:"SCHEMA N POUR BANCS DECOUVRANTS",
    15:"SCHEMA ERIA",
  },
'TREATMENT_OF_FLUXES_AT_THE_BOUNDARIES' : {
    1:"Priorite aux valeurs imposees",
    2:"Priorite aux flux",
  },
'OPTION_FOR_THE_DIFFUSION_OF_VELOCITIES' : {
    1:"div( nu grad(U) )",
    2:"1/h div ( h nu grad(U)",
  },
'FINITE_VOLUME_SCHEME_FOR_VELOCITY_DIFFUSION' : {
    1:"elements finis P1 explicites",
    2:"flux a deux points",
    3:"flux a deux points reconstruit",
  },
'FINITE_VOLUME_SCHEME_FOR_TRACER_DIFFUSION' : {
    1:"elements finis P1 explicites",
    2:"flux a deux points",
    3:"flux a deux points reconstruit",
  },
'OPTION_FOR_THE_RTPF_SCHEME_RECONSTRUCTIONS' : {
    1:"reconstructions avec gradients de sous-cellule",
    2:"reconstructions avec gradients de cellule",
  },
'OPTION_FOR_DIRICHLET_CONDITION_IN_FV_DIFFUSION' : {
    1:"imposition faible",
    2:"imposition forte",
  },
'MATRIX_STORAGE' : {
    1:"EBE classique",
    3:"Stockage par segments",
  },
'TURBULENCE_MODEL' : {
    1:"VISCOSITE CONSTANTE",
    2:"ELDER",
    3:"MODELE K-EPSILON",
    4:"SMAGORINSKI",
    5:"LONGUEUR DE MELANGE",
    6:"SPALART-ALLMARAS",
  },
'SOLVER_FOR_K_EPSILON_MODEL' : {
    1:"gradient conjugue",
    2:"residu conjugue",
    3:"gradient conjugue sur equation normale",
    4:"erreur minimale",
    5:"gradient conjugue carre",
    6:"gradient conjugue carre stabilise (cgstab)",
    7:"gmres (voir aussi option du solveur pour le modele k-epsilon",
    8:"direct",
  },
'PRECONDITIONING_FOR_K_EPSILON_MODEL' : {
    2:"diagonal",
    0:"aucun",
    7:"Crout",
    14:"diagonal et Crout",
  },
'TURBULENCE_REGIME_FOR_SOLID_BOUNDARIES' : {
    1:"lisse",
    2:"rugueux",
  },
'SCHEME_FOR_ADVECTION_OF_K_EPSILON' : {
    0:"PAS DE CONVECTION",
    1:"CARACTERISTIQUES",
    2:"EXPLICITE + SUPG",
    3:"EXPLICITE LEO POSTMA",
    4:"EXPLICITE + MURD SCHEMA N",
    5:"EXPLICITE + MURD SCHEMA PSI",
    13:"LEO POSTMA POUR BANCS DECOUVRANTS",
    14:"SCHEMA N POUR BANCS DECOUVRANTS",
    15:"SCHEMA ERIA POUR BANCS DECOUVRANTS",
  },
'OPTION_FOR_THE_TREATMENT_OF_TIDAL_FLATS' : {
    1:"EQUATIONS RESOLUES PARTOUT, CORRECTION SUR LES BANCS DECOUVRANTS",
    2:"GEL DES ELEMENTS DECOUVRANTS",
    3:"COMME 1 MAIS AVEC POROSITE (METHODE DEFINA)",
  },
'TREATMENT_OF_NEGATIVE_DEPTHS' : {
    0:"PAS DE TRAITEMENT",
    1:"LISSAGE",
    2:"LIMITATION DES FLUX",
    3:"LIMITATION DES FLUX (ERIA)",
  },
'SOLVER_FOR_DIFFUSION_OF_TRACERS' : {
    1:"gradient conjugue",
    2:"residu conjugue",
    3:"gradient conjugue sur equation normale",
    4:"erreur minimale",
    5:"gradient conjugue carre",
    6:"cgstab",
    7:"gmres (cf aussi option du solveur pour la diffusion des traceurs)",
    8:"direct",
  },
'PRECONDITIONING_FOR_DIFFUSION_OF_TRACERS' : {
    0:"aucun",
    2:"diagonal",
    7:"Crout",
    14:"diagonal et Crout",
  },
'OPTION_FOR_THE_DIFFUSION_OF_TRACERS' : {
    1:"div( nu grad(T) )",
    2:"1/h div ( h nu grad(T)",
  },
'SCHEME_FOR_ADVECTION_OF_TRACERS' : {
    0:"PAS DE CONVECTION",
    1:"CARACTERISTIQUES",
    2:"EXPLICITE + SUPG",
    3:"EXPLICITE LEO POSTMA",
    4:"EXPLICITE + MURD SCHEMA N",
    5:"EXPLICITE + MURD SCHEMA PSI",
    13:"LEO POSTMA POUR BANCS DECOUVRANTS",
    14:"SCHEMA N POUR BANCS DECOUVRANTS",
    15:"SCHEMA ERIA POUR BANCS DECOUVRANTS",
  },
'ALGAE_TYPE' : {
    1:"SPHERE",
    2:"IRIDAEA FLACCIDA (PROCHE DES ULVES)",
    3:"PELVETIOPSIS LIMITATA",
    4:"GIGARTINA LEPTORHYNCHOS",
  },
'ALGAE_RELEASE_TYPE' : {
    1:"PERIODE",
    2:"DEPLACEMENT",
  },
'STOCHASTIC_DIFFUSION_MODEL' : {
    0:"Pas de modele",
    1:"mouvement brownien",
  },
'TYPE_OF_WEIRS' : {
    1:"HORIZONTAL AVEC MEME NOMBRE DE NOEUDS AMONT/AVAL",
    2:"GENERALE",
  },
'GEOGRAPHIC_SYSTEM' : {
    -1:"PAS DE VALEUR PAR DEFAUT",
    0:"DEFINI PAR L UTILISATEUR",
    1:"WGS84 LONGITUDE/LATITUDE EN DEGRES REELS",
    2:"WGS84 NORD UTM",
    3:"WGS84 SUD UTM",
    4:"LAMBERT",
    5:"MERCATOR POUR TELEMAC",
  },
'OPTION_FOR_TIDAL_BOUNDARY_CONDITIONS' : {
    0:"Pas de maree",
    1:"Maree reelle (methodologie recommandee)",
    2:"Maree de vive-eau exceptionnelle (coef. presque 120)",
    3:"Maree de vive-eau moyenne (coef. presque 95)",
    4:"Maree moyenne (coef. presque 70)",
    5:"Maree de morte-eau moyenne (coef. presque 45)",
    6:"Maree de morte-eau exceptionnelle (coef. presque 20)",
    7:"Maree reelle (methodologie d avant 2010)",
  },
'TIDAL_DATA_BASE' : {
    -1:"PAS DE VALEUR PAR DEFAUT",
    1:"JMJ",
    2:"TPXO",
    3:"DIVERS (LEGOS-NEA, FES20XX, PREVIMER...)",
  },
'LANGUAGE' : {
    1:"FRANCAIS",
    2:"ANGLAIS",
  },
}

DicoCasFrToCata = {
  "TITRE":"TITLE",
  "CONDITIONS INITIALES":"INITIAL_CONDITIONS",
  "COTE INITIALE":"INITIAL_ELEVATION",
  "HAUTEUR INITIALE":"INITIAL_DEPTH",
  "FORMAT DU FICHIER DE DONNEES BINAIRE 1":"BINARY_DATA_FILE_1_FORMAT",
  "FICHIER DE DONNEES BINAIRE 1":"BINARY_DATA_FILE_1",
  "FORMAT DU FICHIER DE DONNEES BINAIRE 2":"BINARY_DATA_FILE_2_FORMAT",
  "FICHIER DE DONNEES BINAIRE 2":"BINARY_DATA_FILE_2",
  "FICHIER DE DONNEES FORMATE 1":"FORMATTED_DATA_FILE_1",
  "FICHIER DE DONNEES FORMATE 2":"FORMATTED_DATA_FILE_2",
  "FORMAT DU FICHIER DE GEOMETRIE":"GEOMETRY_FILE_FORMAT",
  "FICHIER DE GEOMETRIE":"GEOMETRY_FILE",
  "FICHIER FORTRAN":"FORTRAN_FILE",
  "FICHIER DES FONDS":"BOTTOM_TOPOGRAPHY_FILE",
  "LISSAGES DU FOND":"BOTTOM_SMOOTHINGS",
  "LISSAGES DU FOND APRES MODIFICATIONS UTILISATEUR":"BOTTOM_SMOOTHINGS_AFTER_USER_MODIFICATIONS",
  "FICHIER DES CONDITIONS AUX LIMITES":"BOUNDARY_CONDITIONS_FILE",
  "VALIDATION":"VALIDATION",
  "FORMAT DU FICHIER DE REFERENCE":"REFERENCE_FILE_FORMAT",
  "FICHIER DE REFERENCE":"REFERENCE_FILE",
  "PROCESSEURS PARALLELES":"PARALLEL_PROCESSORS",
  "VERIFICATION DU MAILLAGE":"CHECKING_THE_MESH",
  "NOMBRE MAXIMUM DE FRONTIERES":"MAXIMUM_NUMBER_OF_BOUNDARIES",
  "NOMBRE MAXIMUM DE SOURCES":"MAXIMUM_NUMBER_OF_SOURCES",
  "NOMBRE MAXIMUM DE TRACEURS":"MAXIMUM_NUMBER_OF_TRACERS",
  "LONGUEUR DU VECTEUR":"VECTOR_LENGTH",
  "COEFFICIENT DE SECURITE POUR SCARACT":"SECURITY_COEFFICIENT_FOR_SCARACT",
  "SUITE DE CALCUL":"COMPUTATION_CONTINUED",
  "FORMAT DU FICHIER DU CALCUL PRECEDENT":"PREVIOUS_COMPUTATION_FILE_FORMAT",
  "FICHIER DU CALCUL PRECEDENT":"PREVIOUS_COMPUTATION_FILE",
  "ENREGISTREMENT POUR SUITE DE CALCUL":"RECORD_NUMBER_FOR_RESTART",
  "REMISE A ZERO DU TEMPS":"INITIAL_TIME_SET_TO_ZERO",
  "MODE SUITE":"RESTART_MODE",
  "FICHIER POUR SUITE":"RESTART_FILE",
  "FORMAT DU FICHIER POUR SUITE":"RESTART_FILE_FORMAT",
  "PERIODE POUR LES SORTIES DU FICHIER POUR SUITE":"RESTART_FILE_PRINTOUT_PERIOD",
  "NUMERO DE L'ENREGISTREMENT DANS LE FICHIER POUR SUITE":"RECORD_NUMBER_IN_RESTART_FILE",
  "UTILISE LES VALEURS MAXIMUM DU FICHIER DU CALCUL PRECEDENT":"USE_MAXIMUM_VALUES_FROM_PREVIOUS_COMPUTATION_FILE",
  "NUMERO DU PREMIER PAS DE TEMPS POUR LES SORTIES GRAPHIQUES":"NUMBER_OF_FIRST_TIME_STEP_FOR_GRAPHIC_PRINTOUTS",
  "PERIODE POUR LES SORTIES GRAPHIQUES":"GRAPHIC_PRINTOUT_PERIOD",
  "VARIABLES POUR LES SORTIES GRAPHIQUES":"VARIABLES_FOR_GRAPHIC_PRINTOUTS",
  "NOMBRE DE TABLEAUX PRIVES":"NUMBER_OF_PRIVATE_ARRAYS",
  "NOMS DES VARIABLES PRIVEES":"NAMES_OF_PRIVATE_VARIABLES",
  "FORMAT DU FICHIER DES RESULTATS":"RESULTS_FILE_FORMAT",
  "FICHIER DES RESULTATS":"RESULTS_FILE",
  "FICHIER RESULTAT EN LONGITUDE-LATITUDE":"RESULT_FILE_IN_LONGITUDE_LATITUDE",
  "FORMAT DU FICHIER DE RESULTATS BINAIRE":"BINARY_RESULTS_FILE_FORMAT",
  "FICHIER DE RESULTATS BINAIRE":"BINARY_RESULTS_FILE",
  "FICHIER DE RESULTATS FORMATE":"FORMATTED_RESULTS_FILE",
  "FICHIER DE RESULTATS FORMATE 1":"FORMATTED_RESULTS_FILE_1",
  "FICHIER DE RESULTATS FORMATE 2":"FORMATTED_RESULTS_FILE_2",
  "FICHIER DE RESULTATS FORMATE 3":"FORMATTED_RESULTS_FILE_3",
  "FICHIER DE RESULTATS FORMATE 4":"FORMATTED_RESULTS_FILE_4",
  "FICHIER DE RESULTATS FORMATE 5":"FORMATTED_RESULTS_FILE_5",
  "FICHIER DE RESULTATS FORMATE 6":"FORMATTED_RESULTS_FILE_6",
  "SECTIONS DE CONTROLE":"CONTROL_SECTIONS",
  "IMPRESSION DU CUMUL DES FLUX":"PRINTING_CUMULATED_FLOWRATES",
  "CALCUL COMPATIBLE DES FLUX":"COMPATIBLE_COMPUTATION_OF_FLUXES",
  "FICHIER DES SECTIONS DE CONTROLE":"SECTIONS_INPUT_FILE",
  "FICHIER DE SORTIE DES SECTIONS DE CONTROLE":"SECTIONS_OUTPUT_FILE",
  "FLUXLINE":"FLUXLINE",
  "FICHIER DE FLUXLINE":"FLUXLINE_INPUT_FILE",
  "NUMERO DU PREMIER PAS DE TEMPS POUR LES SORTIES LISTING":"NUMBER_OF_FIRST_TIME_STEP_FOR_LISTING_PRINTOUTS",
  "PERIODE DE SORTIE LISTING":"LISTING_PRINTOUT_PERIOD",
  "PERIODE POUR LES SORTIES LISTING":"LISTING_FOR_PRINTOUT_PERIOD",
  "SORTIE LISTING":"LISTING_PRINTOUT",
  "VARIABLES A IMPRIMER":"VARIABLES_TO_BE_PRINTED",
  "BILAN DE MASSE":"MASS_BALANCE",
  "INFORMATIONS SUR LE SOLVEUR":"INFORMATION_ABOUT_SOLVER",
  "LISTE DE POINTS":"LIST_OF_POINTS",
  "NOMS DES POINTS":"NAMES_OF_POINTS",
  "PERIODES D'ANALYSE DE FOURIER":"FOURIER_ANALYSIS_PERIODS",
  "BORNES EN TEMPS POUR L'ANALYSE DE FOURIER":"TIME_RANGE_FOR_FOURIER_ANALYSIS",
  "COTES IMPOSEES":"PRESCRIBED_ELEVATIONS",
  "DEBITS IMPOSES":"PRESCRIBED_FLOWRATES",
  "VITESSES IMPOSEES":"PRESCRIBED_VELOCITIES",
  "COURBES DE TARAGE":"STAGE_DISCHARGE_CURVES",
  "FICHIER DES COURBES DE TARAGE":"STAGE_DISCHARGE_CURVES_FILE",
  "COEFFICIENT DE RELAXATION DES COURBES DE TARAGE":"STAGE_DISCHARGE_CURVES_RELAXATION_COEFFICIENT",
  "PROFILS DE VITESSE":"VELOCITY_PROFILES",
  "OPTION POUR LES FRONTIERES LIQUIDES":"OPTION_FOR_LIQUID_BOUNDARIES",
  "FICHIER DES FRONTIERES LIQUIDES":"LIQUID_BOUNDARIES_FILE",
  "ELEMENTS MASQUES PAR L'UTILISATEUR":"ELEMENTS_MASKED_BY_USER",
  "NOMBRE MAXIMUM DE DOMAINES DE FROTTEMENT":"MAXIMUM_NUMBER_OF_FRICTION_DOMAINS",
  "DONNEES POUR LE FROTTEMENT":"FRICTION_DATA",
  "FICHIER DE DONNEES POUR LE FROTTEMENT":"FRICTION_DATA_FILE",
  "LOI DE FROTTEMENT SUR LE FOND":"LAW_OF_BOTTOM_FRICTION",
  "COEFFICIENT DE FROTTEMENT":"FRICTION_COEFFICIENT",
  "VALEUR PAR DEFAUT DU MANNING POUR LA LOI DE COLEBROOK-WHITE":"MANNING_DEFAULT_VALUE_FOR_COLEBROOK_WHITE_LAW",
  "HAUTEUR DANS LES TERMES DE FROTTEMENT":"DEPTH_IN_FRICTION_TERMS",
  "FROTTEMENT POUR LA VEGETATION":"VEGETATION_FRICTION",
  "LOI DE FROTTEMENT SUR LES PAROIS LATERALES":"LAW_OF_FRICTION_ON_LATERAL_BOUNDARIES",
  "COEFFICIENT DE RUGOSITE DES BORDS":"ROUGHNESS_COEFFICIENT_OF_BOUNDARIES",
  "DEFINITION DE ZONES":"DEFINITION_OF_ZONES",
  "FICHIER DES ZONES":"ZONES_FILE",
  "MODELE NON-NEWTONIEN":"NON_NEWTONIAN_MODEL",
  "OPTION DU MODELE DE BINGHAM":"BINGHAM_OPTION",
  "VISCOSITE DU FLUIDE NON-NEWTONIEN":"NON_NEWTONIAN_VISCOSITY",
  "CONTRAINTE D'ELASTICITE DU FLUIDE NON-NEWTONIEN":"NON_NEWTONIAN_YIELD_STRESS",
  "RESISTANCE LAMINAIRE DU FLUIDE NON-NEWTONIEN":"NON_NEWTONIAN_LAMINAR_RESISTANCE_PARAMETER_K",
  "DENSITE DU FLUIDE NON-NEWTONIEN":"NON_NEWTONIAN_FLUID_DENSITY",
  "MODELE NON-NEWTONIEN PSEUDO DIPHASIQUE":"NON_NEWTONIAN_PSEUDO_BIPHASIC_MODEL",
  "INDICE POUR LE MODELE DE HERSCHEL-BULKLEY":"HERSCHEL_BULKLEY_POWER_LAW_INDEX",
  "VENT":"WIND",
  "OPTION DU VENT":"OPTION_FOR_WIND",
  "COEFFICIENT D'INFLUENCE DU VENT":"COEFFICIENT_OF_WIND_INFLUENCE",
  "COEFFICIENT D'INFLUENCE DU VENT DEPENDANT DE LA VITESSE DU VENT":"COEFFICIENT_OF_WIND_INFLUENCE_VARYING_WITH_WIND_SPEED",
  "VITESSE DU VENT SUIVANT X":"WIND_VELOCITY_ALONG_X",
  "VITESSE DU VENT SUIVANT Y":"WIND_VELOCITY_ALONG_Y",
  "VITESSE ET DIRECTION DU VENT":"SPEED_AND_DIRECTION_OF_WIND",
  "PROFONDEUR LIMITE POUR LE VENT":"THRESHOLD_DEPTH_FOR_WIND",
  "PRESSION ATMOSPHERIQUE":"AIR_PRESSURE",
  "VALEUR DE LA PRESSION ATMOSPHERIQUE":"VALUE_OF_ATMOSPHERIC_PRESSURE",
  "PLUIE OU EVAPORATION":"RAIN_OR_EVAPORATION",
  "PLUIE OU EVAPORATION EN MM PAR JOUR":"RAIN_OR_EVAPORATION_IN_MM_PER_DAY",
  "MODELE PLUIE-DEBIT":"RAINFALL_RUNOFF_MODEL",
  "CONDITIONS D'HUMIDITE PRECEDENTE":"ANTECEDENT_MOISTURE_CONDITIONS",
  "CONSTANTE DE TEMPS HORTON":"HORTON_TIME_CONSTANT",
  "TENEUR EN EAU INITIALE":"INITIAL_WATER_CONTENT",
  "TENEUR EN EAU A SATURATION":"SATURATED_WATER_CONTENT",
  "SUCCION":"SUCTION",
  "DUREE DE LA PLUIE OU EVAPORATION EN HEURES":"DURATION_OF_RAIN_OR_EVAPORATION_IN_HOURS",
  "FICHIER ASCII DE DONNEES ATMOSPHERIQUES":"ASCII_ATMOSPHERIC_DATA_FILE",
  "FICHIER BINAIRE DE DONNEES ATMOSPHERIQUES":"BINARY_ATMOSPHERIC_DATA_FILE",
  "FORMAT DU FICHIER BINAIRE DE DONNEES ATMOSPHERIQUES":"BINARY_ATMOSPHERIC_DATA_FILE_FORMAT",
  "FORMAT LIBRE POUR FICHIER DE DONNEES ATMOSPHERIQUES":"FREE_FORMAT_FOR_ATMOSPHERIC_DATA_FILE",
  "OPTION POUR RATIO DES PERTES INITIALES":"OPTION_FOR_INITIAL_ABSTRACTION_RATIO",
  "TEMPERATURE DE L'AIR":"AIR_TEMPERATURE",
  "NEBULOSITE":"CLOUD_COVER",
  "RAYONNEMENT SOLAIRE":"SOLAR_RADIATION",
  "PRESSION DE VAPEUR SATURANTE":"VAPOROUS_PRESSURE",
  "COURANTS DE HOULE":"WAVE_DRIVEN_CURRENTS",
  "NUMERO DE L'ENREGISTREMENT DANS LE FICHIER DE HOULE":"RECORD_NUMBER_IN_WAVE_FILE",
  "AUGMENTATION DU FROTTEMENT PAR LA HOULE":"WAVE_ENHANCED_FRICTION_FACTOR",
  "ESTIMATION DE PARAMETRE":"PARAMETER_ESTIMATION",
  "FONCTION COUT":"COST_FUNCTION",
  "METHODE D'IDENTIFICATION":"IDENTIFICATION_METHOD",
  "PRECISIONS POUR L'IDENTIFICATION":"TOLERANCES_FOR_IDENTIFICATION",
  "MAXIMUM D'ITERATIONS POUR L'IDENTIFICATION":"MAXIMUM_NUMBER_OF_ITERATIONS_FOR_IDENTIFICATION",
  "ABSCISSES DES SOURCES":"ABSCISSAE_OF_SOURCES",
  "ORDONNEES DES SOURCES":"ORDINATES_OF_SOURCES",
  "DEBITS DES SOURCES":"WATER_DISCHARGE_OF_SOURCES",
  "VITESSES DES SOURCES SELON X":"VELOCITIES_OF_THE_SOURCES_ALONG_X",
  "VITESSES DES SOURCES SELON Y":"VELOCITIES_OF_THE_SOURCES_ALONG_Y",
  "TYPE DES SOURCES":"TYPE_OF_SOURCES",
  "FICHIER DES SOURCES":"SOURCES_FILE",
  "NUMEROS GLOBAUX DES NOEUDS DES SOURCES":"GLOBAL_NUMBERS_OF_SOURCE_NODES",
  "FICHIER DES REGIONS DES SOURCES":"SOURCE_REGIONS_DATA_FILE",
  "NOMBRE MAXIMUM DE POINTS POUR DEFINIR DES SOURCES":"MAXIMUM_NUMBER_OF_POINTS_FOR_SOURCES_REGIONS",
  "PROCESSUS QUALITE D'EAU":"WATER_QUALITY_PROCESS",
  "MASSE VOLUMIQUE DE L'EAU":"WATER_DENSITY",
  "ACCELERATION DE LA PESANTEUR":"GRAVITY_ACCELERATION",
  "STRUCTURES VERTICALES":"VERTICAL_STRUCTURES",
  "EQUATIONS":"EQUATIONS",
  "TRAITEMENT DU SYSTEME LINEAIRE":"TREATMENT_OF_THE_LINEAR_SYSTEM",
  "SCHEMA EN VOLUMES FINIS":"FINITE_VOLUME_SCHEME",
  "ORDRE EN ESPACE DU SCHEMA VOLUME FINIS":"FINITE_VOLUME_SCHEME_SPACE_ORDER",
  "ORDRE EN TEMPS DU SCHEMA VOLUME FINIS":"FINITE_VOLUME_SCHEME_TIME_ORDER",
  "LIMITEUR DE FLUX POUR H PLUS Z":"FLUX_LIMITOR_FOR_H_PLUS_Z",
  "LIMITEUR DE FLUX POUR U ET V":"FLUX_LIMITOR_FOR_U_AND_V",
  "LIMITEUR DE FLUX POUR LES TRACEURS":"FLUX_LIMITOR_FOR_TRACERS",
  "TYPE DE CONDITION A LA LIMITE POUR LE SCHEMA CINETIQUE":"TYPE_OF_BOUNDARY_CONDITION_FOR_KINETIC_SCHEME",
  "CORIOLIS":"CORIOLIS",
  "COEFFICIENT DE CORIOLIS":"CORIOLIS_COEFFICIENT",
  "OPTION POUR LA GENERATION DE TSUNAMI":"OPTION_FOR_TSUNAMI_GENERATION",
  "PARAMETRES PHYSIQUES DU TSUNAMI":"PHYSICAL_CHARACTERISTICS_OF_THE_TSUNAMI",
  "COURANTS SECONDAIRES":"SECONDARY_CURRENTS",
  "COEFFICIENT DE PRODUCTION POUR COURANTS SECONDAIRES":"PRODUCTION_COEFFICIENT_FOR_SECONDARY_CURRENTS",
  "COEFFICIENT DE DISSIPATION POUR COURANTS SECONDAIRES":"DISSIPATION_COEFFICIENT_FOR_SECONDARY_CURRENTS",
  "DEBUGGER":"DEBUGGER",
  "PAS DE TEMPS":"TIME_STEP",
  "NOMBRE DE PAS DE TEMPS":"NUMBER_OF_TIME_STEPS",
  "DUREE DU CALCUL":"DURATION",
  "DATE DE L'ORIGINE DES TEMPS":"ORIGINAL_DATE_OF_TIME",
  "HEURE DE L'ORIGINE DES TEMPS":"ORIGINAL_HOUR_OF_TIME",
  "ARRET SI UN ETAT PERMANENT EST ATTEINT":"STOP_IF_A_STEADY_STATE_IS_REACHED",
  "CRITERES D'ARRET":"STOP_CRITERIA",
  "CONTROLE DES LIMITES":"CONTROL_OF_LIMITS",
  "VALEURS LIMITES":"LIMIT_VALUES",
  "PAS DE TEMPS VARIABLE":"VARIABLE_TIME_STEP",
  "NOMBRE DE COURANT SOUHAITE":"DESIRED_COURANT_NUMBER",
  "NOMBRE DE FOURIER SOUHAITE":"DESIRED_FOURIER_NUMBER",
  "COORDONNEES SPHERIQUES":"SPHERICAL_COORDINATES",
  "LATITUDE DU POINT ORIGINE":"LATITUDE_OF_ORIGIN_POINT",
  "LONGITUDE DU POINT ORIGINE":"LONGITUDE_OF_ORIGIN_POINT",
  "NORD":"NORTH",
  "TYPE DE PROJECTION SPATIALE":"SPATIAL_PROJECTION_TYPE",
  "SOLVEUR":"SOLVER",
  "OPTION DU SOLVEUR":"SOLVER_OPTION",
  "PRECISION DU SOLVEUR":"SOLVER_ACCURACY",
  "MAXIMUM D'ITERATIONS POUR LE SOLVEUR":"MAXIMUM_NUMBER_OF_ITERATIONS_FOR_SOLVER",
  "CORRECTION DE CONTINUITE":"CONTINUITY_CORRECTION",
  "PRECONDITIONNEMENT":"PRECONDITIONING",
  "PRECONDITIONNEMENT C-U":"C_U_PRECONDITIONING",
  "ASSEMBLAGE EN ELEMENTS FINIS":"FINITE_ELEMENT_ASSEMBLY",
  "IMPLICITATION POUR LA HAUTEUR":"IMPLICITATION_FOR_DEPTH",
  "IMPLICITATION POUR LA VITESSE":"IMPLICITATION_FOR_VELOCITY",
  "DISCRETISATIONS EN ESPACE":"DISCRETIZATIONS_IN_SPACE",
  "PROPAGATION":"PROPAGATION",
  "ORDRE DU TIR INITIAL POUR H":"INITIAL_GUESS_FOR_H",
  "PROPAGATION LINEARISEE":"LINEARIZED_PROPAGATION",
  "ORDRE DU TIR INITIAL POUR U":"INITIAL_GUESS_FOR_U",
  "PROFONDEUR MOYENNE POUR LA LINEARISATION":"MEAN_DEPTH_FOR_LINEARIZATION",
  "CONVECTION":"ADVECTION",
  "CONVECTION DE H":"ADVECTION_OF_H",
  "CONVECTION DE U ET V":"ADVECTION_OF_U_AND_V",
  "FORME DE LA CONVECTION":"TYPE_OF_ADVECTION",
  "OPTION POUR LES CARACTERISTIQUES":"OPTION_FOR_CHARACTERISTICS",
  "OPTION DE SUPG":"SUPG_OPTION",
  "NOMBRE DE POINTS DE GAUSS POUR LES CARACTERISTIQUES FAIBLES":"NUMBER_OF_GAUSS_POINTS_FOR_WEAK_CHARACTERISTICS",
  "MASS-LUMPING POUR LES CARACTERISTIQUES FAIBLES":"MASS_LUMPING_FOR_WEAK_CHARACTERISTICS",
  "MAXIMUM D'ITERATIONS POUR LES SCHEMAS DE CONVECTION":"MAXIMUM_NUMBER_OF_ITERATIONS_FOR_ADVECTION_SCHEMES",
  "MASS-LUMPING SUR H":"MASS_LUMPING_ON_H",
  "MASS-LUMPING SUR LA VITESSE":"MASS_LUMPING_ON_VELOCITY",
  "SCHEMA POUR LA CONVECTION DES VITESSES":"SCHEME_FOR_ADVECTION_OF_VELOCITIES",
  "OPTION DU SCHEMA POUR LA CONVECTION DES VITESSES":"SCHEME_OPTION_FOR_ADVECTION_OF_VELOCITIES",
  "COMPATIBILITE DU GRADIENT DE SURFACE LIBRE":"FREE_SURFACE_GRADIENT_COMPATIBILITY",
  "NOMBRE DE SOUS-ITERATIONS POUR LES NON-LINEARITES":"NUMBER_OF_SUB_ITERATIONS_FOR_NON_LINEARITIES",
  "TRAITEMENT DES FLUX AUX FRONTIERES":"TREATMENT_OF_FLUXES_AT_THE_BOUNDARIES",
  "NOMBRE DE CORRECTIONS DES SCHEMAS DISTRIBUTIFS":"NUMBER_OF_CORRECTIONS_OF_DISTRIBUTIVE_SCHEMES",
  "NOMBRE DE SOUS-PAS DES SCHEMAS DISTRIBUTIFS":"NUMBER_OF_SUB_STEPS_OF_DISTRIBUTIVE_SCHEMES",
  "DIFFUSION DES VITESSES":"DIFFUSION_OF_VELOCITY",
  "OPTION POUR LA DIFFUSION DES VITESSES":"OPTION_FOR_THE_DIFFUSION_OF_VELOCITIES",
  "IMPLICITATION POUR LA DIFFUSION DES VITESSES":"IMPLICITATION_FOR_DIFFUSION_OF_VELOCITY",
  "SCHEMA VOLUMES FINIS POUR LA DIFFUSION DES VITESSES":"FINITE_VOLUME_SCHEME_FOR_VELOCITY_DIFFUSION",
  "SCHEMA VOLUMES FINIS POUR LA DIFFUSION DES TRACEURS":"FINITE_VOLUME_SCHEME_FOR_TRACER_DIFFUSION",
  "OPTION POUR LA RECONSTRUCTION DU SCHEMA RTPF":"OPTION_FOR_THE_RTPF_SCHEME_RECONSTRUCTIONS",
  "OPTION DE LA CONDITION DE DIRICHLET POUR LA DIFFUSION VF":"OPTION_FOR_DIRICHLET_CONDITION_IN_FV_DIFFUSION",
  "AD NOMBRE DE DERIVEES":"AD_NUMBER_OF_DERIVATIVES",
  "AD NOMS DES DERIVEES":"AD_NAMES_OF_DERIVATIVES",
  "AD SOLVEUR LINEAIRE SYMBOLIQUE":"AD_SYMBOLIC_LINEAR_SOLVER",
  "AD REMISE A ZERO DES DERIVEES DU SOLVEUR LINEAIRE":"AD_LINEAR_SOLVER_RESET_DERIVATIVES",
  "AD CONVERGENCE DES DERIVEES POUR LE SOLVEUR LINEAIRE":"AD_LINEAR_SOLVER_DERIVATIVE_CONVERGENCE",
  "STOCKAGE DES MATRICES":"MATRIX_STORAGE",
  "PRODUIT MATRICE-VECTEUR":"MATRIX_VECTOR_PRODUCT",
  "COEFFICIENT D'INTEGRATION EN TEMPS DE NEWMARK":"NEWMARK_TIME_INTEGRATION_COEFFICIENT",
  "ZERO":"ZERO",
  "OPTION DE LA RECONSTRUCTION HYDROSTATIQUE":"OPTION_OF_THE_HYDROSTATIC_RECONSTRUCTION",
  "ETUDE DE CONVERGENCE":"CONVERGENCE_STUDY",
  "NIVEAUX DE RAFFINEMENT":"REFINEMENT_LEVELS",
  "COEFFICIENT DE DIFFUSION DES VITESSES":"VELOCITY_DIFFUSIVITY",
  "MODELE DE TURBULENCE":"TURBULENCE_MODEL",
  "PRECISION SUR SPALART-ALLMARAS":"ACCURACY_OF_SPALART_ALLMARAS",
  "INFORMATION SUR LE MODELE SPALART-ALLMARAS":"INFORMATION_ABOUT_SPALART_ALLMARAS_MODEL",
  "SOLVEUR POUR LE MODELE K-EPSILON":"SOLVER_FOR_K_EPSILON_MODEL",
  "OPTION DU SOLVEUR POUR LE MODELE K-EPSILON":"OPTION_FOR_THE_SOLVER_FOR_K_EPSILON_MODEL",
  "PRECONDITIONNEMENT POUR LE MODELE K-EPSILON":"PRECONDITIONING_FOR_K_EPSILON_MODEL",
  "COEFFICIENTS ADIMENSIONNELS DE DISPERSION":"NON_DIMENSIONAL_DISPERSION_COEFFICIENTS",
  "REGIME DE TURBULENCE POUR LES PAROIS":"TURBULENCE_REGIME_FOR_SOLID_BOUNDARIES",
  "INFORMATIONS SUR LE MODELE K-EPSILON":"INFORMATION_ABOUT_K_EPSILON_MODEL",
  "CONVECTION DE K ET EPSILON":"ADVECTION_OF_K_AND_EPSILON",
  "SCHEMA POUR LA CONVECTION DU K-EPSILON":"SCHEME_FOR_ADVECTION_OF_K_EPSILON",
  "OPTION DU SCHEMA POUR LA CONVECTION DU K-EPSILON":"SCHEME_OPTION_FOR_ADVECTION_OF_K_EPSILON",
  "COEFFICIENTS DU MODELE DE LONGUEUR DE MELANGE":"MIXING_LENGTH_MODEL_COEFFICIENTS",
  "PRECISION SUR K":"ACCURACY_OF_K",
  "PRECISION SUR EPSILON":"ACCURACY_OF_EPSILON",
  "MAXIMUM D'ITERATIONS POUR K ET EPSILON":"MAXIMUM_NUMBER_OF_ITERATIONS_FOR_K_AND_EPSILON",
  "BANCS DECOUVRANTS":"TIDAL_FLATS",
  "OPTION DE TRAITEMENT DES BANCS DECOUVRANTS":"OPTION_FOR_THE_TREATMENT_OF_TIDAL_FLATS",
  "TRAITEMENT DES HAUTEURS NEGATIVES":"TREATMENT_OF_NEGATIVE_DEPTHS",
  "SEUIL POUR LES PROFONDEURS NEGATIVES":"THRESHOLD_FOR_NEGATIVE_DEPTHS",
  "PROFONDEUR LIMITE POUR PROCEDURE DE RESSUYAGE":"THRESHOLD_DEPTH_FOR_RECEDING_PROCEDURE",
  "CLIPPING DE H":"H_CLIPPING",
  "VALEUR MINIMUM DE H":"MINIMUM_VALUE_OF_DEPTH",
  "VALEURS IMPOSEES DES TRACEURS":"PRESCRIBED_TRACERS_VALUES",
  "NOMBRE DE TRACEURS":"NUMBER_OF_TRACERS",
  "NOMS DES TRACEURS":"NAMES_OF_TRACERS",
  "VALEURS INITIALES DES TRACEURS":"INITIAL_VALUES_OF_TRACERS",
  "EFFETS DE DENSITE":"DENSITY_EFFECTS",
  "TEMPERATURE MOYENNE":"MEAN_TEMPERATURE",
  "SOLVEUR POUR LA DIFFUSION DES TRACEURS":"SOLVER_FOR_DIFFUSION_OF_TRACERS",
  "OPTION DU SOLVEUR POUR LA DIFFUSION DES TRACEURS":"SOLVER_OPTION_FOR_TRACERS_DIFFUSION",
  "PRECONDITIONNEMENT POUR LA DIFFUSION DES TRACEURS":"PRECONDITIONING_FOR_DIFFUSION_OF_TRACERS",
  "PRECISION POUR LA DIFFUSION DES TRACEURS":"ACCURACY_FOR_DIFFUSION_OF_TRACERS",
  "MAXIMUM D'ITERATIONS POUR LA DIFFUSION DES TRACEURS":"MAXIMUM_NUMBER_OF_ITERATIONS_FOR_DIFFUSION_OF_TRACERS",
  "VALEURS DES TRACEURS DES SOURCES":"VALUES_OF_THE_TRACERS_AT_THE_SOURCES",
  "VALEURS DES TRACEURS DANS LA PLUIE":"VALUES_OF_TRACERS_IN_THE_RAIN",
  "CONVECTION DES TRACEURS":"ADVECTION_OF_TRACERS",
  "COEFFICIENT D'IMPLICITATION DES TRACEURS":"IMPLICITATION_COEFFICIENT_OF_TRACERS",
  "DIFFUSION DES TRACEURS":"DIFFUSION_OF_TRACERS",
  "COEFFICIENT DE DIFFUSION DES TRACEURS":"COEFFICIENT_FOR_DIFFUSION_OF_TRACERS",
  "OPTION POUR LA DIFFUSION DES TRACEURS":"OPTION_FOR_THE_DIFFUSION_OF_TRACERS",
  "SCHEMA POUR LA CONVECTION DES TRACEURS":"SCHEME_FOR_ADVECTION_OF_TRACERS",
  "OPTION DU SCHEMA POUR LA CONVECTION DES TRACEURS":"SCHEME_OPTION_FOR_ADVECTION_OF_TRACERS",
  "MASS-LUMPING SUR LES TRACEURS":"MASS_LUMPING_ON_TRACERS",
  "NOMBRE MAXIMAL DE FLOTTEURS":"MAXIMUM_NUMBER_OF_DROGUES",
  "DENSITE INITIALE DE REPARTITION DES FLOTTEURS":"INITIAL_DROGUES_SAMPLING_DENSITY",
  "PERIODE POUR LES SORTIES DE FLOTTEURS":"PRINTOUT_PERIOD_FOR_DROGUES",
  "FICHIER ASCII DES FLOTTEURS":"ASCII_DROGUES_FILE",
  "FICHIER BINAIRE DES FLOTTEURS":"BINARY_DROGUES_FILE",
  "FORMAT DU FICHIER DES FLOTTEURS":"DROGUES_FILE_FORMAT",
  "FICHIER DES FLOTTEURS PRECEDENT":"PREVIOUS_DROGUES_FILE",
  "FORMAT DU FICHIER DES FLOTTEURS PRECEDENT":"PREVIOUS_DROGUES_FILE_FORMAT",
  "FICHIER POSITIONNANT LES DROGUES INITIALES":"DROGUES_INITIAL_POSITIONING_DATA_FILE",
  "FORMAT DU FICHIER POSITIONNANT LES DROGUES":"FORMAT_OF_THE_DROGUES_POSITIONING_DATA_FILE",
  "MODELE DE TRANSPORT DES ALGUES":"ALGAE_TRANSPORT_MODEL",
  "NOMBRE DE CLASSES D'ALGUES":"NUMBER_OF_ALGAE_CLASSES",
  "TYPE DES ALGUES":"ALGAE_TYPE",
  "DIAMETRE DES ALGUES":"DIAMETER_OF_ALGAE",
  "DUREE AVANT RELACHE DES ALGUES":"DURATION_BEFORE_ALGAE_RELEASE",
  "MASSE VOLUMIQUE DES ALGUES":"DENSITY_OF_ALGAE",
  "EPAISSEUR DES ALGUES":"THICKNESS_OF_ALGAE",
  "TYPE DE RELACHE DES ALGUES":"ALGAE_RELEASE_TYPE",
  "SEUIL DE LA VITESSE ORBITALE DE VAGUE POUR LES ALGUES 1":"WAVE_ORBITAL_VELOCITY_THRESHOLD_FOR_ALGAE_1",
  "SEUIL DE LA VITESSE ORBITALE DE VAGUE POUR LES ALGUES 2":"WAVE_ORBITAL_VELOCITY_THRESHOLD_FOR_ALGAE_2",
  "TAUX DE DEGRADATION POUR LES ALGUES":"RATE_OF_DEGRADATION_FOR_ALGAE",
  "MODELE DE NAPPES D'HYDROCARBURES":"OIL_SPILL_MODEL",
  "FICHIER DE COMMANDES HYDROCARBURES":"OIL_SPILL_STEERING_FILE",
  "MODELE DE DIFFUSION STOCHASTIQUE":"STOCHASTIC_DIFFUSION_MODEL",
  "NOMBRE DE DERIVES LAGRANGIENNES":"NUMBER_OF_LAGRANGIAN_DRIFTS",
  "NOMBRE DE SEUILS":"NUMBER_OF_WEIRS",
  "FICHIER DE DONNEES DES SEUILS":"WEIRS_DATA_FILE",
  "TYPE DES SEUILS":"TYPE_OF_WEIRS",
  "FICHIER DE SORTIE DES DEBITS DES SEUILS":"WEIRS_DISCHARGE_OUTPUT_FILE",
  "NOMBRE DE BUSES":"NUMBER_OF_CULVERTS",
  "FICHIER DE DONNEES DES BUSES":"CULVERTS_DATA_FILE",
  "OPTION POUR LES BUSES":"OPTION_FOR_CULVERTS",
  "BRECHE":"BREACH",
  "FICHIER DE DONNEES DES BRECHES":"BREACHES_DATA_FILE",
  "LARGEURS INITIALES DES BRECHES":"INITIAL_WIDTHS_OF_BREACHES",
  "BASE BINAIRE 1 DE DONNEES DE MAREE":"BINARY_DATABASE_1_FOR_TIDE",
  "BASE BINAIRE 2 DE DONNEES DE MAREE":"BINARY_DATABASE_2_FOR_TIDE",
  "SYSTEME GEOGRAPHIQUE":"GEOGRAPHIC_SYSTEM",
  "NUMERO DE FUSEAU OU PROJECTION DANS LE SYSTEME GEOGRAPHIQUE":"ZONE_NUMBER_IN_GEOGRAPHIC_SYSTEM",
  "FICHIER DE CONVERSION LAMBERT 93":"LAMBERT_93_CONVERSION_FILE",
  "COEFFICIENT DE CALAGE DU NIVEAU DE MER":"COEFFICIENT_TO_CALIBRATE_SEA_LEVEL",
  "NUMERO GLOBAL DU POINT POUR CALER LA PLEINE MER":"GLOBAL_NUMBER_OF_THE_POINT_TO_CALIBRATE_HIGH_WATER",
  "INTERPOLATION DE COMPOSANTES MINEURES":"MINOR_CONSTITUENTS_INFERENCE",
  "VITESSES INITIALES CALCULEES PAR TPXO":"INITIAL_VELOCITIES_COMPUTED_BY_TPXO",
  "HAUTEUR MINIMALE POUR LES CONDITIONS INITIALES DE COURANTS":"MINIMUM_DEPTH_TO_COMPUTE_TIDAL_VELOCITIES_INITIAL_CONDITIONS",
  "OPTION POUR LES CONDITIONS AUX LIMITES DE MAREE":"OPTION_FOR_TIDAL_BOUNDARY_CONDITIONS",
  "BASE DE DONNEES DE MAREE":"TIDAL_DATA_BASE",
  "FICHIER DES CONSTANTES HARMONIQUES":"HARMONIC_CONSTANTS_FILE",
  "FICHIER DU MODELE DE MAREE":"TIDAL_MODEL_FILE",
  "FORMAT DU FICHIER DU MODELE DE MAREE":"TIDAL_MODEL_FILE_FORMAT",
  "BASE ASCII DE DONNEES DE MAREE":"ASCII_DATABASE_FOR_TIDE",
  "COEFFICIENT DE CALAGE DU MARNAGE":"COEFFICIENT_TO_CALIBRATE_TIDAL_RANGE",
  "COEFFICIENT DE CALAGE DES VITESSES DE COURANT":"COEFFICIENT_TO_CALIBRATE_TIDAL_VELOCITIES",
  "NUMERO LOCAL DU POINT POUR CALER LA PLEINE MER":"LOCAL_NUMBER_OF_THE_POINT_TO_CALIBRATE_HIGH_WATER",
  "HAUTEUR MINIMALE POUR LES CONDITIONS AUX LIMITES DE COURANTS":"MINIMUM_DEPTH_TO_COMPUTE_TIDAL_VELOCITIES_BOUNDARY_CONDITIONS",
  "FORCE GENERATRICE DE LA MAREE":"TIDE_GENERATING_FORCE",
  "COUPLAGE AVEC":"COUPLING_WITH",
  "NOMS DES VARIABLES CLANDESTINES":"NAMES_OF_CLANDESTINE_VARIABLES",
  "FICHIER DE COMMANDE DELWAQ":"DELWAQ_STEERING_FILE",
  "PERIODE DE SORTIE POUR DELWAQ":"DELWAQ_PRINTOUT_PERIOD",
  "FICHIER DELWAQ DES ECHANGES ENTRE NOEUDS":"EXCHANGES_BETWEEN_NODES_DELWAQ_FILE",
  "FICHIER DELWAQ DES DISTANCES ENTRE NOEUDS":"NODES_DISTANCES_DELWAQ_FILE",
  "FICHIER DELWAQ DES SURFACES DU FOND":"BOTTOM_SURFACES_DELWAQ_FILE",
  "FICHIER DELWAQ DES VOLUMES":"VOLUMES_DELWAQ_FILE",
  "FICHIER DELWAQ DES SURFACES DE FLUX":"EXCHANGE_AREAS_DELWAQ_FILE",
  "FICHIER DELWAQ DES FLUX VERTICAUX":"VERTICAL_FLUXES_DELWAQ_FILE",
  "FICHIER DELWAQ DE LA VITESSE":"VELOCITY_DELWAQ_FILE",
  "FICHIER DELWAQ DE LA DIFFUSION":"DIFFUSIVITY_DELWAQ_FILE",
  "FICHIER DELWAQ DE LA TEMPERATURE":"TEMPERATURE_DELWAQ_FILE",
  "FICHIER DELWAQ DE LA SALINITE":"SALINITY_DELWAQ_FILE",
  "VITESSE POUR DELWAQ":"VELOCITY_FOR_DELWAQ",
  "DIFFUSION POUR DELWAQ":"DIFFUSIVITY_FOR_DELWAQ",
  "TEMPERATURE POUR DELWAQ":"TEMPERATURE_FOR_DELWAQ",
  "SALINITE POUR DELWAQ":"SALINITY_FOR_DELWAQ",
  "FICHIER DES PARAMETRES DE SISYPHE":"SISYPHE_STEERING_FILE",
  "PERIODE DE COUPLAGE POUR SISYPHE":"COUPLING_PERIOD_FOR_SISYPHE",
  "FICHIER DES PARAMETRES DE GAIA":"GAIA_STEERING_FILE",
  "FICHIER DES PARAMETRES DE TOMAWAC":"TOMAWAC_STEERING_FILE",
  "PERIODE DE COUPLAGE POUR TOMAWAC":"COUPLING_PERIOD_FOR_TOMAWAC",
  "FICHIER DES PARAMETRES DE WAQTEL":"WAQTEL_STEERING_FILE",
  "FICHIER DES PARAMETRES DE KHIONE":"KHIONE_STEERING_FILE",
  "NESTOR":"NESTOR",
  "FICHIER DES PARAMETRES DE NESTOR":"NESTOR_ACTION_FILE",
  "FICHIER DE POLYGONES DE NESTOR":"NESTOR_POLYGON_FILE",
  "FICHIER DE SURFACE REFERENCE DE NESTOR":"NESTOR_SURFACE_REFERENCE_FILE",
  "FICHIER DE REPRISE DE NESTOR":"NESTOR_RESTART_FILE",
  "LANGUE":"LANGUAGE",
  "FICHIER DES PARAMETRES":"STEERING_FILE",
  "DICTIONNAIRE":"DICTIONARY",
  "PARTITIONNEUR":"PARTITIONING_TOOL",
  "CONCATENATION SORTIE PARTEL":"CONCATENATE_PARTEL_OUTPUT",
}

DicoCasEnToCata = {
  'TITLE':'TITLE',
  'INITIAL CONDITIONS':'INITIAL_CONDITIONS',
  'INITIAL ELEVATION':'INITIAL_ELEVATION',
  'INITIAL DEPTH':'INITIAL_DEPTH',
  'BINARY DATA FILE 1 FORMAT':'BINARY_DATA_FILE_1_FORMAT',
  'BINARY DATA FILE 1':'BINARY_DATA_FILE_1',
  'BINARY DATA FILE 2 FORMAT':'BINARY_DATA_FILE_2_FORMAT',
  'BINARY DATA FILE 2':'BINARY_DATA_FILE_2',
  'FORMATTED DATA FILE 1':'FORMATTED_DATA_FILE_1',
  'FORMATTED DATA FILE 2':'FORMATTED_DATA_FILE_2',
  'GEOMETRY FILE FORMAT':'GEOMETRY_FILE_FORMAT',
  'GEOMETRY FILE':'GEOMETRY_FILE',
  'FORTRAN FILE':'FORTRAN_FILE',
  'BOTTOM TOPOGRAPHY FILE':'BOTTOM_TOPOGRAPHY_FILE',
  'BOTTOM SMOOTHINGS':'BOTTOM_SMOOTHINGS',
  'BOTTOM SMOOTHINGS AFTER USER MODIFICATIONS':'BOTTOM_SMOOTHINGS_AFTER_USER_MODIFICATIONS',
  'BOUNDARY CONDITIONS FILE':'BOUNDARY_CONDITIONS_FILE',
  'VALIDATION':'VALIDATION',
  'REFERENCE FILE FORMAT':'REFERENCE_FILE_FORMAT',
  'REFERENCE FILE':'REFERENCE_FILE',
  'PARALLEL PROCESSORS':'PARALLEL_PROCESSORS',
  'CHECKING THE MESH':'CHECKING_THE_MESH',
  'MAXIMUM NUMBER OF BOUNDARIES':'MAXIMUM_NUMBER_OF_BOUNDARIES',
  'MAXIMUM NUMBER OF SOURCES':'MAXIMUM_NUMBER_OF_SOURCES',
  'MAXIMUM NUMBER OF TRACERS':'MAXIMUM_NUMBER_OF_TRACERS',
  'VECTOR LENGTH':'VECTOR_LENGTH',
  'SECURITY COEFFICIENT FOR SCARACT':'SECURITY_COEFFICIENT_FOR_SCARACT',
  'COMPUTATION CONTINUED':'COMPUTATION_CONTINUED',
  'PREVIOUS COMPUTATION FILE FORMAT':'PREVIOUS_COMPUTATION_FILE_FORMAT',
  'PREVIOUS COMPUTATION FILE':'PREVIOUS_COMPUTATION_FILE',
  'RECORD NUMBER FOR RESTART':'RECORD_NUMBER_FOR_RESTART',
  'INITIAL TIME SET TO ZERO':'INITIAL_TIME_SET_TO_ZERO',
  'RESTART MODE':'RESTART_MODE',
  'RESTART FILE':'RESTART_FILE',
  'RESTART FILE FORMAT':'RESTART_FILE_FORMAT',
  'RESTART FILE PRINTOUT PERIOD':'RESTART_FILE_PRINTOUT_PERIOD',
  'RECORD NUMBER IN RESTART FILE':'RECORD_NUMBER_IN_RESTART_FILE',
  'USE MAXIMUM VALUES FROM PREVIOUS COMPUTATION FILE':'USE_MAXIMUM_VALUES_FROM_PREVIOUS_COMPUTATION_FILE',
  'NUMBER OF FIRST TIME STEP FOR GRAPHIC PRINTOUTS':'NUMBER_OF_FIRST_TIME_STEP_FOR_GRAPHIC_PRINTOUTS',
  'GRAPHIC PRINTOUT PERIOD':'GRAPHIC_PRINTOUT_PERIOD',
  'VARIABLES FOR GRAPHIC PRINTOUTS':'VARIABLES_FOR_GRAPHIC_PRINTOUTS',
  'NUMBER OF PRIVATE ARRAYS':'NUMBER_OF_PRIVATE_ARRAYS',
  'NAMES OF PRIVATE VARIABLES':'NAMES_OF_PRIVATE_VARIABLES',
  'RESULTS FILE FORMAT':'RESULTS_FILE_FORMAT',
  'RESULTS FILE':'RESULTS_FILE',
  'RESULT FILE IN LONGITUDE-LATITUDE':'RESULT_FILE_IN_LONGITUDE_LATITUDE',
  'BINARY RESULTS FILE FORMAT':'BINARY_RESULTS_FILE_FORMAT',
  'BINARY RESULTS FILE':'BINARY_RESULTS_FILE',
  'FORMATTED RESULTS FILE':'FORMATTED_RESULTS_FILE',
  'FORMATTED RESULTS FILE 1':'FORMATTED_RESULTS_FILE_1',
  'FORMATTED RESULTS FILE 2':'FORMATTED_RESULTS_FILE_2',
  'FORMATTED RESULTS FILE 3':'FORMATTED_RESULTS_FILE_3',
  'FORMATTED RESULTS FILE 4':'FORMATTED_RESULTS_FILE_4',
  'FORMATTED RESULTS FILE 5':'FORMATTED_RESULTS_FILE_5',
  'FORMATTED RESULTS FILE 6':'FORMATTED_RESULTS_FILE_6',
  'CONTROL SECTIONS':'CONTROL_SECTIONS',
  'PRINTING CUMULATED FLOWRATES':'PRINTING_CUMULATED_FLOWRATES',
  'COMPATIBLE COMPUTATION OF FLUXES':'COMPATIBLE_COMPUTATION_OF_FLUXES',
  'SECTIONS INPUT FILE':'SECTIONS_INPUT_FILE',
  'SECTIONS OUTPUT FILE':'SECTIONS_OUTPUT_FILE',
  'FLUXLINE':'FLUXLINE',
  'FLUXLINE INPUT FILE':'FLUXLINE_INPUT_FILE',
  'NUMBER OF FIRST TIME STEP FOR LISTING PRINTOUTS':'NUMBER_OF_FIRST_TIME_STEP_FOR_LISTING_PRINTOUTS',
  'LISTING PRINTOUT PERIOD':'LISTING_PRINTOUT_PERIOD',
  'LISTING FOR PRINTOUT PERIOD':'LISTING_FOR_PRINTOUT_PERIOD',
  'LISTING PRINTOUT':'LISTING_PRINTOUT',
  'VARIABLES TO BE PRINTED':'VARIABLES_TO_BE_PRINTED',
  'MASS-BALANCE':'MASS_BALANCE',
  'INFORMATION ABOUT SOLVER':'INFORMATION_ABOUT_SOLVER',
  'LIST OF POINTS':'LIST_OF_POINTS',
  'NAMES OF POINTS':'NAMES_OF_POINTS',
  'FOURIER ANALYSIS PERIODS':'FOURIER_ANALYSIS_PERIODS',
  'TIME RANGE FOR FOURIER ANALYSIS':'TIME_RANGE_FOR_FOURIER_ANALYSIS',
  'PRESCRIBED ELEVATIONS':'PRESCRIBED_ELEVATIONS',
  'PRESCRIBED FLOWRATES':'PRESCRIBED_FLOWRATES',
  'PRESCRIBED VELOCITIES':'PRESCRIBED_VELOCITIES',
  'STAGE-DISCHARGE CURVES':'STAGE_DISCHARGE_CURVES',
  'STAGE-DISCHARGE CURVES FILE':'STAGE_DISCHARGE_CURVES_FILE',
  'STAGE-DISCHARGE CURVES RELAXATION COEFFICIENT':'STAGE_DISCHARGE_CURVES_RELAXATION_COEFFICIENT',
  'VELOCITY PROFILES':'VELOCITY_PROFILES',
  'OPTION FOR LIQUID BOUNDARIES':'OPTION_FOR_LIQUID_BOUNDARIES',
  'LIQUID BOUNDARIES FILE':'LIQUID_BOUNDARIES_FILE',
  'ELEMENTS MASKED BY USER':'ELEMENTS_MASKED_BY_USER',
  'MAXIMUM NUMBER OF FRICTION DOMAINS':'MAXIMUM_NUMBER_OF_FRICTION_DOMAINS',
  'FRICTION DATA':'FRICTION_DATA',
  'FRICTION DATA FILE':'FRICTION_DATA_FILE',
  'LAW OF BOTTOM FRICTION':'LAW_OF_BOTTOM_FRICTION',
  'FRICTION COEFFICIENT':'FRICTION_COEFFICIENT',
  'MANNING DEFAULT VALUE FOR COLEBROOK-WHITE LAW':'MANNING_DEFAULT_VALUE_FOR_COLEBROOK_WHITE_LAW',
  'DEPTH IN FRICTION TERMS':'DEPTH_IN_FRICTION_TERMS',
  'VEGETATION FRICTION':'VEGETATION_FRICTION',
  'LAW OF FRICTION ON LATERAL BOUNDARIES':'LAW_OF_FRICTION_ON_LATERAL_BOUNDARIES',
  'ROUGHNESS COEFFICIENT OF BOUNDARIES':'ROUGHNESS_COEFFICIENT_OF_BOUNDARIES',
  'DEFINITION OF ZONES':'DEFINITION_OF_ZONES',
  'ZONES FILE':'ZONES_FILE',
  'NON-NEWTONIAN MODEL':'NON_NEWTONIAN_MODEL',
  'BINGHAM OPTION':'BINGHAM_OPTION',
  'NON-NEWTONIAN VISCOSITY':'NON_NEWTONIAN_VISCOSITY',
  'NON-NEWTONIAN YIELD STRESS':'NON_NEWTONIAN_YIELD_STRESS',
  'NON-NEWTONIAN LAMINAR RESISTANCE PARAMETER K':'NON_NEWTONIAN_LAMINAR_RESISTANCE_PARAMETER_K',
  'NON-NEWTONIAN FLUID DENSITY':'NON_NEWTONIAN_FLUID_DENSITY',
  'NON-NEWTONIAN PSEUDO-BIPHASIC MODEL':'NON_NEWTONIAN_PSEUDO_BIPHASIC_MODEL',
  'HERSCHEL-BULKLEY POWER-LAW INDEX':'HERSCHEL_BULKLEY_POWER_LAW_INDEX',
  'WIND':'WIND',
  'OPTION FOR WIND':'OPTION_FOR_WIND',
  'COEFFICIENT OF WIND INFLUENCE':'COEFFICIENT_OF_WIND_INFLUENCE',
  'COEFFICIENT OF WIND INFLUENCE VARYING WITH WIND SPEED':'COEFFICIENT_OF_WIND_INFLUENCE_VARYING_WITH_WIND_SPEED',
  'WIND VELOCITY ALONG X':'WIND_VELOCITY_ALONG_X',
  'WIND VELOCITY ALONG Y':'WIND_VELOCITY_ALONG_Y',
  'SPEED AND DIRECTION OF WIND':'SPEED_AND_DIRECTION_OF_WIND',
  'THRESHOLD DEPTH FOR WIND':'THRESHOLD_DEPTH_FOR_WIND',
  'AIR PRESSURE':'AIR_PRESSURE',
  'VALUE OF ATMOSPHERIC PRESSURE':'VALUE_OF_ATMOSPHERIC_PRESSURE',
  'RAIN OR EVAPORATION':'RAIN_OR_EVAPORATION',
  'RAIN OR EVAPORATION IN MM PER DAY':'RAIN_OR_EVAPORATION_IN_MM_PER_DAY',
  'RAINFALL-RUNOFF MODEL':'RAINFALL_RUNOFF_MODEL',
  'ANTECEDENT MOISTURE CONDITIONS':'ANTECEDENT_MOISTURE_CONDITIONS',
  'HORTON TIME CONSTANT':'HORTON_TIME_CONSTANT',
  'INITIAL WATER CONTENT':'INITIAL_WATER_CONTENT',
  'SATURATED WATER CONTENT':'SATURATED_WATER_CONTENT',
  'SUCTION':'SUCTION',
  'DURATION OF RAIN OR EVAPORATION IN HOURS':'DURATION_OF_RAIN_OR_EVAPORATION_IN_HOURS',
  'ASCII ATMOSPHERIC DATA FILE':'ASCII_ATMOSPHERIC_DATA_FILE',
  'BINARY ATMOSPHERIC DATA FILE':'BINARY_ATMOSPHERIC_DATA_FILE',
  'BINARY ATMOSPHERIC DATA FILE FORMAT':'BINARY_ATMOSPHERIC_DATA_FILE_FORMAT',
  'FREE FORMAT FOR ATMOSPHERIC DATA FILE':'FREE_FORMAT_FOR_ATMOSPHERIC_DATA_FILE',
  'OPTION FOR INITIAL ABSTRACTION RATIO':'OPTION_FOR_INITIAL_ABSTRACTION_RATIO',
  'AIR TEMPERATURE':'AIR_TEMPERATURE',
  'CLOUD COVER':'CLOUD_COVER',
  'SOLAR RADIATION':'SOLAR_RADIATION',
  'VAPOROUS PRESSURE':'VAPOROUS_PRESSURE',
  'WAVE DRIVEN CURRENTS':'WAVE_DRIVEN_CURRENTS',
  'RECORD NUMBER IN WAVE FILE':'RECORD_NUMBER_IN_WAVE_FILE',
  'WAVE ENHANCED FRICTION FACTOR':'WAVE_ENHANCED_FRICTION_FACTOR',
  'PARAMETER ESTIMATION':'PARAMETER_ESTIMATION',
  'COST FUNCTION':'COST_FUNCTION',
  'IDENTIFICATION METHOD':'IDENTIFICATION_METHOD',
  'TOLERANCES FOR IDENTIFICATION':'TOLERANCES_FOR_IDENTIFICATION',
  'MAXIMUM NUMBER OF ITERATIONS FOR IDENTIFICATION':'MAXIMUM_NUMBER_OF_ITERATIONS_FOR_IDENTIFICATION',
  'ABSCISSAE OF SOURCES':'ABSCISSAE_OF_SOURCES',
  'ORDINATES OF SOURCES':'ORDINATES_OF_SOURCES',
  'WATER DISCHARGE OF SOURCES':'WATER_DISCHARGE_OF_SOURCES',
  'VELOCITIES OF THE SOURCES ALONG X':'VELOCITIES_OF_THE_SOURCES_ALONG_X',
  'VELOCITIES OF THE SOURCES ALONG Y':'VELOCITIES_OF_THE_SOURCES_ALONG_Y',
  'TYPE OF SOURCES':'TYPE_OF_SOURCES',
  'SOURCES FILE':'SOURCES_FILE',
  'GLOBAL NUMBERS OF SOURCE NODES':'GLOBAL_NUMBERS_OF_SOURCE_NODES',
  'SOURCE REGIONS DATA FILE':'SOURCE_REGIONS_DATA_FILE',
  'MAXIMUM NUMBER OF POINTS FOR SOURCES REGIONS':'MAXIMUM_NUMBER_OF_POINTS_FOR_SOURCES_REGIONS',
  'WATER QUALITY PROCESS':'WATER_QUALITY_PROCESS',
  'WATER DENSITY':'WATER_DENSITY',
  'GRAVITY ACCELERATION':'GRAVITY_ACCELERATION',
  'VERTICAL STRUCTURES':'VERTICAL_STRUCTURES',
  'EQUATIONS':'EQUATIONS',
  'TREATMENT OF THE LINEAR SYSTEM':'TREATMENT_OF_THE_LINEAR_SYSTEM',
  'FINITE VOLUME SCHEME':'FINITE_VOLUME_SCHEME',
  'FINITE VOLUME SCHEME SPACE ORDER':'FINITE_VOLUME_SCHEME_SPACE_ORDER',
  'FINITE VOLUME SCHEME TIME ORDER':'FINITE_VOLUME_SCHEME_TIME_ORDER',
  'FLUX LIMITOR FOR H PLUS Z':'FLUX_LIMITOR_FOR_H_PLUS_Z',
  'FLUX LIMITOR FOR U AND V':'FLUX_LIMITOR_FOR_U_AND_V',
  'FLUX LIMITOR FOR TRACERS':'FLUX_LIMITOR_FOR_TRACERS',
  'TYPE OF BOUNDARY CONDITION FOR KINETIC SCHEME':'TYPE_OF_BOUNDARY_CONDITION_FOR_KINETIC_SCHEME',
  'CORIOLIS':'CORIOLIS',
  'CORIOLIS COEFFICIENT':'CORIOLIS_COEFFICIENT',
  'OPTION FOR TSUNAMI GENERATION':'OPTION_FOR_TSUNAMI_GENERATION',
  'PHYSICAL CHARACTERISTICS OF THE TSUNAMI':'PHYSICAL_CHARACTERISTICS_OF_THE_TSUNAMI',
  'SECONDARY CURRENTS':'SECONDARY_CURRENTS',
  'PRODUCTION COEFFICIENT FOR SECONDARY CURRENTS':'PRODUCTION_COEFFICIENT_FOR_SECONDARY_CURRENTS',
  'DISSIPATION COEFFICIENT FOR SECONDARY CURRENTS':'DISSIPATION_COEFFICIENT_FOR_SECONDARY_CURRENTS',
  'DEBUGGER':'DEBUGGER',
  'TIME STEP':'TIME_STEP',
  'NUMBER OF TIME STEPS':'NUMBER_OF_TIME_STEPS',
  'DURATION':'DURATION',
  'ORIGINAL DATE OF TIME':'ORIGINAL_DATE_OF_TIME',
  'ORIGINAL HOUR OF TIME':'ORIGINAL_HOUR_OF_TIME',
  'STOP IF A STEADY STATE IS REACHED':'STOP_IF_A_STEADY_STATE_IS_REACHED',
  'STOP CRITERIA':'STOP_CRITERIA',
  'CONTROL OF LIMITS':'CONTROL_OF_LIMITS',
  'LIMIT VALUES':'LIMIT_VALUES',
  'VARIABLE TIME-STEP':'VARIABLE_TIME_STEP',
  'DESIRED COURANT NUMBER':'DESIRED_COURANT_NUMBER',
  'DESIRED FOURIER NUMBER':'DESIRED_FOURIER_NUMBER',
  'SPHERICAL COORDINATES':'SPHERICAL_COORDINATES',
  'LATITUDE OF ORIGIN POINT':'LATITUDE_OF_ORIGIN_POINT',
  'LONGITUDE OF ORIGIN POINT':'LONGITUDE_OF_ORIGIN_POINT',
  'NORTH':'NORTH',
  'SPATIAL PROJECTION TYPE':'SPATIAL_PROJECTION_TYPE',
  'SOLVER':'SOLVER',
  'SOLVER OPTION':'SOLVER_OPTION',
  'SOLVER ACCURACY':'SOLVER_ACCURACY',
  'MAXIMUM NUMBER OF ITERATIONS FOR SOLVER':'MAXIMUM_NUMBER_OF_ITERATIONS_FOR_SOLVER',
  'CONTINUITY CORRECTION':'CONTINUITY_CORRECTION',
  'PRECONDITIONING':'PRECONDITIONING',
  'C-U PRECONDITIONING':'C_U_PRECONDITIONING',
  'FINITE ELEMENT ASSEMBLY':'FINITE_ELEMENT_ASSEMBLY',
  'IMPLICITATION FOR DEPTH':'IMPLICITATION_FOR_DEPTH',
  'IMPLICITATION FOR VELOCITY':'IMPLICITATION_FOR_VELOCITY',
  'DISCRETIZATIONS IN SPACE':'DISCRETIZATIONS_IN_SPACE',
  'PROPAGATION':'PROPAGATION',
  'INITIAL GUESS FOR H':'INITIAL_GUESS_FOR_H',
  'LINEARIZED PROPAGATION':'LINEARIZED_PROPAGATION',
  'INITIAL GUESS FOR U':'INITIAL_GUESS_FOR_U',
  'MEAN DEPTH FOR LINEARIZATION':'MEAN_DEPTH_FOR_LINEARIZATION',
  'ADVECTION':'ADVECTION',
  'ADVECTION OF H':'ADVECTION_OF_H',
  'ADVECTION OF U AND V':'ADVECTION_OF_U_AND_V',
  'TYPE OF ADVECTION':'TYPE_OF_ADVECTION',
  'OPTION FOR CHARACTERISTICS':'OPTION_FOR_CHARACTERISTICS',
  'SUPG OPTION':'SUPG_OPTION',
  'NUMBER OF GAUSS POINTS FOR WEAK CHARACTERISTICS':'NUMBER_OF_GAUSS_POINTS_FOR_WEAK_CHARACTERISTICS',
  'MASS-LUMPING FOR WEAK CHARACTERISTICS':'MASS_LUMPING_FOR_WEAK_CHARACTERISTICS',
  'MAXIMUM NUMBER OF ITERATIONS FOR ADVECTION SCHEMES':'MAXIMUM_NUMBER_OF_ITERATIONS_FOR_ADVECTION_SCHEMES',
  'MASS-LUMPING ON H':'MASS_LUMPING_ON_H',
  'MASS-LUMPING ON VELOCITY':'MASS_LUMPING_ON_VELOCITY',
  'SCHEME FOR ADVECTION OF VELOCITIES':'SCHEME_FOR_ADVECTION_OF_VELOCITIES',
  'SCHEME OPTION FOR ADVECTION OF VELOCITIES':'SCHEME_OPTION_FOR_ADVECTION_OF_VELOCITIES',
  'FREE SURFACE GRADIENT COMPATIBILITY':'FREE_SURFACE_GRADIENT_COMPATIBILITY',
  'NUMBER OF SUB-ITERATIONS FOR NON-LINEARITIES':'NUMBER_OF_SUB_ITERATIONS_FOR_NON_LINEARITIES',
  'TREATMENT OF FLUXES AT THE BOUNDARIES':'TREATMENT_OF_FLUXES_AT_THE_BOUNDARIES',
  'NUMBER OF CORRECTIONS OF DISTRIBUTIVE SCHEMES':'NUMBER_OF_CORRECTIONS_OF_DISTRIBUTIVE_SCHEMES',
  'NUMBER OF SUB-STEPS OF DISTRIBUTIVE SCHEMES':'NUMBER_OF_SUB_STEPS_OF_DISTRIBUTIVE_SCHEMES',
  'DIFFUSION OF VELOCITY':'DIFFUSION_OF_VELOCITY',
  'OPTION FOR THE DIFFUSION OF VELOCITIES':'OPTION_FOR_THE_DIFFUSION_OF_VELOCITIES',
  'IMPLICITATION FOR DIFFUSION OF VELOCITY':'IMPLICITATION_FOR_DIFFUSION_OF_VELOCITY',
  'FINITE VOLUME SCHEME FOR VELOCITY DIFFUSION':'FINITE_VOLUME_SCHEME_FOR_VELOCITY_DIFFUSION',
  'FINITE VOLUME SCHEME FOR TRACER DIFFUSION':'FINITE_VOLUME_SCHEME_FOR_TRACER_DIFFUSION',
  'OPTION FOR THE RTPF SCHEME RECONSTRUCTIONS':'OPTION_FOR_THE_RTPF_SCHEME_RECONSTRUCTIONS',
  'OPTION FOR DIRICHLET CONDITION IN FV DIFFUSION':'OPTION_FOR_DIRICHLET_CONDITION_IN_FV_DIFFUSION',
  'AD NUMBER OF DERIVATIVES':'AD_NUMBER_OF_DERIVATIVES',
  'AD NAMES OF DERIVATIVES':'AD_NAMES_OF_DERIVATIVES',
  'AD SYMBOLIC LINEAR SOLVER':'AD_SYMBOLIC_LINEAR_SOLVER',
  'AD LINEAR SOLVER RESET DERIVATIVES':'AD_LINEAR_SOLVER_RESET_DERIVATIVES',
  'AD LINEAR SOLVER DERIVATIVE CONVERGENCE':'AD_LINEAR_SOLVER_DERIVATIVE_CONVERGENCE',
  'MATRIX STORAGE':'MATRIX_STORAGE',
  'MATRIX-VECTOR PRODUCT':'MATRIX_VECTOR_PRODUCT',
  'NEWMARK TIME INTEGRATION COEFFICIENT':'NEWMARK_TIME_INTEGRATION_COEFFICIENT',
  'ZERO':'ZERO',
  'OPTION OF THE HYDROSTATIC RECONSTRUCTION':'OPTION_OF_THE_HYDROSTATIC_RECONSTRUCTION',
  'CONVERGENCE STUDY':'CONVERGENCE_STUDY',
  'REFINEMENT LEVELS':'REFINEMENT_LEVELS',
  'VELOCITY DIFFUSIVITY':'VELOCITY_DIFFUSIVITY',
  'TURBULENCE MODEL':'TURBULENCE_MODEL',
  'ACCURACY OF SPALART-ALLMARAS':'ACCURACY_OF_SPALART_ALLMARAS',
  'INFORMATION ABOUT SPALART-ALLMARAS MODEL':'INFORMATION_ABOUT_SPALART_ALLMARAS_MODEL',
  'SOLVER FOR K-EPSILON MODEL':'SOLVER_FOR_K_EPSILON_MODEL',
  'OPTION FOR THE SOLVER FOR K-EPSILON MODEL':'OPTION_FOR_THE_SOLVER_FOR_K_EPSILON_MODEL',
  'PRECONDITIONING FOR K-EPSILON MODEL':'PRECONDITIONING_FOR_K_EPSILON_MODEL',
  'NON-DIMENSIONAL DISPERSION COEFFICIENTS':'NON_DIMENSIONAL_DISPERSION_COEFFICIENTS',
  'TURBULENCE REGIME FOR SOLID BOUNDARIES':'TURBULENCE_REGIME_FOR_SOLID_BOUNDARIES',
  'INFORMATION ABOUT K-EPSILON MODEL':'INFORMATION_ABOUT_K_EPSILON_MODEL',
  'ADVECTION OF K AND EPSILON':'ADVECTION_OF_K_AND_EPSILON',
  'SCHEME FOR ADVECTION OF K-EPSILON':'SCHEME_FOR_ADVECTION_OF_K_EPSILON',
  'SCHEME OPTION FOR ADVECTION OF K-EPSILON':'SCHEME_OPTION_FOR_ADVECTION_OF_K_EPSILON',
  'MIXING LENGTH MODEL COEFFICIENTS':'MIXING_LENGTH_MODEL_COEFFICIENTS',
  'ACCURACY OF K':'ACCURACY_OF_K',
  'ACCURACY OF EPSILON':'ACCURACY_OF_EPSILON',
  'MAXIMUM NUMBER OF ITERATIONS FOR K AND EPSILON':'MAXIMUM_NUMBER_OF_ITERATIONS_FOR_K_AND_EPSILON',
  'TIDAL FLATS':'TIDAL_FLATS',
  'OPTION FOR THE TREATMENT OF TIDAL FLATS':'OPTION_FOR_THE_TREATMENT_OF_TIDAL_FLATS',
  'TREATMENT OF NEGATIVE DEPTHS':'TREATMENT_OF_NEGATIVE_DEPTHS',
  'THRESHOLD FOR NEGATIVE DEPTHS':'THRESHOLD_FOR_NEGATIVE_DEPTHS',
  'THRESHOLD DEPTH FOR RECEDING PROCEDURE':'THRESHOLD_DEPTH_FOR_RECEDING_PROCEDURE',
  'H CLIPPING':'H_CLIPPING',
  'MINIMUM VALUE OF DEPTH':'MINIMUM_VALUE_OF_DEPTH',
  'PRESCRIBED TRACERS VALUES':'PRESCRIBED_TRACERS_VALUES',
  'NUMBER OF TRACERS':'NUMBER_OF_TRACERS',
  'NAMES OF TRACERS':'NAMES_OF_TRACERS',
  'INITIAL VALUES OF TRACERS':'INITIAL_VALUES_OF_TRACERS',
  'DENSITY EFFECTS':'DENSITY_EFFECTS',
  'MEAN TEMPERATURE':'MEAN_TEMPERATURE',
  'SOLVER FOR DIFFUSION OF TRACERS':'SOLVER_FOR_DIFFUSION_OF_TRACERS',
  'SOLVER OPTION FOR TRACERS DIFFUSION':'SOLVER_OPTION_FOR_TRACERS_DIFFUSION',
  'PRECONDITIONING FOR DIFFUSION OF TRACERS':'PRECONDITIONING_FOR_DIFFUSION_OF_TRACERS',
  'ACCURACY FOR DIFFUSION OF TRACERS':'ACCURACY_FOR_DIFFUSION_OF_TRACERS',
  'MAXIMUM NUMBER OF ITERATIONS FOR DIFFUSION OF TRACERS':'MAXIMUM_NUMBER_OF_ITERATIONS_FOR_DIFFUSION_OF_TRACERS',
  'VALUES OF THE TRACERS AT THE SOURCES':'VALUES_OF_THE_TRACERS_AT_THE_SOURCES',
  'VALUES OF TRACERS IN THE RAIN':'VALUES_OF_TRACERS_IN_THE_RAIN',
  'ADVECTION OF TRACERS':'ADVECTION_OF_TRACERS',
  'IMPLICITATION COEFFICIENT OF TRACERS':'IMPLICITATION_COEFFICIENT_OF_TRACERS',
  'DIFFUSION OF TRACERS':'DIFFUSION_OF_TRACERS',
  'COEFFICIENT FOR DIFFUSION OF TRACERS':'COEFFICIENT_FOR_DIFFUSION_OF_TRACERS',
  'OPTION FOR THE DIFFUSION OF TRACERS':'OPTION_FOR_THE_DIFFUSION_OF_TRACERS',
  'SCHEME FOR ADVECTION OF TRACERS':'SCHEME_FOR_ADVECTION_OF_TRACERS',
  'SCHEME OPTION FOR ADVECTION OF TRACERS':'SCHEME_OPTION_FOR_ADVECTION_OF_TRACERS',
  'MASS-LUMPING ON TRACERS':'MASS_LUMPING_ON_TRACERS',
  'MAXIMUM NUMBER OF DROGUES':'MAXIMUM_NUMBER_OF_DROGUES',
  'INITIAL DROGUES SAMPLING DENSITY':'INITIAL_DROGUES_SAMPLING_DENSITY',
  'PRINTOUT PERIOD FOR DROGUES':'PRINTOUT_PERIOD_FOR_DROGUES',
  'ASCII DROGUES FILE':'ASCII_DROGUES_FILE',
  'BINARY DROGUES FILE':'BINARY_DROGUES_FILE',
  'DROGUES FILE FORMAT':'DROGUES_FILE_FORMAT',
  'PREVIOUS DROGUES FILE':'PREVIOUS_DROGUES_FILE',
  'PREVIOUS DROGUES FILE FORMAT':'PREVIOUS_DROGUES_FILE_FORMAT',
  'DROGUES INITIAL POSITIONING DATA FILE':'DROGUES_INITIAL_POSITIONING_DATA_FILE',
  'FORMAT OF THE DROGUES POSITIONING DATA FILE':'FORMAT_OF_THE_DROGUES_POSITIONING_DATA_FILE',
  'ALGAE TRANSPORT MODEL':'ALGAE_TRANSPORT_MODEL',
  'NUMBER OF ALGAE CLASSES':'NUMBER_OF_ALGAE_CLASSES',
  'ALGAE TYPE':'ALGAE_TYPE',
  'DIAMETER OF ALGAE':'DIAMETER_OF_ALGAE',
  'DURATION BEFORE ALGAE RELEASE':'DURATION_BEFORE_ALGAE_RELEASE',
  'DENSITY OF ALGAE':'DENSITY_OF_ALGAE',
  'THICKNESS OF ALGAE':'THICKNESS_OF_ALGAE',
  'ALGAE RELEASE TYPE':'ALGAE_RELEASE_TYPE',
  'WAVE ORBITAL VELOCITY THRESHOLD FOR ALGAE 1':'WAVE_ORBITAL_VELOCITY_THRESHOLD_FOR_ALGAE_1',
  'WAVE ORBITAL VELOCITY THRESHOLD FOR ALGAE 2':'WAVE_ORBITAL_VELOCITY_THRESHOLD_FOR_ALGAE_2',
  'RATE OF DEGRADATION FOR ALGAE':'RATE_OF_DEGRADATION_FOR_ALGAE',
  'OIL SPILL MODEL':'OIL_SPILL_MODEL',
  'OIL SPILL STEERING FILE':'OIL_SPILL_STEERING_FILE',
  'STOCHASTIC DIFFUSION MODEL':'STOCHASTIC_DIFFUSION_MODEL',
  'NUMBER OF LAGRANGIAN DRIFTS':'NUMBER_OF_LAGRANGIAN_DRIFTS',
  'NUMBER OF WEIRS':'NUMBER_OF_WEIRS',
  'WEIRS DATA FILE':'WEIRS_DATA_FILE',
  'TYPE OF WEIRS':'TYPE_OF_WEIRS',
  'WEIRS DISCHARGE OUTPUT FILE':'WEIRS_DISCHARGE_OUTPUT_FILE',
  'NUMBER OF CULVERTS':'NUMBER_OF_CULVERTS',
  'CULVERTS DATA FILE':'CULVERTS_DATA_FILE',
  'OPTION FOR CULVERTS':'OPTION_FOR_CULVERTS',
  'BREACH':'BREACH',
  'BREACHES DATA FILE':'BREACHES_DATA_FILE',
  'INITIAL WIDTHS OF BREACHES':'INITIAL_WIDTHS_OF_BREACHES',
  'BINARY DATABASE 1 FOR TIDE':'BINARY_DATABASE_1_FOR_TIDE',
  'BINARY DATABASE 2 FOR TIDE':'BINARY_DATABASE_2_FOR_TIDE',
  'GEOGRAPHIC SYSTEM':'GEOGRAPHIC_SYSTEM',
  'ZONE NUMBER IN GEOGRAPHIC SYSTEM':'ZONE_NUMBER_IN_GEOGRAPHIC_SYSTEM',
  'LAMBERT 93 CONVERSION FILE':'LAMBERT_93_CONVERSION_FILE',
  'COEFFICIENT TO CALIBRATE SEA LEVEL':'COEFFICIENT_TO_CALIBRATE_SEA_LEVEL',
  'GLOBAL NUMBER OF THE POINT TO CALIBRATE HIGH WATER':'GLOBAL_NUMBER_OF_THE_POINT_TO_CALIBRATE_HIGH_WATER',
  'MINOR CONSTITUENTS INFERENCE':'MINOR_CONSTITUENTS_INFERENCE',
  'INITIAL VELOCITIES COMPUTED BY TPXO':'INITIAL_VELOCITIES_COMPUTED_BY_TPXO',
  'MINIMUM DEPTH TO COMPUTE TIDAL VELOCITIES INITIAL CONDITIONS':'MINIMUM_DEPTH_TO_COMPUTE_TIDAL_VELOCITIES_INITIAL_CONDITIONS',
  'OPTION FOR TIDAL BOUNDARY CONDITIONS':'OPTION_FOR_TIDAL_BOUNDARY_CONDITIONS',
  'TIDAL DATA BASE':'TIDAL_DATA_BASE',
  'HARMONIC CONSTANTS FILE':'HARMONIC_CONSTANTS_FILE',
  'TIDAL MODEL FILE':'TIDAL_MODEL_FILE',
  'TIDAL MODEL FILE FORMAT':'TIDAL_MODEL_FILE_FORMAT',
  'ASCII DATABASE FOR TIDE':'ASCII_DATABASE_FOR_TIDE',
  'COEFFICIENT TO CALIBRATE TIDAL RANGE':'COEFFICIENT_TO_CALIBRATE_TIDAL_RANGE',
  'COEFFICIENT TO CALIBRATE TIDAL VELOCITIES':'COEFFICIENT_TO_CALIBRATE_TIDAL_VELOCITIES',
  'LOCAL NUMBER OF THE POINT TO CALIBRATE HIGH WATER':'LOCAL_NUMBER_OF_THE_POINT_TO_CALIBRATE_HIGH_WATER',
  'MINIMUM DEPTH TO COMPUTE TIDAL VELOCITIES BOUNDARY CONDITIONS':'MINIMUM_DEPTH_TO_COMPUTE_TIDAL_VELOCITIES_BOUNDARY_CONDITIONS',
  'TIDE GENERATING FORCE':'TIDE_GENERATING_FORCE',
  'COUPLING WITH':'COUPLING_WITH',
  'NAMES OF CLANDESTINE VARIABLES':'NAMES_OF_CLANDESTINE_VARIABLES',
  'DELWAQ STEERING FILE':'DELWAQ_STEERING_FILE',
  'DELWAQ PRINTOUT PERIOD':'DELWAQ_PRINTOUT_PERIOD',
  'EXCHANGES BETWEEN NODES DELWAQ FILE':'EXCHANGES_BETWEEN_NODES_DELWAQ_FILE',
  'NODES DISTANCES DELWAQ FILE':'NODES_DISTANCES_DELWAQ_FILE',
  'BOTTOM SURFACES DELWAQ FILE':'BOTTOM_SURFACES_DELWAQ_FILE',
  'VOLUMES DELWAQ FILE':'VOLUMES_DELWAQ_FILE',
  'EXCHANGE AREAS DELWAQ FILE':'EXCHANGE_AREAS_DELWAQ_FILE',
  'VERTICAL FLUXES DELWAQ FILE':'VERTICAL_FLUXES_DELWAQ_FILE',
  'VELOCITY DELWAQ FILE':'VELOCITY_DELWAQ_FILE',
  'DIFFUSIVITY DELWAQ FILE':'DIFFUSIVITY_DELWAQ_FILE',
  'TEMPERATURE DELWAQ FILE':'TEMPERATURE_DELWAQ_FILE',
  'SALINITY DELWAQ FILE':'SALINITY_DELWAQ_FILE',
  'VELOCITY FOR DELWAQ':'VELOCITY_FOR_DELWAQ',
  'DIFFUSIVITY FOR DELWAQ':'DIFFUSIVITY_FOR_DELWAQ',
  'TEMPERATURE FOR DELWAQ':'TEMPERATURE_FOR_DELWAQ',
  'SALINITY FOR DELWAQ':'SALINITY_FOR_DELWAQ',
  'SISYPHE STEERING FILE':'SISYPHE_STEERING_FILE',
  'COUPLING PERIOD FOR SISYPHE':'COUPLING_PERIOD_FOR_SISYPHE',
  'GAIA STEERING FILE':'GAIA_STEERING_FILE',
  'TOMAWAC STEERING FILE':'TOMAWAC_STEERING_FILE',
  'COUPLING PERIOD FOR TOMAWAC':'COUPLING_PERIOD_FOR_TOMAWAC',
  'WAQTEL STEERING FILE':'WAQTEL_STEERING_FILE',
  'KHIONE STEERING FILE':'KHIONE_STEERING_FILE',
  'NESTOR':'NESTOR',
  'NESTOR ACTION FILE':'NESTOR_ACTION_FILE',
  'NESTOR POLYGON FILE':'NESTOR_POLYGON_FILE',
  'NESTOR SURFACE REFERENCE FILE':'NESTOR_SURFACE_REFERENCE_FILE',
  'NESTOR RESTART FILE':'NESTOR_RESTART_FILE',
  'LANGUAGE':'LANGUAGE',
  'STEERING FILE':'STEERING_FILE',
  'DICTIONARY':'DICTIONARY',
  'PARTITIONING TOOL':'PARTITIONING_TOOL',
  'CONCATENATE PARTEL OUTPUT':'CONCATENATE_PARTEL_OUTPUT',
}
DicoEnumCasFrToEnumCasEn = {
'INITIAL_CONDITIONS':{
  "COTE NULLE":"ZERO ELEVATION",
  "COTE CONSTANTE":"CONSTANT ELEVATION",
  "HAUTEUR NULLE":"ZERO DEPTH",
  "HAUTEUR CONSTANTE":"CONSTANT DEPTH",
  "SPECIAL":"SPECIAL",
  "PARTICULIERES":"PARTICULIERES",
  "PARTICULAR":"PARTICULAR",
  "ALTIMETRIE SATELLITE TPXO":"TPXO SATELLITE ALTIMETRY",
},

'BINARY_DATA_FILE_1_FORMAT':{
  "BIN":"BIN",
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'BINARY_DATA_FILE_2_FORMAT':{
  "BIN":"BIN",
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'GEOMETRY_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'REFERENCE_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'PREVIOUS_COMPUTATION_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'RESTART_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'RESULTS_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'BINARY_RESULTS_FILE_FORMAT':{
  "BIN":"BIN",
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'BINARY_ATMOSPHERIC_DATA_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'PARAMETER_ESTIMATION':{
  "":"",
  "FROTTEMENT":"FRICTION",
  "FROTTEMENT, PERMANENT":"FRICTION, STEADY",
},

'EQUATIONS':{
  "SAINT-VENANT EF":"SAINT-VENANT FE",
  "SAINT-VENANT VF":"SAINT-VENANT FV",
  "BOUSSINESQ":"BOUSSINESQ",
},

'DROGUES_FILE_FORMAT':{
  "BKBINPCL":"BKBINPCL",
  "TECPLOT":"TECPLOT",
},

'PREVIOUS_DROGUES_FILE_FORMAT':{
  "BKBINPCL":"BKBINPCL",
  "BKASCPCL":"BKASCPCL",
},

'FORMAT_OF_THE_DROGUES_POSITIONING_DATA_FILE':{
  "BKASCI2S":"BKASCI2S",
},

'TIDAL_MODEL_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'COUPLING_WITH':{
  "SISYPHE":"SISYPHE",
  "TOMAWAC":"TOMAWAC",
  "TOMAWAC2":"TOMAWAC2",
  "WAQTEL":"WAQTEL",
  "KHIONE":"KHIONE",
  "GAIA":"GAIA",
  "DELWAQ":"DELWAQ",
  "":"",
},

'PARTITIONING_TOOL':{
  "METIS":"METIS",
  "SCOTCH":"SCOTCH",
  "PARMETIS":"PARMETIS",
  "PTSCOTCH":"PTSCOTCH",
},

}
