/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog3Manager = BADDIALOGID;
LgIndex_t TelemacFiles_LBL_D3 = BADDIALOGID;
LgIndex_t TF3_LBL_D3 = BADDIALOGID;
LgIndex_t BrowsTel_BTN_D3 = BADDIALOGID;
LgIndex_t BrowseDel_BTN_D3 = BADDIALOGID;
LgIndex_t FTelList_T_D3 = BADDIALOGID;
LgIndex_t FDelList_T_D3 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t DataSetLoa_RADIO_D2 = BADDIALOGID;
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t FileLoadMo_RADIO_D1 = BADDIALOGID;
