!                 **************************
                  MODULE DECLARATIONS_KHIONE
!                 **************************
!
!***********************************************************************
! KHIONE   V8P0                                              02/11/2016
!***********************************************************************
!
!brief    DECLARATION OF PRINCIPAL KHIONE VARIABLES
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF_DEF
!
!       NOTE: THIS MODULE IS ORGANIZED IN 6 PARTS
!
!       (1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (2) INTEGERS
!       (3) LOGICAL VALUES
!       (4) REALS
!       (5) STRINGS
!       (6) ALIASES (IF NECESSARY)
!
!
!=======================================================================
!
!  STRUCTURE USED FOR WRITTING OUT THE TIME SERIES FILE
!
!-----------------------------------------------------------------------
!
      TYPE STR_CELL_TYPE
        INTEGER :: NVAL
        CHARACTER(LEN=24), ALLOCATABLE :: TXT(:)
        CHARACTER(LEN=24), ALLOCATABLE :: UNT(:)
        CHARACTER(LEN=24), ALLOCATABLE :: VAL(:)
      END TYPE STR_CELL_TYPE
!
      TYPE STR_LINE_TYPE
        INTEGER :: NVAL
        CHARACTER(LEN=24) :: HTXT
        CHARACTER(LEN=24) :: HUNT
        CHARACTER(LEN=24) :: HVAL
        TYPE (STR_CELL_TYPE), ALLOCATABLE :: CELLS(:)
      END TYPE STR_LINE_TYPE
!
!=======================================================================
!
!       0) PARAMETERS
!
!-----------------------------------------------------------------------
!
!     MAXIMUM NUMBER OF VALUES OF KEY-WORDS OF ONE KIND
!       (INTEGER, LOGICAL, ETC.)
!
      INTEGER, PARAMETER :: MAXKEY = 300
!
!
!=======================================================================
!
!       1) OUTPUTS
!
!-----------------------------------------------------------------------
!
!     VARIABLES FOR GRAPHIC PRINTOUT
!
      CHARACTER(LEN=72) VARDES,VARIMP,VARD3D
!
!     GRAPHIC PRINTOUT PERIOD KHIONE
!
      INTEGER LEOPRD
!
!     LISTING PRINTOUT PERIOD KHIONE
!
      INTEGER LISPRD
!     MAXIMUM NUMBER OF OUTPUT VARIABLES
!
      INTEGER, PARAMETER :: MAXVAR = 100
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
      LOGICAL SORLEO(MAXVAR),SORIMP(MAXVAR)
      LOGICAL SORIMP3(MAXVAR),SORLEO3(MAXVAR)
!
!     BLOCK OF VARIABLES FOR OUTPUT
!
      TYPE(BIEF_OBJ), TARGET :: VARSOR
!
!     BLOCK OF VARIABLES FOR OUTPUT
!
      TYPE(BIEF_OBJ), TARGET :: VARSO3
!
!     NAMES AND UNITS OF VARIABLES
!       ( THESE TWO ARE SET IN LECDON_, THROUGH A CALL TO NOMVAR_ )
      CHARACTER(LEN=32) TEXTE(MAXVAR),TEXTPR(MAXVAR)
!
!     NAMES AND UNITS OF VARIABLES
!       ( THESE TWO ARE SET IN LECDON_, THROUGH A CALL TO NOMVAR_ )
      CHARACTER(LEN=32) TEXTE3(MAXVAR),TEXTPR3(MAXVAR)
!
!     VARSOR FILTER FOR CONTINUED COMPUTATION
!
      INTEGER :: ALIRE(MAXVAR)
!     BE ABSOLUTLY SURE THAT ALIRE IS SIZE MAXVAR
      PARAMETER ( ALIRE = (/
!         1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,
     &    0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,
     &    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
     &    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
     &    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) )
!
!     TITLE OF STUDY
!
      CHARACTER(LEN=72) TITICECAS
!
!     FOR TIME SERIES OUTPUT
!
      TYPE (STR_LINE_TYPE) :: LINES
!
!=======================================================================
!
!      2) FILES
!
!-----------------------------------------------------------------------
!
!
!     MAXIMUM RANK OF LOGICAL UNITS (OPENING FILES) AS DECLARED IN
!     SUBMIT STRINGS IN THE DICTIONARY
!
      INTEGER, PARAMETER :: MAXLU_ICE = 14
!
!     TELEMAC-2D FILES
!
      TYPE(BIEF_FILE) :: ICE_FILES(MAXLU_ICE)
!
!     KHIONE RESULT FILE NUMBER
!
      INTEGER ICERES,ICER3D
!
!     KHIONE BOUNDARY CONDIITON FILE NUMBER
!
      INTEGER ICECLI
!
!     KHIONE GEOMETRY FILE NUMBER
!
      INTEGER ICEGEO
!
!     KHIONE STEERING FILE NUMBER
!
      INTEGER ICECAS
!
!     KHIONE REFERENCE FILE NUMBER
!
      INTEGER ICEREF
!
!     KHIONE PREVIOUS ICE COVER FILE NUMBER (EULERIAN)
!
      INTEGER ICECOV
!
!     KHIONE PREVIOUS ICE PACKS FILE NUMBER (LAGRANGIAN)
!
      INTEGER ICEBLK
!
!     KHIONE CLOGGING ICE RESULTS FILE NUMBER
!
      INTEGER CLGRFO
!
!=======================================================================
!
!      3) DICTIONARY
!
!-----------------------------------------------------------------------
!
!     COPY OF SUBMIT STRINGS IN THE DICTIONARY
!
      CHARACTER(LEN=PATH_LEN) SUBMIT(4,300)
!
!
!=======================================================================
!
!       4) ALGORITHMIC DIFFERENTIATION
!
!-----------------------------------------------------------------------
!
!
!     NUMBER OF DIFFERENTIATING ARRAYS, AND THOSE WITH A GIVEN NAME
!
      INTEGER NADVAR,N_NAMES_ADVAR
!
!     NAMES OF DIFFERENTING ARRAYS (GIVEN BY USER)
!
      CHARACTER(LEN=32) NAMES_ADVAR(MAXVAR)
!
!     BLOCK OF DIFFERENTIATED VECTORS
!
      TYPE(BIEF_OBJ), TARGET :: ADVAR
!
!
!=======================================================================
!
!       5) SWITCHES AND OPTIONS
!
!-----------------------------------------------------------------------
!
!     NUMBER OF DIFFERENTIATING ARRAYS, AND THOSE WITH A GIVEN NAME
!
      INTEGER NICVAR,N_NAMES_ICVAR
!
!     DEBUGGER
      INTEGER DEBUG
!
!     FRAZIL CONCENTRATION
      INTEGER IND_FRA
!
!     WATER TEMPERATURE (DUPLICATED INDEX)
      INTEGER IND_T
!
!     SALINITY (DUPLICATED INDEX)
      INTEGER IND_S
!
!     DYNAMIC ICE COVER (DUPLICATED INDEX)
      INTEGER IND_DCI,IND_DTI
!
!=======================================================================
!
!       1) HEAT FLUXES
!
!-----------------------------------------------------------------------
!
!     THERMAL BUDGET: NET SUM OF THERMAL FLUXES BETWEEN ATMO AND WATER
      TYPE(BIEF_OBJ), TARGET :: SUMPH
!
!     THERMAL BUDGET: NET SUM OF THERMAL FLUXES BETWEEN ATMO AND ICE
      TYPE(BIEF_OBJ), TARGET :: SUMPH_ICE
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLEAR SKY
      TYPE(BIEF_OBJ), TARGET :: PHCL
!
!     THERMAL BUDGET: SOLAR RADIATION UNDER CLOUDY SKY
      TYPE(BIEF_OBJ), TARGET :: PHRI
!
!     THERMAL BUDGET: NET SOLAR RADIATION AFTER REFLECTION
      TYPE(BIEF_OBJ), TARGET :: PHPS
!
!     THERMAL BUDGET: EFFECTIVE BACK RADIATION
      TYPE(BIEF_OBJ), TARGET :: PHIB
!
!     THERMAL BUDGET: EVAPORATION HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIE
!
!     THERMAL BUDGET: CONDUCTIVITY HEAT FLUX
      TYPE(BIEF_OBJ), TARGET :: PHIH
!
!     THERMAL BUDGET: PRECIPITATION
      TYPE(BIEF_OBJ), TARGET :: PHIP
!
!     THERMAL BUDGET: HEAT TRANSFER BETWEEN WATER AND ICE
      TYPE(BIEF_OBJ), TARGET :: PHIW
!
!     WATER TEMPERATURE
!      TYPE(BIEF_OBJ), TARGET :: TW
!
!     HEAT TRANSFER COEFFICIENT BETWEEN SURFACE ICE AND WATER
      TYPE(BIEF_OBJ), TARGET :: HWI
!      DOUBLE PRECISION HWIN
!
!
!
!=======================================================================
!
!       2) PHYSICAL PROPERTIES AND CONSTANTS
!
!-----------------------------------------------------------------------
!
!     ICE EXPANDS UPON FREEZING, WHICH IS THE OPPOSITE OF MOST OTHER
!       SUBSTANCES. AT 0[oC] IT HAS A DENSITY OF 916.8[kg/m3] AS
!       COMPARED TO A DENSITY OF 999.8[kg/m3] FOR WATER AT THE SAME
!       TEMPERATURE. AS A RESULT, ICE FLOATS IN WATER.
!     NOTE: THE MAXIMUM WATER DENSITY IS 1000[kg/m3] AT 4[oC]
!
!     ICE DENSITY ( DEFAULT = 916.8 kg/m3 )
      DOUBLE PRECISION  RHO_ICE
!
!     AIR DENSITY ( DEFAULT = 1.225 kg/m3 )
      DOUBLE PRECISION  RHO_AIR
!
!     WATER DENSITY
      DOUBLE PRECISION  RO0
!
!     SPECIFIC HEAT OF WATER (DEFAULT = 4.1855 kJ/kgK )
      DOUBLE PRECISION  CP_EAU
!
!     SPECIFIC HEAT OF ICE (DEFAULT = 2.04 kJ/kgK )
      DOUBLE PRECISION  CP_ICE
!
!     LATENT HEAT OF FREEZING (DEFAULT = 334. kJ/kgK )
      DOUBLE PRECISION  LH_ICE
!
!     CONSTANT, COEFFICIENT FOR LINEARIZED HEAT FLUX EXCHANGES
!     .. BETWEEN WATER AND AIR
      DOUBLE PRECISION  CST_WATAIR,LIN_WATAIR
!
!     .. BETWEEN ICE AND AIR
      DOUBLE PRECISION  CST_ICEAIR,LIN_ICEAIR
!
!     COEFFICIENT FOR BACK RADIATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIB
!
!     COEFFICIENT FOR EVAPORATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIE
!
!     COEFFICIENT FOR CONDUCTIVE HEAT FLUX
      DOUBLE PRECISION COEF_PHIH
!
!     COEFFICIENT FOR PRECIPITATION HEAT FLUX
      DOUBLE PRECISION COEF_PHIP
!
!     SOLAR CONSTANT (W/M^2)
      DOUBLE PRECISION SIO
!
!     ALBEDO OF ICE
      DOUBLE PRECISION ALBE
!
!     LIGHT EXTINCTION COEFFICIENT
      DOUBLE PRECISION EXTINC
!
!
!=======================================================================
!
!       ?) GEOGRAPHICAL CONSIDERATIONS
!
!     TODO: TO BE REPLACED BY A COMPUTATION FROM PHI0 (AND LAMBD0)
!
!     STANDARD LONGITUDE, IN DEG REES
      DOUBLE PRECISION ALSM
!
!     LOCAL LONGITUDE, IN  DEGREES
      DOUBLE PRECISION ALLM
!
!     -1, FOR WEST LONGITUDE; + FOR EAST LONGITUDE
      DOUBLE PRECISION ETADIR

!
!
!=======================================================================
!
!       ?) FREEZE-UP RELATED PARAMETERS
!
!
!     NUMBER OF CLASSES FOR FRAZIL ICE
!
      INTEGER NC_FRA
!
!     FRAZIL CRYSTAL RADIUS [ M ]
      DOUBLE PRECISION, ALLOCATABLE :: RK_FRZL(:)
!
!     FRAZIL CRYSTAL THICKNESS [ M ]
      DOUBLE PRECISION, ALLOCATABLE :: EK_FRZL(:)
!
!     FRAZIL CRYSTAL VOLUME [ M3 ]
      DOUBLE PRECISION, ALLOCATABLE :: VK_FRZL(:)
!
!     NUSSELT NUMBER
      DOUBLE PRECISION NUSS
!
!     MODEL FOR COMPUTATION OF THE NUSSELT NUMBER
      DOUBLE PRECISION NUSSI
!
!     TURBULENT NUSSELT NUMBER
      DOUBLE PRECISION, ALLOCATABLE :: NUSST(:)
!
!     TURBULENT MODEL TO ESTIMATE K-EPS
      INTEGER ITURB
!
!     TURBULENT PARAMETERS (USED WHEN ITURB=1)
      DOUBLE PRECISION KTURB(4)
!
!     MODEL FOR THE COMPUTATION OF THE BUOYANCY VELOCITY
      INTEGER IBUOY
!
!     FRAZIL PARTICLE BUOYANCY VELOCITY
      DOUBLE PRECISION, ALLOCATABLE :: VBK(:)
!
!     FRAZIL CRYSTAL DIAMETER THICKNESS RATIO [ - ]
      DOUBLE PRECISION DE
!
!     WATER-FRAZIL THERMAL CONDUCTIVITY [ W/M/oC ]
      DOUBLE PRECISION TC_WT                        !  =>  REPLACES XKWP

!     THERMAL CONDUCTIVITY OF BLACK ICE ( W/M/oC )
      DOUBLE PRECISION TC_BI                        !  =>  REPLACES XKI

!     THERMAL CONDUCTIVITY OF SNOW ( W/M/oC )
      DOUBLE PRECISION TC_S                         !  =>  REPLACES XKS
!
!     SETTLING COEFFICIENT OF FRAZIL ON BARS
      DOUBLE PRECISION AF
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - OPEN WATER
      DOUBLE PRECISION, ALLOCATABLE :: DEPK(:)
!
!     COEFFICIENT QUANTIFYING THE RATE OF REENTRAINMENT OF SURFACE
!       ICE PER UNIT AREA
      DOUBLE PRECISION, ALLOCATABLE :: EROK(:)

!     POROSITY OF SURFACE ICE
      DOUBLE PRECISION SURF_EF
!
!     SECONDARY NUCLEATION MODEL
      INTEGER ISNUC
!
!     SEEDDING MODEL
      INTEGER ISEED
!
!     MINIMUM NUMBER OF FRAZIL PARTICLES PER UNIT VOLUME
!     (FOR SEEDING MODEL EQ 1)
      DOUBLE PRECISION MINNK
!
!     MINIMUM FRAZIL VOLUME FRACTION BASED ON MINNK
!     (FOR SEEDING MODEL EQ 1)
      DOUBLE PRECISION, ALLOCATABLE :: MINCK(:)

!     FRAZIL ICE SEEDING RATE
!     (FOR SEEDING MODEL EQ 2)
      DOUBLE PRECISION, ALLOCATABLE :: SEEDR(:)
!
!     SECONDARY NUCLEATION NMAX PARAMETER
!     FOR SVENSSON AND OMSTEDT COLLISION MODEL
      DOUBLE PRECISION SNNMAX
!
!     FLOCULATION - BREAKUP MODEL
      INTEGER IFLOC
!
!     PARAMETER FOR NET EFFECT OF FLOCULATION - BREAKUP
!     RATIO OF PARTICLES THAT MOVE FROM CLASS I TO I+1
      DOUBLE PRECISION AFLOC
!
!     MEAN TURBULENT KINETIC ENERGY FOR FRAZIL THERMAL GROWTH
      TYPE(BIEF_OBJ), TARGET :: KGM
!
!     MEAN TURBULENT DISSIPATION RATE FOR FRAZIL THERMAL GROWTH
      TYPE(BIEF_OBJ), TARGET :: EPSGM
!
!     TURBULENT INTENSITY FOR FRAZIL THERMAL GROWTH
      TYPE(BIEF_OBJ), TARGET :: ALPGM
!
!     TURBULENT VISCOSITY FOR FRAZIL THERMAL GROWTH
      TYPE(BIEF_OBJ), TARGET :: NUTGM
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - OPEN WATER
      TYPE(BIEF_OBJ), TARGET :: THETA0
!
!     PROBABILITY OF DEPOSITION OF FRAZIL PARTICLES REACHING THE
!       SURFACE LAYER - ICE
      TYPE(BIEF_OBJ), TARGET :: THETA1
!
!     COEFFICIENT QUANTIFYING THE RATE OF REENTRAINMENT OF SURFACE
!       ICE PER UNIT AREA
      TYPE(BIEF_OBJ), TARGET :: BETA1
!
!     AVERAGE RISING VELOCITY OF FRAZIL ICE IN THE TURBULENT RIVER FLOW
      TYPE(BIEF_OBJ), TARGET :: VBB
!
!     ICE CONCENTRATION AS COMPUTED FROM SURFACE ICE PARTICLES
!     (ALSO USED TO DEFINE OPEN WATER VS. UNDER ICE COVER)
      TYPE(BIEF_OBJ), TARGET :: ANFEM
!
!     TOTAL ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIFEM
!
!     SOLID ICE THICKNESS
      TYPE(BIEF_OBJ), TARGET :: THIFEMS
!
!     FREEZING POINT OF WATER ( 0.oC BY DEFAULT )
      DOUBLE PRECISION CST_TMELT
      TYPE(BIEF_OBJ), TARGET :: TMELT

!     TOTAL NUMBER OF FRAZIL PARTICLE
      TYPE(BIEF_OBJ), TARGET :: NTOT,NTOT3,NTOTS

!     TOTAL NUMBER OF FRAZIL PARTICLE
      TYPE(BIEF_OBJ), TARGET :: CTOT,CTOT3,CTOTS
!
!     ELEVATION Z FOR 3D OUTPUT
      TYPE(BIEF_OBJ), TARGET :: ELEZ
!
!     FRAZIL CONCENTRATION
      TYPE(BIEF_OBJ), TARGET :: FRZL,FRZL3,FRZLS
!
!     FRAZIL NUMBER OF PARTICLE
      TYPE(BIEF_OBJ), TARGET :: NBP,NBP3,NBPS
!
!     WATER TEMPERATURE
      TYPE(BIEF_OBJ), TARGET :: TEMP,TEMP3,TEMPS
!
!     WATER SALINITY
      TYPE(BIEF_OBJ), TARGET :: SAL,SAL3,SALS
!
!     MINIMAL VALUE FOR PRECIPITATION INDUCED COVER
      DOUBLE PRECISION PRE_MIN
!
!     INITIAL CONCENTRATION OF FRAZIL
      DOUBLE PRECISION, ALLOCATABLE :: FRZL0(:)
!
!     PRESCRIBED CONCENTRATION OF FRAZIL
      DOUBLE PRECISION, ALLOCATABLE :: PREFRZL(:)
!
!     SCHEME FOR ADVECTION OF FRAZIL
      INTEGER  SCHADVFRZL
!
!     SCHEME OPTION FOR ADVECTION OF FRAZIL
      INTEGER  OPTADV_FRZL
!
!     SCHEME FOR DIFFUSION OF FRAZIL
      INTEGER  SCHDFRZL
!
!     FINITE VOLUME SCHEME FOR DIFFUSION OF FRAZIL
      INTEGER  MVIST_FRZL
!
!     SOLVER OPTIONS FOR DIFFUSION OF FRAZIL
      TYPE(SLVCFG), ALLOCATABLE :: SLVFRZL(:)
!
!     DIFFUSION COEFFICIENT OF FRAZIL
      DOUBLE PRECISION, ALLOCATABLE :: DIFFRZLNU(:)
!
!     DIFFUSION COEFFICIENT OF FRAZIL
      DOUBLE PRECISION, ALLOCATABLE :: DNUFRZLH(:)
!
!     DIFFUSION COEFFICIENT OF FRAZIL
      DOUBLE PRECISION, ALLOCATABLE :: DNUFRZLV(:)
!
!     NUMBER OF PRESCRIBED FRAZIL VALUES
      INTEGER NPREFRZL
!
!     INITIAL CONCENTRATION COVER
      DOUBLE PRECISION CONC0
!
!     PRESCRIBED CONCENTRATION OF COVER
      DOUBLE PRECISION, ALLOCATABLE :: PRECONC(:)
!
!     INITIAL THICKNESS COVER
      DOUBLE PRECISION THI0
!
!     PRESCRIBED THICKNESS OF COVER
      DOUBLE PRECISION, ALLOCATABLE :: PRETHI(:)
!
!     DIFFUSION COEFFICIENT OF CONCENTRATION COVER
      DOUBLE PRECISION DIFCONCNU
!
!     DIFFUSION COEFFICIENT OF CONCENTRATION COVER
      DOUBLE PRECISION DIFTHINU
!
!     DYNAMIC ICE COVER SURFACE FRACTION OUTPUT
      TYPE(BIEF_OBJ), TARGET :: DYNCOVC
!
!     DYNAMIC ICE COVER THICKNESS OUTPUT
      TYPE(BIEF_OBJ), TARGET :: DYNCOVT
!
!     DYNAMIC ICE COVER SOURCE TERM
      TYPE(BIEF_OBJ), TARGET :: SUM_SRCP
!
!     ICE COVER GRADIENTS
      TYPE(BIEF_OBJ), TARGET :: DCOVX,DCOVY
!
!=======================================================================
!
!       ?) ICE COVER RELATED PARAMETERS
!
!     ICE FRICTION
      TYPE(BIEF_OBJ), TARGET :: ICESTR

!     TURBULENT INTENSITY
      TYPE(BIEF_OBJ), TARGET :: VZ
!
!     CRITICAL WATER TEMPERATURE FOR BORDER ICE
      TYPE(BIEF_OBJ), TARGET :: TCR
!
!     CRITICAL VELOCITY ABOVE WHICH STATIC BORDER ICE WILL NOT FORM
      DOUBLE PRECISION VCRBOR
!
!     CRITICAL VELOCITY ABOVE WHICH DYNAMIC BORDER ICE WILL NOT FORM
      DOUBLE PRECISION VCRBOM
!
!     INITIAL CONCENTRATION FOR BORDER / SKIM ICE FORMATION
      DOUBLE PRECISION ANFEM0      ! REPLACES ANMAXBORDER AND ANMAXSKIM
!
!     LAW OF FRICTION ON UNDER ICE COVER
      INTEGER IFROT
!
!     LAW FOR FRICTION COEFFICIENT
      INTEGER IFICE
!
!     FRICTION COEFFICIENT OF THE UNDER ICE COVER
      DOUBLE PRECISION FICE

!     MAX FRICTION COEFFICIENT OF THE UNDER ICE COVER
      DOUBLE PRECISION FICE_MAX
!
!     EQUIVALENT SURFACE ICE THCIKNESS (LAW FOR FRICTION COEFFICIENT=1)
      DOUBLE PRECISION THIE
!
!     UNDER COVER FRICTION MODEL
      INTEGER IFRIC
!
!     ICE COVER PRESSURE GRADIENT MODEL
      INTEGER IPRES
!
!=======================================================================
!
!       ?) CLOGGING RELATED PARAMETERS
!
!     POROSITY OF ACCUMULATED ICE
      DOUBLE PRECISION CLOG_EF
!
!     ANGLE OF ACCUMULATED ICE
      DOUBLE PRECISION CLOG_THETA
!
!     PHYSICAL CHARACTERISTICS OF THE INTAKE RACK
      DOUBLE PRECISION CLOG_VDIST,CLOG_VDIAM,CLOG_TDIST,CLOG_TDIAM
!
!     CLOGGED BOUNDARY NUMBERS
      INTEGER NFRCLOG,NSECLOG,NTOTCLOG
      INTEGER, ALLOCATABLE :: NUMCLOG(:),SECLOG(:)
      INTEGER, ALLOCATABLE :: NSEG_FS(:),LISTE_FS(:,:,:)
      DOUBLE PRECISION, ALLOCATABLE :: UN1(:),UN2(:)
!
!     GROWTH THICKNESS OF THE VERTICAL AND HORIZONTAL ACCRECION
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VWDTH(:),CLOG_TWDTH(:)
!
!     PHYSICAL SIZE OF LENGTHS OF THE VERTICAL AND HORIZONTAL BARS
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VLGTH(:),CLOG_TLGTH(:)
!
!     TOTAL VOLUM OF ACCRECION
      DOUBLE PRECISION, ALLOCATABLE :: CLOG_VOLUM(:)
!
!     CLOGGING SECTIONS
      TYPE(BIEF_OBJ), TARGET :: MSKSEC
!
!=======================================================================
!
!       ?) ICE CHARACTERISATION
!
!     REPLACEMENT OF:
!       ICE ISLAND INDEX:   TYPE(BIEF_OBJ), TARGET :: JAMFEM
!       ICE TYPE INDEX:     TYPE(BIEF_OBJ), TARGET :: ICEREGION
!     ICETYPE IS:
!       1 - OPEN WATER
!       2 - STATIC BORDER ICE, FULLY WITHIN THE BORDER ICE COVER
!       3 - STATIC BORDER ICE THAT HAS GROWN A SUFFICIENTLY THICK COVER
!     ICELOC IS:
!       1 - OPEN WATER
!       2 - BOUNDARY NODE
!       3 - EDGE NODE
      TYPE(BIEF_OBJ), TARGET :: ICETYPE
      TYPE(BIEF_OBJ), TARGET :: ICETYPEP
      TYPE(BIEF_OBJ), TARGET :: ICELOC
!
!     INTEGERS WORKING ARRAYS
      TYPE(BIEF_OBJ), TARGET :: IT1,IT2
!
!-----------------------------------------------------------------------
!
!     IMAGE ELEMENT
      INTEGER, ALLOCATABLE :: IMGELM(:,:)

      !PARCEL'S NUMBER OF BOOM IMAGE
      INTEGER, ALLOCATABLE ::NAPHABM(:,:)

!     TRASH RACK CROSS SECTION NODES
      INTEGER, ALLOCATABLE :: NCGNO(:),NFZNO(:)
!
      INTEGER NTWBC
!
!     NUMBER OF INTAKES
      INTEGER NITK

!     SWTICH FOR FRAZIL CLOGGING
      INTEGER NCLOG

      INTEGER, PARAMETER :: MAXFRO = 50

!     MAXIMUM TOTAL NEIGHBORING PARCEL NUMBER
      INTEGER MAXKRN

!      NUNBER OF ICE BOOM
      INTEGER NBM

!      MAXIMUM NUNBER OF ICE BOOM
      INTEGER MAXBM

!     NUMBER OF ICE BOOM SPANS
      INTEGER NBMSP

!     ICE BOOM TYPES
      INTEGER BMTYPE

!      NUMBER OF SLOT TO ISSUE ICE
      INTEGER ITBDF

!      NUMBER OF BREAKUP REACHES
      INTEGER NCOV

!      NUMBER OF SOLID BOUNDARY
      INTEGER NMLBN

!      NUMBER OF OPEN BOUNDARY
      INTEGER NMOBN

!      NUMBER OF UNDERCOVER BOUNDARY
      INTEGER NUQSEC

!     TYEP OF UNDERCOVER BOUDNARY CONDITION
      INTEGER IUQBC

!     COUNTER FOR UNDERCOVER BOUNDARY CONDITION
      INTEGER IUNDT

      INTEGER ITMAX
      !     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!      NUMBER OF ICE BOUNDARY
      INTEGER MSBD

!      ICE CONCENTRATION BE SPECIFIED
      INTEGER IQBJB

!      NUMBER OF SOLID BOUNDARY
      INTEGER NLB

!     NUMBER OF OPEN BOUNDARY
      INTEGER NOB

!     NUMBER OF TIMESTEP FOR UNDERCOVER
      INTEGER IUND

      INTEGER NTBN,NHBN,NQBN,N0BN,NHTN,NFBN,NQB1,NQ0,NQ01,
     &  NEL,NSBN

!     NUMBER OF PARCEL IN THE DOMAIN
      INTEGER NPARIN

!     NUMBER OF PARCEL MOVING OUT OF THE DOMAIN
      INTEGER NPAROUT

!     DELETE THE BAD PARCELS
      INTEGER NBADPARCELS

!     TOTAL NUMBER OF PARCELS
      INTEGER NTOTALPARCELS

!     FILE NUMBER FOR UNDERCOVER BOUNDARY FILE
      INTEGER IUDC

!     FILE NUMBER FOR ICE BOOM FILE
      INTEGER INBM

!     FILE NUMBER FOR ICE BOOM FORCE FILE
      INTEGER IBMF

!     FILE NUMBER FOR BREAK UP FILE
      INTEGER IBRK

!     FILE NUMBER FOR ICE CONDITION ON FEM NODE FILE
      INTEGER IHDW0

!     FILE NUMBER FOR FRAZIL DEPOSITION AND ENTRAINMENT
      INTEGER IFRZ

!     FILE NUMBER FOR TRASH TRACK AND CROSS SECTIONS
      INTEGER ICSG

!     ICE FLUX TIME FRAME
      INTEGER KFLXI

      INTEGER KPRT
      INTEGER KDMPH
      INTEGER KDMPI
      INTEGER KDMPHI

      INTEGER KWND
      INTEGER KELV,KFLX,
     &  KHDW,KHDI,KHOT,KSTR,KTHR,IRND
!          ! UPDATE BOUNDARY AND OUTPUT
     & JOBFLX,NSEC,NDISC,NELEV,ISTRT,
     & IHDW,IHOT0,IHOT,ISTR0,ISTR,ILNK,
     & IPRO,IPLT,ICLG,IQBD

!     NUMBER OF ICE PARCELS
      INTEGER KNP

!     STEPS TO CHECK BREAKUP
      INTEGER NBKDTM

!     NUMBER OF REACHES FOR BREAKUP
      INTEGER NRCH

!     ATMOSPHERE-WATER EXCHANGE MODEL
!
      INTEGER ATMOEXCH
!
!     ! INDEX FOR DISCHARGE USED FOR FRAZIL ACCRETION
!      INTEGER, PARAMETER :: KCGQ = 1
!
!
!
!
!-----------------------------------------------------------------------
!
!       3) LOGICAL
!
!     WITH ICEDYNAMICS CALCULATION
      LOGICAL ICEDYNAMICS
!
!     IF YES, MASS-BALANCE
      LOGICAL ICEBILMAS
!
!     IF YES, VALIDATION
      LOGICAL ICEVALID
!
!     STEADY HYDRODYNAMICS
      LOGICAL  PERMA
!
!     IF TEMPERATURE IS VARIABLE
      LOGICAL YATEMP

!      IF YES, TECPLOT OUTPUT
      LOGICAL IOUTPUT

!     IF YES, ICE INPUT
      LOGICAL ICIPUT
!
!     HEAT EXCHANGES
      LOGICAL THERMAL_BUDGET
!
!     ICE COVER IMPACT ON HYDRO
      LOGICAL ICOVER_IMPACT
!
!     CLOGGING
      LOGICAL CLOGGING
!
!     BORDER_ICE
      LOGICAL BD_ICE
!
!     SALINITY
      LOGICAL SALINITY
!
!     DYNAMIC ICE COVER
      LOGICAL DYN_ICOVER
!
!     FRAZIL PRECIPITATION MODEL
      INTEGER IPREC
!
!     SCHEME OPTION FOR THERMAL GROWTH
      INTEGER ITGM
!
!     ENERGY BALANCE VERSION
      INTEGER INRJB
!
!-----------------------------------------------------------------------
!
!       4) REALS
!
!-----------------------------------------------------------------------

      DOUBLE PRECISION ROI
!  ICE LATENT HEAT
!      DOUBLE PRECISION XLATEN    !       => MOVED TO KHIONE UNDER LH_ICE

      !  CLOUDINESS
      DOUBLE PRECISION CC

!     HEIGHT THE WIND DATA IS MEASUR ED(M)
      DOUBLE PRECISION Z1

!     ELEVATION MEASURED FROM SEA  LEVEL(M)
      DOUBLE PRECISION ZH

!--------------------------------------------------------------
!  GROUP FOR SIMULATING WATER TEMPERATURE AND THERMAL GROWTH AND DECAY OF ICE

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION HWA

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION HIA

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON ICE-AIR SURFACE
      DOUBLE PRECISION ALP

!     COEFFICIENT FOR LINEARIZED HEAT FLUX CALCULATION ON WATER-AIR SURFACE
      DOUBLE PRECISION ALPW
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR TURBULENT FLOW
      DOUBLE PRECISION CWI1
!
!     CONSTANT FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR SUPERCOOLED TURBULENT FLOW
      DOUBLE PRECISION CIW1
!
!     NUSSELT NUMBER FOR CALCULATING HEAT TRANSFER COEFFICIENT BETWEEN RIVER WATER AND ICE FOR LAMINAR FLOW
      DOUBLE PRECISION ATA

!     HEAT TRANSFER COEFFICIENT FROM WATER TO ICE
      DOUBLE PRECISION CWI
!
!     KINEMATIC VISCOSITY OF WATER
      DOUBLE PRECISION XNU

!------------------------------------------------------------------------
!   GROUP FOR SIMULATING BORDER ICE FORMATION
!
!     CRITICAL WATER SURFACE TEMPERATURE FOR BORDER ICE FORMATION
      DOUBLE PRECISION TC
!
!     CHANNEL WIDTH FOR THE COMPUTATION OF SURFACE WATER TEMPERATURE
      DOUBLE PRECISION BCH
!
!     MAXIMUM CONCENTRATION FOR BORDER ICE FORMATION
!      DOUBLE PRECISION ANMAXBORDER
!
!----------------------------------------------------------------------------
! GROUP FOR SKIM ICE SIMULATION
!
!     MAXIMUM CONCENTRATION FOR SKIM ICE RUN
!      DOUBLE PRECISION ANMAXSKIM                 => REPLACED BY ANFEM0
!
!--------------------------------------------------------------------------
! GROUP FOR MASS EXCHANGE BETWEEN SUSPENDED LAYER, SURFACE LAYER AND ANCHOR ICE

!     POROSITY OF SURFACE ICE
      DOUBLE PRECISION EF

!     POROSITY OF FRAZIL ICE
      DOUBLE PRECISION EF0

!     VERTICAL BAR LENGTH
      DOUBLE PRECISION HBAR
!
!-------------------------------------------------------------------------------
!  GROUP FOR ICE COVER FORMATION
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
      DOUBLE PRECISION WFV0,WFV1
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
      DOUBLE PRECISION WFT0,WFT1
!
!     INITIAL AND CURRENT WIDTH FOR VERTICAL BARS
      DOUBLE PRECISION WFV0DW,WFV1DW
!
!     INITIAL AND CURRENT WIDTH FOR TRANSVERSE BARS
      DOUBLE PRECISION WFT0DW,WFT1DW
!
!
      DOUBLE PRECISION TIME,CORIO,PI,SQPI
      DOUBLE PRECISION  RHO,RHOI,RADDIG

!     GEOMETRY MAX & MIN
      DOUBLE PRECISION XMIN,YMIN,XMAX,YMAX,XGMIN,YGMIN

!     INITIAL ICE PARCEL CONCENTRATION
      DOUBLE PRECISION AN0

!     INITIAL FRAZIL ICE THICKNESS
      DOUBLE PRECISION THI0F

!     INITIAL SIZE OF ICE PARCEL
      DOUBLE PRECISION HPI0
!
!     A MINIMUM VALUE
      DOUBLE PRECISION VSM
!
!     NUMBER OF ICE PARCELS
!     DOUBLE PRECISION KNP
!
!     ICE PARCEL MASS
      DOUBLE PRECISION PM1
!
      DOUBLE PRECISION ANGLE   ! MAY NOT NEED;   WIND ANGLE
!
      DOUBLE PRECISION REFEL   ! MAY NOT NEED; REFERENCE LEVEL FOR HYDRO
!
      DOUBLE PRECISION OPTIM  ! MAY NOT NEED; OPTIMAL TIME STEP FOR HYDRO
!
!     ICE MASS DENSITY AND ICE MASS AT TN
      DOUBLE PRECISION UMI0,PMI0,PMI0F

!     FRICTION COEFFICIENT BETWEEN ICE-RIVERBANK; ICE-RIVERBED
      DOUBLE PRECISION FRIC1,FRIC2
!
!     AIR-ICE DRAG COEFFICIENT
      DOUBLE PRECISION WDCA

!     ICE INTERNAL FRICTION ANGLE
      DOUBLE PRECISION PHI
!
!     EMPIRICAL CONSTANT
      DOUBLE PRECISION PJ
!
!     MAX WATER-ICE DRAG COEFFICIENT
      DOUBLE PRECISION CWMAX

!     BOLTZMANN CONSTANT (WM-2K-4)
      DOUBLE PRECISION SGMA

!     SPECIFIC HEAT OF WATER
      DOUBLE PRECISION CP

!     TIME FOR ICE DYNAMICS
      DOUBLE PRECISION TIMICE0
      DOUBLE PRECISION TMN
      DOUBLE PRECISION ENDTIME

!      UNDERCOVER TIME STEP
      DOUBLE PRECISION UNDT

!     STARTING TIME OF ICE DYNAMICS
      DOUBLE PRECISION TICEBG

!     BOOM CURTAIN DEPTH
      DOUBLE PRECISION DWALL

      ! WEATHER TIME
      DOUBLE PRECISION TIMA0,TIMA1,TAIR0,TAIR1


!     VARIABLES FOR BOUNDARY CONDITIONS AND NODAL INFORMATION FOR
!     HYDRODYNAMICS MAY NOT BE NEEDED
      DOUBLE PRECISION SINBN,COSBN,HB,
     & QB,STEMP,CTEMP,DISCH,DISCHU,
     & WNDTIME,PRTTIME,DMPTIMH,DMPTIMI,
     & FAC,QBT,QBTI,QIN,XBGN,YBGN,XEND,YEND

!     ICE BOOM COORDINATE
      DOUBLE PRECISION, ALLOCATABLE :: XBM(:,:),YBM(:,:)

!     ICE BOOM SPAN COORDINATE
      DOUBLE PRECISION, ALLOCATABLE :: XBMSP(:,:),YBMSP(:,:)

!     FORCE PER UNIT LENGTH IN SPAN J
      DOUBLE PRECISION, ALLOCATABLE :: ASIGNP(:)

!     ICE BOOM FLOAT OR SUBMERGE
      DOUBLE PRECISION, ALLOCATABLE :: FRNUM1(:)

!     ICE THICKNESS AT THE ICE BOOM J
      DOUBLE PRECISION, ALLOCATABLE :: THISP(:)

!     CRITICAL SUBMERGENCE LINE LOAD OF BOOM
      DOUBLE PRECISION, ALLOCATABLE :: BMLINELD(:)

!     CRITICAL ICE THICKNESS ABOVE SUBMERGED BOOM FOR RE-EMERGENCE
      DOUBLE PRECISION, ALLOCATABLE :: THIEMERG(:)

!     BOTTOM ELEVATION OF THE GATE
      DOUBLE PRECISION, ALLOCATABLE :: GATE(:)

!     BUOYANT FORCE OF THE ICE BOOM WHEN IT IS SUBMERGED
      DOUBLE PRECISION, ALLOCATABLE :: BMBUOY(:)

!     FRICTION COEFFICIENT BETWEEN THE ICE BOOM AND THE BOTTOM OF THE ICE
      DOUBLE PRECISION, ALLOCATABLE :: BMFRIC(:)

!     DIRECTION OF THE SOLID BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: PAPHA1(:),PAPHA2(:)

!     DISTANCE BETWEEN ICE PARCEL AND SOLID BOUNDARY
      DOUBLE PRECISION, ALLOCATABLE :: PARDIS(:)

!     DIRECTION OF THE ICE BOOM
      DOUBLE PRECISION, ALLOCATABLE :: PAPHABM1(:),PAPHABM2(:)

!     DISTANCE BETWEEN ICE APARCEL AND ICE BOOM
      DOUBLE PRECISION, ALLOCATABLE :: PARDISBM(:)

!!     DIRECTION OF THE ICE BOOM (SIN,COS)
!      DOUBLE PRECISION, ALLOCATABLE :: ALPHA11(:),ALPHA12(:)

!!     DISTANCE BETWEEN ICE PARCEL AND ICE BOOM
!      DOUBLE PRECISION, ALLOCATABLE :: PARDS1(:)

!     TIME FOR ICE COVER BREAKUP
      DOUBLE PRECISION, ALLOCATABLE :: BRKTIM(:)

!     CRITICAL VALUE OF WATER SURFACE ELEVATION AT REFERENCE NODE
      DOUBLE PRECISION, ALLOCATABLE :: BRKWSE(:)

!     CRITICAL VALUE OF WATER SURFACE ELEVATION INCREASE AT REFERENCE NODE
      DOUBLE PRECISION, ALLOCATABLE :: BRKDWSE(:)

!     WATER SURFACE ELEVATON RECORD FOR BREAKUP
      DOUBLE PRECISION, ALLOCATABLE :: WSERD(:,:)

!     INITIAL ICE COVER THICKNESS
      DOUBLE PRECISION, ALLOCATABLE :: COVTI(:)

!      FINITE ELEMENT ORIENTATION AND HEIGHT
      DOUBLE PRECISION, ALLOCATABLE :: ALAFAE(:),ELMHT(:)

!      FINITE ELEMENT MAX EDGE IN X,Y
      DOUBLE PRECISION, ALLOCATABLE :: XMAXH(:),YMAXH(:)

!      FINITE ELEMENT INFORMAITON
      DOUBLE PRECISION, ALLOCATABLE :: A1(:),A2(:),A3(:)
      DOUBLE PRECISION, ALLOCATABLE :: B1(:),B2(:),B3(:)
      DOUBLE PRECISION, ALLOCATABLE :: C1(:),C2(:),C3(:)
      DOUBLE PRECISION, ALLOCATABLE :: CLMP(:)
!
!-----------------------------------------------------------------------
!      LINK FILE
      CHARACTER(LEN=50) LNKFILE

!      ICE BOUNDARY FILE
      CHARACTER(LEN=50) IQBFILE

!      ICE BOOM FILE AND BOOM FORCE FILE
      CHARACTER(LEN=50) BMFILE,BFFILE

!      BREAKUP FILE
      CHARACTER(LEN=50) BKFILE

!      UNDERCOVER TRANSPORT FILE
      CHARACTER(LEN=50) UDFILE

!     FRAZIL COEFFICIENTS FILE
      CHARACTER(LEN=50) FZFILE

!     TRASH RACK CROSS SECTION FILE
      CHARACTER(LEN=50) TRFILE

!     FRAZIL CLOGGING OUTPUT FILE
      CHARACTER(LEN=50) CLGFILE

!     EXISTING ICE CONDITION FILE
      CHARACTER(LEN=50) HT0FILE,ST0FILE,HD0FILE

      CHARACTER(LEN=50) CASENAME,GEOFILE,TIMFILE,PRTFILE,
     &  PTMFILE,FLXFILE,ELVFILE,WNDFILE,DSCFILE,
     &  HO0FILE,ERRFILE,STATE,THRFILE,DELFILE,
     &  QNIFILE,QNWFILE,DBMFILE,
     &  LELFILE,NBMFILE,PROFILE,TBCFILE,LINKEFILE,SWIFILE,MCRFILE,
     &  WEAFILE,ICEVOLUMEFILE,NETFILE,COVFILE,PARFILE,
     &  CLGDWFILE,DSCLOC,ELVLOC,DSCILOC

      INTEGER, PARAMETER :: MAX_ICE_FILE = 1000

!      TYPE(BIEF_FILE) :: PLTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) PLTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) HDWFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) HOTFILE(MAX_ICE_FILE)

      CHARACTER(LEN=50) STRFILE(MAX_ICE_FILE)
!
!=======================================================================
!
!       5) BLOCKS
!
!-----------------------------------------------------------------------
!
!     BLOCK OF ICE VARIABLES
!
      TYPE(BIEF_OBJ), TARGET :: ICVAR
!
!
!     BLOCK OF WORKING ARRAYS
!
      TYPE(BIEF_OBJ), TARGET :: TB,TB3
!
!=======================================================================
!
!       X) POINTERS
!
!-----------------------------------------------------------------------
!
!     DECLARATION OF POINTERS FOR ALIASES TO WORKING VECTORS IN TB
!     TARGETS ARE DEFINED IN POINT_KHIONE.
!
      TYPE(BIEF_OBJ),POINTER :: T1,T2,T3,T4,T5,T6
      TYPE(BIEF_OBJ),POINTER :: T1_3,T2_3
!
!=======================================================================
!
!       X) WORKING MATRIX AND ARRAY
!
!-----------------------------------------------------------------------
!
      TYPE(BIEF_OBJ),TARGET :: BM1,BM2
      TYPE(BIEF_OBJ),TARGET :: CV1,CV2,CV3,CV4
!
!=======================================================================
!
      SAVE

      END MODULE DECLARATIONS_KHIONE


