/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          7369,
                                          1491,
                                          "Load Binary File",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          NULL,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  TecGUIFrameAdd(Dialog1Manager,
             426,
             189,
             4143,
             841,
                    "Load Method");

  TecGUIFrameAdd(Dialog1Manager,
             4927,
             326,
             2165,
             530,
                    "Variables for Deferred Load");

  Browse_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                6700,
                                1266,
                                375,
                                144,
                    "...",
                    Browse_BTN_D1_CB);

  FileName_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                    1227,
                                    1266,
                                    5115,
                                    144,
                       FileName_TF_D1_CB);

  LoadMethod_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                        682,
                                        265,
                                        3682,
                                        705,
                                 "Load Variable",
                                 "Deferred Load Variable",
                                 "Auto Load Var. on Demand",
                                 "Custom Load Var. on Demand",
                                 "Custom Load Value on Demand",
                                 LoadMethod_RADIO_D1_CB);

  File_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             426,
                             1304,
                    "File: ");

  CreateFile_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                    4927,
                                    68,
                                    2148,
                                    144,
                    "Create Test File  ... ",
                    CreateFile_BTN_D1_CB);

  SpecFunction_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      4944,
                                      894,
                                      2131,
                                      144,
                    "Specify Function ...",
                    SpecFunction_BTN_D1_CB);

  SpecifyVar_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                        5132,
                                        394,
                                        971,
                                        432,
                                 "All",
                                 "Odd",
                                 "Even",
                                 (char *)NULL,
                                 (char *)NULL,
                                 SpecifyVar_RADIO_D1_CB);

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          5051,
                                          1415,
                                          "Create Binary Test File",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          NULL,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  TecGUIFrameAdd(Dialog2Manager,
             306,
             682,
             1551,
             530,
                    "Data Type");

  TecGUIFrameAdd(Dialog2Manager,
             306,
             189,
             1551,
             394,
                    "Data File Format");

  DataFormat_RADIO_D2 = TecGUIRadioBoxAdd(Dialog2Manager,
                                        477,
                                        242,
                                        1005,
                                        295,
                                 "Block",
                                 "Point",
                                 (char *)NULL,
                                 (char *)NULL,
                                 (char *)NULL,
                                 DataFormat_RADIO_D2_CB);

  NumPoints_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                     3495,
                                     341,
                                     1227,
                                     144,
                       NumPoints_TF_D2_CB);

  NumVars_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                   3495,
                                   659,
                                   1227,
                                   144,
                       NumVars_TF_D2_CB);

  DataType_RADIO_D2 = TecGUIRadioBoxAdd(Dialog2Manager,
                                      443,
                                      735,
                                      1176,
                                      432,
                                 "Integer",
                                 "Float",
                                 "Double",
                                 (char *)NULL,
                                 (char *)NULL,
                                 DataType_RADIO_D2_CB);

  NumZones_TF_D2 = TecGUITextFieldAdd(Dialog2Manager,
                                    3495,
                                    978,
                                    1227,
                                    144,
                       NumZones_TF_D2_CB);

  LBL9_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                             2318,
                             371,
                    "# Points");

  LBL10_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                              2335,
                              689,
                    "# Variables");

  LBL11_LBL_D2 = TecGUILabelAdd(Dialog2Manager,
                              2369,
                              1016,
                    "# Zones");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
