/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


#include "TECADDON.h"
#include "GUIDEFS.h"
LgIndex_t Dialog1Manager = BADDIALOGID;
LgIndex_t Browse_BTN_D1 = BADDIALOGID;
LgIndex_t FileName_TF_D1 = BADDIALOGID;
LgIndex_t LoadMethod_RADIO_D1 = BADDIALOGID;
LgIndex_t File_LBL_D1 = BADDIALOGID;
LgIndex_t CreateFile_BTN_D1 = BADDIALOGID;
LgIndex_t SpecFunction_BTN_D1 = BADDIALOGID;
LgIndex_t SpecifyVar_RADIO_D1 = BADDIALOGID;
LgIndex_t Dialog2Manager = BADDIALOGID;
LgIndex_t DataFormat_RADIO_D2 = BADDIALOGID;
LgIndex_t NumPoints_TF_D2 = BADDIALOGID;
LgIndex_t NumVars_TF_D2 = BADDIALOGID;
LgIndex_t DataType_RADIO_D2 = BADDIALOGID;
LgIndex_t NumZones_TF_D2 = BADDIALOGID;
LgIndex_t LBL9_LBL_D2 = BADDIALOGID;
LgIndex_t LBL10_LBL_D2 = BADDIALOGID;
LgIndex_t LBL11_LBL_D2 = BADDIALOGID;
