!
        MODULE INTERFACE_GAIA
!
!
!***********************************************************************
! GAIA
!***********************************************************************
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE INTERFACE_GAIA_BEDLOAD
      USE INTERFACE_GAIA_SUSPENSION
!
      INTERFACE
        SUBROUTINE AFFECT_MAT(IELMU)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: IELMU
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE GAI_ARRET
     &(ESM,EMAX,HN,VARSOR,NPOIN,MN,NRES,FMTRES,MAXVAR,AT0,RC,HIST,
     & BINRESGAI,TEXTE,SORLEO,SORIMP,T1,T2)
        USE BIEF_DEF
        IMPLICIT NONE
      TYPE(BIEF_OBJ),    INTENT(IN)    :: ESM, EMAX, HN, VARSOR
      INTEGER,           INTENT(IN)    :: NPOIN, MN, NRES, MAXVAR
      DOUBLE PRECISION,  INTENT(IN)    :: AT0, RC, HIST(1)
      CHARACTER(LEN=3),  INTENT(IN)    :: BINRESGAI
      CHARACTER(LEN=32), INTENT(IN)    :: TEXTE(MAXVAR)
      CHARACTER(LEN=8),  INTENT(IN)    :: FMTRES
      LOGICAL,           INTENT(IN)    :: SORLEO(*), SORIMP(*)
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: T1, T2
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE MASS_BALANCE
     &(DT,NPTFR,ENTET,NSICLA,NUMLIQ,NFRLIQ,FLBCLA,
     & LT,NIT,NPOIN,VOLU2D,CHARR,SUSP,EVCL_MB,EVCL_MS,MASSTOT,
     & MASS0TOT)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NPTFR,NFRLIQ,NSICLA,LT,NIT
      INTEGER, INTENT(IN)           :: NPOIN,NUMLIQ(NPTFR)
      DOUBLE PRECISION, INTENT(IN)  :: DT
      LOGICAL, INTENT(IN)           :: ENTET,SUSP,CHARR
      DOUBLE PRECISION, INTENT(IN)  :: MASSTOT(NSICLA)
      DOUBLE PRECISION, INTENT(IN)  :: MASS0TOT(NSICLA)
      TYPE(BIEF_OBJ), INTENT(IN)    :: VOLU2D
      TYPE(BIEF_OBJ), INTENT(IN)    :: EVCL_MB,EVCL_MS
      TYPE(BIEF_OBJ), INTENT(INOUT) :: FLBCLA
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE CALCUW_GAIA( UW, H, HW, TW, GRAV ,NPOIN, TYPE_HOULE)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: NPOIN
        DOUBLE PRECISION, INTENT(INOUT) :: UW(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: H(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: TW(NPOIN),HW(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: GRAV
        INTEGER, INTENT(IN) :: TYPE_HOULE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE COEFRO_GAIA
     &  (CF,H,KS,NPOIN,KARMAN)
        USE BIEF_DEF
        IMPLICIT NONE
        INTEGER, INTENT(IN):: NPOIN
        DOUBLE PRECISION,INTENT(IN):: KARMAN
        TYPE(BIEF_OBJ), INTENT(INOUT) :: CF
        TYPE(BIEF_OBJ),INTENT(IN) :: KS,H
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE USER_FORCING_GAIA
        IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE CONLIT_GAIA
        USE BIEF_DEF
        IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        DOUBLE PRECISION FUNCTION CGL_GAIA( I , AT)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: I
          DOUBLE PRECISION, INTENT(IN):: AT
        END FUNCTION
      END INTERFACE
!
      INTERFACE
        DOUBLE PRECISION FUNCTION QGL_GAIA( I , AT)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: I
          DOUBLE PRECISION, INTENT(IN):: AT
        END FUNCTION
      END INTERFACE
!
      INTERFACE
        SUBROUTINE CORSTR_GAIA
        IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE DEBUG_GAIA (NAME, ILOOP, NLOOP)
        USE BIEF_DEF
        IMPLICIT NONE
        INTEGER, PARAMETER :: SIZE =100
        CHARACTER(LEN=SIZE)  , INTENT(IN) :: NAME
        INTEGER,   INTENT(IN), OPTIONAL :: ILOOP, NLOOP
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE DISIMP_GAIA
     &(Q,Q2BOR,NUMLIQ,IFRLIQ,NSOLDIS,WORK1,QBOR,NPTFR,MASK,MESH)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPTFR,IFRLIQ,NSOLDIS
      INTEGER, INTENT(IN)             :: NUMLIQ(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: MASK(NPTFR),Q
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: WORK1,QBOR
      TYPE(BIEF_OBJ), INTENT(IN)      :: Q2BOR
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE ENTETE_GAIA(IETAPE,AT,LT)
        IMPLICIT NONE
        DOUBLE PRECISION, INTENT(IN) :: AT
        INTEGER, INTENT(IN):: LT,IETAPE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE FLUSEC_GAIA
     &(U,V,H,QSXC,QSYC,CHARR,SUSP,
     & IKLE,NELMAX,NELEM,X,Y,DT,NCP,CTRLSC,INFO,TPS)
        USE BIEF_DEF
        IMPLICIT NONE
        INTEGER, INTENT(IN)          :: NELMAX,NELEM,NCP
        INTEGER, INTENT(IN)          :: IKLE(NELMAX,*)
        INTEGER, INTENT(IN)          :: CTRLSC(NCP)
        DOUBLE PRECISION, INTENT(IN) :: X(*),Y(*),TPS,DT
        LOGICAL, INTENT(IN)          :: INFO,SUSP,CHARR
        TYPE(BIEF_OBJ), INTENT(IN)   :: U,V,H,QSXC,QSYC
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE FLUXPR_GAIA
     &(NSEC, CTRLSC, FLX, VOLNEG, VOLPOS, INFO, TPS, NSEG, NCSIZE,  !JAJ #### TPS
     & FLXS,VOLNEGS,VOLPOSS,SUSP,FLXC,VOLNEGC,VOLPOSC,CHARR)
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NSEC,NCSIZE
      INTEGER, INTENT(IN)          :: CTRLSC(*)
      INTEGER, INTENT(IN)          :: NSEG(NSEC)
      LOGICAL, INTENT(IN)          :: INFO,SUSP,CHARR
      DOUBLE PRECISION, INTENT(IN) :: FLX(NSEC), TPS                !JAJ #### TPS
      DOUBLE PRECISION, INTENT(IN) :: VOLNEG(NSEC),VOLPOS(NSEC)
      DOUBLE PRECISION, INTENT(IN) :: FLXS(NSEC),FLXC(NSEC)
      DOUBLE PRECISION, INTENT(IN) :: VOLNEGS(NSEC),VOLPOSS(NSEC)
      DOUBLE PRECISION, INTENT(IN) :: VOLNEGC(NSEC),VOLPOSC(NSEC)
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE GAIA_STEP
     &(LOOPCOUNT,GRAFCOUNT,LISTCOUNT,TELNIT,
     & U_TEL,V_TEL,H_TEL,ZF_TEL,UETCAR,DELTAR,
     & CF_TEL,KS_TEL,
     & CODE,U3D,V3D,T_TEL,VISC_TEL,DT_TEL,CHARR_TEL,SUSP_TEL,
     & XMVE_TEL,GRAV_TEL,
     & THETAW_TEL,HW_TEL,TW_TEL,UW_TEL,YAGOUT,API_ITER,GRCOMP)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,           INTENT(IN)    :: LOOPCOUNT,GRAFCOUNT
      INTEGER,           INTENT(IN)    :: LISTCOUNT,TELNIT
      CHARACTER(LEN=24),  INTENT(IN)    :: CODE
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U_TEL,V_TEL,H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: ZF_TEL,UETCAR,KS_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: DELTAR
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U3D,V3D,VISC_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: CF_TEL
      DOUBLE PRECISION,  INTENT(IN)    :: T_TEL,XMVE_TEL,GRAV_TEL
      LOGICAL,           INTENT(INOUT) :: CHARR_TEL,SUSP_TEL
      DOUBLE PRECISION,  INTENT(IN)    :: DT_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: THETAW_TEL,HW_TEL,TW_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: UW_TEL
      LOGICAL,           INTENT(IN)    :: YAGOUT
      INTEGER, OPTIONAL, INTENT(IN)    :: API_ITER,GRCOMP
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE GAIA_INIT
     &(GRAFCOUNT,LISTCOUNT,TELNIT,U_TEL,V_TEL,H_TEL,ZF_TEL,UETCAR,
     & DELTAR,CF_TEL,KS_TEL,
     & CODE,U3D,V3D,T_TEL,DT_TEL,CHARR_TEL,SUSP_TEL,
     & THETAW_TEL,HW_TEL,TW_TEL,UW_TEL,YAGOUT,XMVE_TEL,GRAV_TEL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,           INTENT(IN)    :: GRAFCOUNT,LISTCOUNT
      INTEGER,           INTENT(IN)    :: TELNIT
      CHARACTER(LEN=24),  INTENT(IN)    :: CODE
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U_TEL,V_TEL,H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: ZF_TEL,UETCAR,KS_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: DELTAR
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U3D,V3D
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: CF_TEL
      DOUBLE PRECISION,  INTENT(IN)    :: T_TEL,XMVE_TEL,GRAV_TEL
      LOGICAL,           INTENT(INOUT) :: CHARR_TEL,SUSP_TEL
      DOUBLE PRECISION,  INTENT(IN)    :: DT_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: THETAW_TEL,HW_TEL,TW_TEL
      TYPE(BIEF_OBJ),    INTENT(IN)    :: UW_TEL
      LOGICAL,           INTENT(IN)    :: YAGOUT
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE GF_USER(TBEG_GF,TEND_GF,AT0)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(INOUT) :: TBEG_GF, TEND_GF
      DOUBLE PRECISION, INTENT(IN)    :: AT0
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE KS_GAIA
     &(IKS,KS,KSP,KSR,KSPRATIO,HOULE,GRAV,XMVE,XMVS,VCE,
     & HN,ACLADM,UNORM,UW,TW,NPOIN)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,            INTENT(IN)  :: NPOIN,IKS
      LOGICAL,            INTENT(IN)  :: HOULE
      DOUBLE PRECISION,   INTENT(IN)  :: XMVE,XMVS, VCE,GRAV
      DOUBLE PRECISION,   INTENT(IN)  :: KSPRATIO
      TYPE(BIEF_OBJ), INTENT(IN)      :: HN,UNORM
      TYPE(BIEF_OBJ), INTENT(IN)      :: TW,UW
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: KS,KSP,KSR
      TYPE(BIEF_OBJ), INTENT(IN)      :: ACLADM
      END SUBROUTINE
      END INTERFACE
!

      INTERFACE
        SUBROUTINE INIT_CONSTANT_GAIA
     &  (KARIM_HOLLY_YANG, KARMAN,  PI)
        IMPLICIT NONE
        DOUBLE PRECISION, INTENT(INOUT) :: KARIM_HOLLY_YANG
        DOUBLE PRECISION, INTENT(INOUT) :: KARMAN
        DOUBLE PRECISION, INTENT(INOUT) :: PI
!
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE BED1_INIT_SEDIMENT_GAIA
     &(NSICLA,ELAY,ZF,ZR,NPOIN,XMVS0,ES,NOMBLAY,
     & DEBU,VOLU2D,NUMSTRAT,MAXVAR)
      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER,           INTENT(IN)     :: NSICLA,NPOIN,NOMBLAY,MAXVAR
      INTEGER,           INTENT(IN)     :: NUMSTRAT
      TYPE(BIEF_OBJ),    INTENT(INOUT)  :: ELAY,ZF,ZR
      TYPE(BIEF_OBJ),    INTENT(INOUT)  :: VOLU2D
      DOUBLE PRECISION,  INTENT(IN)     :: XMVS0(NSICLA)
      LOGICAL,           INTENT(IN)     :: DEBU
      DOUBLE PRECISION, INTENT(INOUT)   :: ES(NPOIN,NOMBLAY)
      END SUBROUTINE
      END INTERFACE
!
!
      INTERFACE
        SUBROUTINE BED1_UPDATE
     &  (ZR,ZF,VOLU2D)
      USE BIEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      TYPE (BIEF_OBJ),  INTENT(INOUT)    :: ZR,ZF
      TYPE (BIEF_OBJ),  INTENT(IN)       :: VOLU2D
!
        END SUBROUTINE
      END INTERFACE
!
!
      INTERFACE
        SUBROUTINE INIT_TRANSPORT_GAIA
     & (HIDING,NSICLA,NPOIN,T1,T2,T3,T4,T5,T6,T7,T8,T9,
     & T10,T11,T12,T13,T14,CHARR,QS_C,QSXC,QSYC,CALFA_CL,SALFA_CL,
     & COEFPN,COEFCR,SLOPEFF,SUSP,QS,QSCL,QSCL_C,QSCL_S,UNORM,
     & U2D,V2D,HN,CF,MU,
     & TOB,TOBW,UW,TW,THETAW,FW,HOULE,ACLADM,UNLADM,KSP,KSR,
     & ICF,HIDFAC,XMVS0,XMVE,GRAV,VCE,HMIN,KARMAN,ZERO,PI,AC,CSTAEQ,
     & SECCURRENT,BIJK,IELMT,MESH,DCLA,XWC,SEDCO,U3D,V3D,CODE,H_TEL,
     & HW,THETAC,TOBCW_MEAN,TOBCW_MAX)
      USE BIEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)              :: NSICLA,NPOIN
      INTEGER, INTENT(IN)              :: ICF,HIDFAC,IELMT,SLOPEFF
      LOGICAL, INTENT(IN)              :: CHARR,SUSP,HOULE
      LOGICAL, INTENT(IN)              :: SECCURRENT,SEDCO(*)
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U2D,V2D,UNORM,HN,CF
      TYPE(BIEF_OBJ),    INTENT(IN)    :: MU,TOB,TOBW,UW,TW,THETAW,FW
      TYPE(BIEF_OBJ),    INTENT(IN)    :: ACLADM,UNLADM,KSP,KSR
      TYPE(BIEF_OBJ),    INTENT(IN)    :: H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: HIDING,CSTAEQ
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: QS_C, QSXC, QSYC
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: CALFA_CL,SALFA_CL
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: T1,T2,T3,T4,T5,T6,T7,T8
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: T9,T10,T11,T12,T13,T14
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: QS,QSCL_C,QSCL_S
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: COEFPN,COEFCR
      TYPE(BIEF_OBJ),    INTENT(INOUT) :: QSCL
      TYPE(BIEF_MESH),   INTENT(INOUT) :: MESH
      DOUBLE PRECISION,  INTENT(IN)    :: XMVS0(NSICLA),XMVE,GRAV,VCE
      DOUBLE PRECISION,  INTENT(IN)    :: HMIN,KARMAN,ZERO,PI
      DOUBLE PRECISION,  INTENT(IN)    :: BIJK,XWC(NSICLA)
      DOUBLE PRECISION,  INTENT(INOUT) :: AC(NSICLA),DCLA(NSICLA)
      TYPE(BIEF_OBJ),    INTENT(IN)    :: U3D,V3D
      CHARACTER(LEN=24), INTENT(IN)    :: CODE
      TYPE(BIEF_OBJ),   INTENT(IN)     :: HW, THETAC
      TYPE(BIEF_OBJ),   INTENT(INOUT)  :: TOBCW_MEAN, TOBCW_MAX
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE INTEG_GAIA ( A , B , IEIN , NPOIN)
        IMPLICIT NONE
        INTEGER, INTENT(IN):: NPOIN
        DOUBLE PRECISION, INTENT(IN)::A(NPOIN), B(NPOIN)
        DOUBLE PRECISION, INTENT(INOUT)::IEIN(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE LECDON_GAIA(MOTCAR,FILE_DESC,PATH,NCAR,CODE,
     & CAS_FILE,DICO_FILE)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER,INTENT(IN)                   :: NCAR
          CHARACTER(LEN=24),INTENT(IN)         :: CODE
          CHARACTER(LEN=PATH_LEN),INTENT(IN)   ::PATH
          CHARACTER(LEN=PATH_LEN),INTENT(INOUT)::MOTCAR(MAXKEYWORD)
          CHARACTER(LEN=PATH_LEN),INTENT(INOUT)::FILE_DESC(4,MAXKEYWORD)
!         API
          CHARACTER(LEN=PATH_LEN),INTENT(IN)   :: CAS_FILE
          CHARACTER(LEN=PATH_LEN),INTENT(IN)   :: DICO_FILE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE MASKAB_GAIA(HN , Q , QU , QV , NPOIN)
        IMPLICIT NONE
        INTEGER, INTENT(IN):: NPOIN
        DOUBLE PRECISION , INTENT(IN)::HN(NPOIN)
        DOUBLE PRECISION, INTENT(INOUT):: Q(NPOIN),QU(NPOIN),QV(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE MAXSLOPE_GAIA
      IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE MEAN_GRAIN_SIZE_GAIA
          USE BIEF
          IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE NOMVAR_GAIA
          USE DECLARATIONS_GAIA
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE PREDES_GAIA(LLT,AAT,YAGOUT,CODE,LISTCOUNT)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: LLT,LISTCOUNT
          DOUBLE PRECISION, INTENT(IN) :: AAT
          CHARACTER(LEN=24), INTENT(IN) :: CODE
          LOGICAL,INTENT(IN)           :: YAGOUT
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE READ_FIC_CONC_GAIA(CGL_GAIA, WHAT, AT, NFIC, LISTIN,
     &     FOUND )
      IMPLICIT NONE
      CHARACTER(LEN=9)     , INTENT(IN)       :: WHAT
      DOUBLE PRECISION, INTENT(IN)       :: AT
      DOUBLE PRECISION, INTENT(INOUT)    :: CGL_GAIA
      INTEGER         , INTENT(IN)       :: NFIC
      LOGICAL         , INTENT(IN)       :: LISTIN
      LOGICAL         , INTENT(OUT)      :: FOUND
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
      SUBROUTINE RESCUE_GAIA
     &(H,S,ZF,ZR,ES,HW,TW,THETAW,NPOIN,NOMBLAY,
     & TROUVE,ALIRE,PASS,ICF,LISTI,MAXVAR)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: MAXVAR,NOMBLAY
      INTEGER, INTENT(IN) :: ALIRE(MAXVAR),NPOIN,ICF
      LOGICAL, INTENT(IN) :: PASS,LISTI
      DOUBLE PRECISION, INTENT(IN) :: ES(NPOIN,NOMBLAY)
      INTEGER, INTENT(INOUT) :: TROUVE(MAXVAR)
      DOUBLE PRECISION, INTENT(INOUT) :: S(NPOIN) , ZF(NPOIN), H(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: ZR(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: HW(NPOIN), TW(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: THETAW(NPOIN)
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE RIDE_GAIA
     & (KS,TW,UW,UNORM,GRAV,XMVE,XMVS,VCE,NPOIN,KSPRATIO,ACLADM)
        IMPLICIT NONE
        INTEGER, INTENT(IN) ::NPOIN
        DOUBLE PRECISION, INTENT(INOUT) :: KS(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: GRAV,XMVE,XMVS, VCE
        DOUBLE PRECISION, INTENT(IN) :: UNORM(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: UW(NPOIN), TW(NPOIN)
        DOUBLE PRECISION, INTENT(IN) :: KSPRATIO
        DOUBLE PRECISION, INTENT(IN) :: ACLADM(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE RIDE_VR_GAIA
     & (KSR,KS,UNORM,HN,GRAV,XMVE,XMVS,NPOIN,ACLADM)
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NPOIN
      DOUBLE PRECISION, INTENT(IN)   :: GRAV,XMVE,XMVS
      DOUBLE PRECISION, INTENT(INOUT):: KSR(NPOIN),KS(NPOIN)
      DOUBLE PRECISION, INTENT(IN)   :: HN(NPOIN), UNORM(NPOIN)
      DOUBLE PRECISION, INTENT(IN)   :: ACLADM(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE TASSEMENT_2_GAIA
     &(ZF,NPOIN,DT,ELAY,DZF_TASS,T2,LT,XMVS,XMVE,GRAV,NOMBLAY,
     & ES,CONC_MUD,MS_VASE,XWC,COEF_N,CONC_GEL,CONC_MAX)
      USE BIEF_DEF
      USE BIEF
      IMPLICIT NONE
      INTEGER,INTENT(IN)              :: NPOIN
      INTEGER, INTENT(IN)             :: LT,NOMBLAY
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(IN)    :: XMVS,XMVE,GRAV
      TYPE (BIEF_OBJ),  INTENT(INOUT) :: DZF_TASS,ELAY,T2,ZF
      DOUBLE PRECISION, INTENT(INOUT) :: MS_VASE(NPOIN,NOMBLAY)
      DOUBLE PRECISION, INTENT(INOUT) :: ES(NPOIN,NOMBLAY)
      DOUBLE PRECISION, INTENT(IN)    :: CONC_MUD(NOMBLAY)
      DOUBLE PRECISION, INTENT(IN)    :: XWC
      DOUBLE PRECISION, INTENT(IN)    :: COEF_N,CONC_GEL,CONC_MAX
        END SUBROUTINE
      END INTERFACE
!
!
      INTERFACE
        SUBROUTINE TOBW_GAIA
     &  (TOBW ,CF, FW, UW,TW,HN,NPOIN,XMVE)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN
      DOUBLE PRECISION, INTENT(IN)    :: CF(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: UW(NPOIN),TW(NPOIN),HN(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: XMVE
      DOUBLE PRECISION, INTENT(INOUT) :: TOBW(NPOIN),FW(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE TOB_GAIA
     & (TOB, TOBW, TOBCW_MEAN, TOBCW_MAX, THETAC, THETAW, MU,
     &  KS,KSP, KSR,CF,FW,UETCAR,CF_TEL,KS_TEL,CODE,
     &  ICR, KSPRATIO, HOULE,GRAV,XMVE,XMVS, VCE, KARMAN,
     &  ZERO,HMIN,HN, ACLADM, UNORM,UW, TW, NPOIN,KSCALC,IKS,
     &  DELTAR, H_TEL)
      USE BIEF
      IMPLICIT NONE
      INTEGER,            INTENT(IN)  :: NPOIN,ICR, IKS
      LOGICAL,            INTENT(IN)  :: KSCALC
      LOGICAL,            INTENT(IN)  :: HOULE
      CHARACTER(LEN=24),  INTENT(IN)  :: CODE
      DOUBLE PRECISION,   INTENT(IN)  :: XMVE,XMVS, VCE,GRAV,KARMAN
      DOUBLE PRECISION,   INTENT(IN)  :: ZERO,HMIN,KSPRATIO
      TYPE(BIEF_OBJ), INTENT(IN)      :: UETCAR
      TYPE(BIEF_OBJ), INTENT(IN)      :: DELTAR
      TYPE(BIEF_OBJ), INTENT(IN)      :: HN,UNORM
      TYPE(BIEF_OBJ), INTENT(IN)      :: TW,UW
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: KS,KSP,KSR,KS_TEL
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: MU
      TYPE(BIEF_OBJ), INTENT(IN)      :: ACLADM
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: CF
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FW
      TYPE(BIEF_OBJ), INTENT(IN  )    :: THETAC, THETAW
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: TOB,TOBW
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: TOBCW_MEAN,TOBCW_MAX
      TYPE(BIEF_OBJ), INTENT(IN)      :: CF_TEL
      TYPE(BIEF_OBJ), INTENT(IN)      :: H_TEL
      END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE TOBCW_GAIA
     & (TOB, TOBW, THETAC, THETAW, TOBCW_MEAN, TOBCW_MAX, NPOIN)
        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: NPOIN
        DOUBLE PRECISION, INTENT(IN)    :: THETAC(NPOIN), THETAW(NPOIN)
        DOUBLE PRECISION, INTENT(IN)    :: TOB(NPOIN),TOBW(NPOIN)
        DOUBLE PRECISION, INTENT(INOUT) :: TOBCW_MEAN(NPOIN)
        DOUBLE PRECISION, INTENT(INOUT) :: TOBCW_MAX(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE GAIA_WRITE_RESULTS
     &(CODE,GRAFCOUNT,GRCOMP,COMP,LISTCOUNT,YAGOUT,T_TEL)
        IMPLICIT NONE
        CHARACTER(LEN=24), INTENT(IN) :: CODE
        INTEGER,           INTENT(IN) :: GRAFCOUNT
        INTEGER,           INTENT(IN) :: LISTCOUNT
        LOGICAL,           INTENT(IN) :: YAGOUT
        INTEGER,           INTENT(IN) :: GRCOMP
        LOGICAL,           INTENT(IN) :: COMP
        DOUBLE PRECISION,  INTENT(IN) :: T_TEL
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE GAIA_PREPARE_STEP
     &(H_TEL, U_TEL, V_TEL, CF_TEL, CHARR_TEL, CODE, DELTAR, DT_TEL,
     & HW_TEL, KS_TEL, LISTCOUNT, LOOPCOUNT, TELNIT, SUSP_TEL,
     & T_TEL, THETAW_TEL, TW_TEL, UETCAR, UW_TEL, ZF_TEL)
        USE BIEF_DEF
        IMPLICIT NONE
        INTEGER,           INTENT(IN)    :: LOOPCOUNT
        INTEGER,           INTENT(IN)    :: LISTCOUNT,TELNIT
        CHARACTER(LEN=24), INTENT(IN)    :: CODE
        TYPE(BIEF_OBJ),    INTENT(IN)    :: U_TEL,V_TEL,H_TEL
        TYPE(BIEF_OBJ),    INTENT(INOUT) :: ZF_TEL,UETCAR,KS_TEL
        TYPE(BIEF_OBJ),    INTENT(IN)    :: DELTAR
        TYPE(BIEF_OBJ),    INTENT(INOUT) :: CF_TEL
        DOUBLE PRECISION,  INTENT(IN)    :: T_TEL
        LOGICAL,           INTENT(INOUT) :: CHARR_TEL,SUSP_TEL
        DOUBLE PRECISION,  INTENT(IN)    :: DT_TEL
        TYPE(BIEF_OBJ),    INTENT(IN)    :: THETAW_TEL,HW_TEL,TW_TEL
        TYPE(BIEF_OBJ),    INTENT(IN)    :: UW_TEL
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE GAIA_SUSPENSION_DEPOSIT
     &(CODE)
        IMPLICIT NONE
        CHARACTER(LEN=24), INTENT(IN) :: CODE
        END SUBROUTINE
      END INTERFACE
!
      INTERFACE
        SUBROUTINE GAIA_BALANCE
     &(ZF_TEL,TELNIT)
        USE BIEF_DEF
        IMPLICIT NONE
        TYPE(BIEF_OBJ),    INTENT(INOUT) :: ZF_TEL
        INTEGER,           INTENT(IN)    :: TELNIT
        END SUBROUTINE
      END INTERFACE
!
!======================================================================!
!======================================================================!
!
      END MODULE INTERFACE_GAIA
