/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog3(LgIndex_t  ParentDialog)
{
  if (Dialog3Manager != BADDIALOGID)
    return;

  Dialog3Manager = TecGUIDialogCreateModal(ParentDialog,
                                          3860,
                                          1580,
                                          "Select Files",
                                          Dialog3Init_CB,
                                          Dialog3OkButton_CB,
                                          NULL,
                                          Dialog3CancelButton_CB,
                                          Dialog3HelpButton_CB);
  TelemacFiles_LBL_D3 = TecGUILabelAdd(Dialog3Manager,
                                     382,
                                     91,
                    "Telemac data files :");

  TF3_LBL_D3 = TecGUILabelAdd(Dialog3Manager,
                            382,
                            841,
                    "Delwaq data files :");

  BrowsTel_BTN_D3 = TecGUIButtonAdd(Dialog3Manager,
                                  2534,
                                  37,
                                  382,
                                  144,
                    "...",
                    BrowsTel_BTN_D3_CB);

  BrowseDel_BTN_D3 = TecGUIButtonAdd(Dialog3Manager,
                                   2419,
                                   776,
                                   382,
                                   144,
                    "...",
                    BrowseDel_BTN_D3_CB);

  FTelList_T_D3 = TecGUITextAdd(Dialog3Manager,
                              292,
                              225,
                              3260,
                              417,
                       0,
                       FTelList_T_D3_CB);

  FDelList_T_D3 = TecGUITextAdd(Dialog3Manager,
                              292,
                              980,
                              3260,
                              417,
                       0,
                       FDelList_T_D3_CB);

}

/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          5096,
                                          669,
                                          "LoadMode",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          NULL,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  DataSetLoa_RADIO_D2 = TecGUIRadioBoxAdd(Dialog2Manager,
                                        216,
                                        96,
                                        4546,
                                        433,
                                 "Create new data set and reset plot style",
                                 "Retain plot style and create new data set",
                                 "Append data to existing data set",
                                 (char *)NULL,
                                 (char *)NULL,
                                 DataSetLoa_RADIO_D2_CB);

}

/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4383,
                                          637,
                                          "Telemac data loader options",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          NULL,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  FileLoadMo_RADIO_D1 = TecGUIRadioBoxAdd(Dialog1Manager,
                                        331,
                                        85,
                                        3412,
                                        433,
                                 "Telemac result file",
                                 "Telemac + Delwaq result files",
                                 "Telemac mesh file",
                                 (char *)NULL,
                                 (char *)NULL,
                                 FileLoadMo_RADIO_D1_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
