/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog2(LgIndex_t  ParentDialog)
{
  if (Dialog2Manager != BADDIALOGID)
    return;

  Dialog2Manager = TecGUIDialogCreateModal(ParentDialog,
                                          5096,
                                          669,
                                          "Untitled",
                                          Dialog2Init_CB,
                                          Dialog2OkButton_CB,
                                          NULL,
                                          Dialog2CancelButton_CB,
                                          Dialog2HelpButton_CB);
  LoadMode_RADIO_D2 = TecGUIRadioBoxAdd(Dialog2Manager,
                                      216,
                                      96,
                                      4546,
                                      433,
                                 "Create new data set and reset plot style",
                                 "Retain plot style and create new data set",
                                 "Append data to existing data set",
                                 (char *)NULL,
                                 (char *)NULL,
                                 LoadMode_RADIO_D2_CB);

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
