/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog2Manager;
extern void BuildDialog2(LgIndex_t  ParentDialog);

extern LgIndex_t  LoadMode_RADIO_D2;
