!                   *************************
                    MODULE INTERFACE_POSTEL3D
!                   *************************
!
!
!***********************************************************************
! POSTEL3D 7.1
!***********************************************************************
!
!
!-----------------------------------------------------------------------
!
!     DEFINITION OF INTERFACES
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE COUPEH
     &(IREC,AT,Z,U,V,W,HREF,NPLREF,PLINF,NC2DH,NPOIN2,NPLAN,NCOU,
     & FFORMAT,VAR,SHZ,NVA3,TAB,TEXTELU)
      USE BIEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NC2DH,NPOIN2,NPLAN
      INTEGER, INTENT(INOUT) :: NCOU(NC2DH)
      INTEGER, INTENT(IN) :: IREC
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: W(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: AT
      DOUBLE PRECISION, INTENT(IN) :: HREF(9)
      INTEGER , INTENT(IN) :: NPLREF(9)
      INTEGER , INTENT(INOUT) :: PLINF(NPOIN2)
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TAB
      INTEGER, INTENT(IN) :: NVA3
      CHARACTER(LEN=8) :: FFORMAT
      DOUBLE PRECISION,INTENT(INOUT) :: VAR(NPOIN2),SHZ(NPOIN2)
      CHARACTER(LEN=32), INTENT(IN) :: TEXTELU(100)
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE COUPEV
     &(AT,Z,U,V,W,
     & SHP,IMSEG,X2DV,Y2DV,DISTOR,IKLES,
     & ELEM,NC2DV,NPOIN2,NELEM2,NCOU,FFORMAT,IM,JM,
     & TITCAS,NVA3,TAB,TEXTLU,N)
      USE BIEF
      IMPLICIT NONE
      INTEGER,INTENT(IN) :: NPOIN2,NELEM2,IM,JM,NC2DV
      INTEGER, INTENT(INOUT) :: NCOU(NC2DV)
      DOUBLE PRECISION ,INTENT(IN) ::AT
      DOUBLE PRECISION , INTENT(INOUT) :: SHP(IM,3,NC2DV)
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TAB
      INTEGER , INTENT(IN) :: N
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2,JM),V(NPOIN2,JM)
      DOUBLE PRECISION, INTENT(IN) :: Z(NPOIN2,JM),W(NPOIN2,JM)
      INTEGER, INTENT(IN) :: IKLES(3,NELEM2)
      INTEGER, INTENT(IN) :: ELEM(IM,NC2DV)
      INTEGER, INTENT(INOUT) :: NVA3
      INTEGER, INTENT(IN) :: IMSEG(49,NC2DV)
      DOUBLE PRECISION, INTENT(IN) :: X2DV(50,NC2DV),Y2DV(50,NC2DV)
      DOUBLE PRECISION, INTENT(IN) :: DISTOR(NC2DV)
      CHARACTER(LEN=8),  INTENT(INOUT) :: FFORMAT
      CHARACTER(LEN=32), INTENT(IN) ::TEXTLU(100)
      CHARACTER(LEN=72), INTENT(IN) ::TITCAS
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE ECRDEB
     &(CANAL,FFORMAT,TITCAS,NBVAR,C2DH,TEXTLU,IC,N)
      IMPLICIT NONE
      INTEGER ,INTENT(IN) :: NBVAR
      INTEGER, INTENT(INOUT) :: CANAL
      INTEGER, INTENT(IN) :: IC,N
      LOGICAL, INTENT(IN) :: C2DH
      CHARACTER(LEN=72), INTENT(IN) :: TITCAS
      CHARACTER(LEN=32), INTENT(IN) :: TEXTLU(100)
      CHARACTER(LEN=8), INTENT(INOUT) ::  FFORMAT
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE LECDON_POSTEL3D
     &(MOTCAR,FILE_DESC,PATH,NCAR)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)               :: NCAR
      CHARACTER(LEN=PATH_LEN), INTENT(IN)    :: PATH
      CHARACTER(LEN=PATH_LEN), INTENT(INOUT) :: FILE_DESC(4,MAXKEYWORD)
      CHARACTER(LEN=PATH_LEN), INTENT(INOUT) :: MOTCAR(MAXKEYWORD)
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE LECR3D
     &(IREC,AT,Z,U,V,W,NPOIN3,NPOIN2,NPLAN,NRES,FFORMAT,NVA3,TAB)
      USE BIEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IREC
      INTEGER, INTENT(IN) :: NPOIN3,NPOIN2,NPLAN,NRES
      CHARACTER(LEN=8), INTENT(IN) :: FFORMAT
      INTEGER, INTENT(INOUT) :: NVA3
      TYPE (BIEF_OBJ) , INTENT(INOUT) :: TAB
      DOUBLE PRECISION , INTENT(INOUT) :: AT
      DOUBLE PRECISION , INTENT(INOUT) :: U(NPOIN3)
      DOUBLE PRECISION , INTENT(INOUT) :: V(NPOIN3)
      DOUBLE PRECISION , INTENT(INOUT) :: W(NPOIN3)
      DOUBLE PRECISION , INTENT(INOUT) :: Z(NPOIN2,NPLAN)
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE PRE2DH
     &(X,Y,IKLES,IPOBO,NPOIN2,NELEM2,NC2DH,NCOU,TITCAS,
     & FFORMAT,NVA3,TEXTLU,X_ORIG,Y_ORIG)
      IMPLICIT NONE
      INTEGER, INTENT(IN) ::NPOIN2,NELEM2,NC2DH
      INTEGER, INTENT(INOUT) :: NCOU(NC2DH)
      DOUBLE PRECISION, INTENT(IN) :: X(NPOIN2),Y(NPOIN2)
      CHARACTER(LEN=72), INTENT(IN) :: TITCAS
      INTEGER , INTENT(INOUT) :: IKLES(3,NELEM2),IPOBO(NPOIN2)
      CHARACTER(LEN=32), INTENT(IN) :: TEXTLU(100)
      CHARACTER(LEN=8),INTENT(INOUT) :: FFORMAT
      INTEGER,INTENT(IN) :: NVA3
      INTEGER, INTENT(IN) :: X_ORIG,Y_ORIG
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE PRE2DV
     &(X,Y,SHP,NSEG,IMSEG,X2DV,Y2DV,IKLES,ELEM,NPOIN2,NELEM2,
     & IM,NC2DV)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2,NELEM2,IM,NC2DV
      DOUBLE PRECISION, INTENT(IN) :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION , INTENT(INOUT) :: SHP(IM,3,NC2DV)
      DOUBLE PRECISION, INTENT(IN) :: X2DV(50,NC2DV),Y2DV(50,NC2DV)
      INTEGER, INTENT(INOUT) :: IKLES(3,NELEM2)
      INTEGER, INTENT(INOUT) :: ELEM(IM,NC2DV)
      INTEGER, INTENT(INOUT) :: NSEG(NC2DV),IMSEG(49,NC2DV)
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
      SUBROUTINE NOMTRA
     &(NOMTAC,NOMTPA,NTRAC,NTRPA)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NTRAC,NTRPA
      CHARACTER(LEN=32), INTENT(INOUT) :: NOMTAC(NTRAC),NOMTPA(NTRPA)
      END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      END MODULE INTERFACE_POSTEL3D
