unset HOMETEL
unset SYSTELCFG
unset USETELCFG
unset SOURCEFILE
unset PYTHONUNBUFFERED
unset PYTHONPATH
unset LD_LIBRARY_PATH
unset SYSTEL
unset MPIHOME
unset HDF5HOME
unset LD_RUN_PATH
unset MEDHOME
unset MUMPSHOME
unset SCALAPACKHOME
unset BLACSHOME
unset METISHOME
export PATH=/home/tomsail/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin