{% set name = "telemac" %}
{% set version = "8.4" %}
{% set build = 0 %}
{% set mpi = "openmpi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  path: ../
  url: https://github.com/tomsail/telemac-conda/archive/refs/tags/v8.4.tar.gz
  sha256: 7326fc4181ed37ace6b289a789bca9f1e8371b7c6e1655dc9c69198c9cc512db

build:
  number: {{ build }}
  skip: true #[win]

outputs:
  - name: telemac
    script: build.sh
    build:
      {% set mpi_prefix = "mpi_" + mpi %}
      string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
      {% set build_pin = mpi_prefix + '_*' %}
    files:
     - scripts
     - sources
     - builds
     - configs
     - etc/conda/deactivate.d/env_var_telemac_activate.sh
     - etc/conda/activate.d/env_var_telemac_activate.sh

    requirements:
      build:
      host:
        - python 
        - numpy =1.21.6
        - {{ compiler('fortran') }}
        - {{ mpi }}
        - {{ mpi }}-mpifort
        - metis
        - parmetis
        - openblas
        - liblapack
      run:
        - python
        - numpy =1.21.6
        - {{ compiler('fortran') }}
        - {{ mpi }}
        - {{ mpi }}-mpifort
        - metis
        - parmetis
        - openblas
        - liblapack
        - scipy
        - netcdf4
        - mpi4py
        - matplotlib

about:
  home: https://gitlab.pam-retd.fr/otm/telemac-mascaret
  license: Apache-2
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'TELEMAC Suite with all the modules and API functions'

extra:
  recipe-maintainers:
    - brey
    - tomsail
