{% set name = "telemac" %}
{% set version = "0.1.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomsail/telemac-conda/archive/refs/tags/v8.4.tar.gz
  #sha256: 6ee77a34b1b827463b7a61e00149b1781af7db340d329b8e36bdcd85ae545553

build:
  number: {{ build }}
  skip: true #[win]

outputs:
  - name: telemac
    script: build.sh
    files: 
     - scripts
     - sources 
     - builds
     - configs
    
    requirements:
      build:
        - python =3.10
        - numpy =1.23
        - {{ compiler('fortran') }}
        - openmpi
        - openmpi-mpifort
        - metis
        - parmetis
        - openblas
        - liblapack
      host:
        - python =3.10
        - numpy =1.23
        - {{ compiler('fortran') }}
        - openmpi
        - openmpi-mpifort
        - metis
        - parmetis
        - openblas
        - liblapack
      run:
        - scipy
        - netcdf4
        - mpi4py
        - matplotlib
        - mpi4py

    test:
      commands:
        - echo $BUILD_PREFIX
        - echo {{ environ.get('PREFIX') }}
        - echo {{ environ.get('SRC_DIR') }}
        - export HOMETEL={{ environ.get('SRC_DIR') }}
        - python3 -c "import time; print('sleep');time.sleep(300)"
        - source $HOMETEL/configs/pysource.template.sh

about:
  home: https://gitlab.pam-retd.fr/otm/telemac-mascaret
  license: Apache-2
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'TELEMAC Suite with all the modules and API functions'

extra:
  recipe-maintainers:
    - brey
    - tomsail
