/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/



/**
 */
void BuildDialog1(LgIndex_t  ParentDialog)
{
  if (Dialog1Manager != BADDIALOGID)
    return;

  Dialog1Manager = TecGUIDialogCreateModal(ParentDialog,
                                          4383,
                                          567,
                                          "serafinloader",
                                          Dialog1Init_CB,
                                          Dialog1OkButton_CB,
                                          NULL,
                                          Dialog1CancelButton_CB,
                                          Dialog1HelpButton_CB);
  XYPLOT_TOG_D1 = TecGUIToggleAdd(Dialog1Manager,
                                356,
                                75,
                                3934,
                                128,
                               "Create XY plot for auxiliary data",
                               XYPLOT_TOG_D1_CB);

  BrowseButton_BTN_D1 = TecGUIButtonAdd(Dialog1Manager,
                                      3845,
                                      283,
                                      382,
                                      144,
                    "...",
                    BrowseButton_BTN_D1_CB);

  FileName_TF_D1 = TecGUITextFieldAdd(Dialog1Manager,
                                    1349,
                                    289,
                                    2368,
                                    144,
                       FileName_TF_D1_CB);

  text_LBL_D1 = TecGUILabelAdd(Dialog1Manager,
                             152,
                             326,
                    "File Name :");

}


/**
 */
void InitTGB(void)
{
/* Currently not used */
}
