/***************************************************
 *                                                 *
 *  NOTE!  This file is automatically generated by *
 *         the Tecplot GUI Builder.  It is highly  *
 *         recommended that you never edit this    *
 *         file directly!                          *
 *                                                 *
 ***************************************************/


extern void InitTGB(void);
extern LgIndex_t Dialog1Manager;
extern void BuildDialog1(LgIndex_t  ParentDialog);

extern LgIndex_t  XYPLOT_TOG_D1;
extern LgIndex_t  BrowseButton_BTN_D1;
extern LgIndex_t  FileName_TF_D1;
extern LgIndex_t  text_LBL_D1;
